### ISSUE TITLE
P:下拉刷新时数据马上满屏，底部出现上拉的Footer！

### ISSUE THREAD

**Issue by jaime1990** [peng8350/flutter_pulltorefresh#102]
> 如下图，我在下拉刷新时数据加载到距离底部还有一个item的距离时，底部就会出现Load More字样，并且无法自动消失，待下次再下拉刷新时才会消失，烦请大佬帮忙看看！急~~~

![Screenshot_20190605_112853 1](https://user-images.githubusercontent.com/11324995/58928536-74b61180-8785-11e9-9b61-f758ab5fcb40.jpg)

**Comment by jaime1990** [comment]
目前使用的版本是1.4.1

**Comment by peng8350** [comment]
如果这个很严谨的话,可以设置hideWhenNotFull为false,然后用enablePullUp来判断。这个问题可以干掉,但是底部指示器还要引用头部指示器里的状态。

**Comment by jaime1990** [comment]
> enablePullUp

谢谢，请问有示例么？

**Comment by peng8350** [comment]
#37

**Comment by jaime1990** [comment]
> #37

好的，非常感谢~
