### ISSUE TITLE
TabBarView同步刷新的问题

### ISSUE THREAD

**Issue by zrgnosis** [peng8350/flutter_pulltorefresh#103]
每个TabBarView中都创建了一个RefreshController，并且设置了 initialRefresh:true
每次切换到一个新的 Tab 时，先前切换过的 TabBarView 中的列表都会再刷新一次。

接着测试发现，通过下面这种方式设置刷新，也会出现上面说的问题。
initState(){
      SchedulerBinding.instance.addPostFrameCallback((_) {
            _refreshController.requestRefresh();
           });
}

只有手动下拉刷新才不会出现上面的问题。

版本：1.4.0

在测试 1.4.1 时，发现了新的问题，不管是设置 initialRefresh:true 还是 initState 中设置 _refreshController.requestRefresh(); 都不执行首次下拉刷新了。

**Comment by peng8350** [comment]
这个问题是和 #101 一样的,主要是我每次改动代码,要不就是忽略了FrontStyle的情况,要不就忽略了另外一边。我现在正在想办法让Front,Behind,Follow,UnFollow这四种样式区分度不大,不然以后更新也麻烦。主动刷新,其实下面的代码等同

```

SchedulerBinding.instance.addPostFrameCallback((_) {
    _refreshController.scrollController.animateTo(-80.0);
});
}
```

**Comment by peng8350** [comment]
TabBarView问题,那是因为你没有keepAlive吧

**Comment by peng8350** [comment]
好吧，之前我误解楼主的意思了，这个问题刚刚发现了，tabbarview里多个keepalive组件共用scrollcontroller,某一个调用requestRefresh方法触发其他的共用同时触发刷新。共用同一个scrollController出现的问题，看来只能弃用scrollcontroller,改为scrollPosition
