### ISSUE TITLE
上拉底部加载怎么一直显示，然后没有旋转动画

### ISSUE THREAD

**Issue by wyxuan** [peng8350/flutter_pulltorefresh#105]
上拉底部加载怎么一直显示，就是加载完成后不隐藏。使用全局那个方式的话怎么没有回调参数

**Comment by peng8350** [comment]
1.旋转动画你要自定义指示器，Readme里也有
2.大部分app上拉加载都是加载完成后仍然显示的,你说的上拉加载更多隐藏效果需求，最好给个gif图，我看看能不能实现
3.你要什么回调参数

**Comment by peng8350** [comment]
估计楼主说的是像下拉刷新那样需要手拖下来然后隐藏掉，1.1.6貌似有这功能，之后大改api就去掉这个了。一般都会选择快到底部时就触发加载更多

**Comment by wmyasw** [comment]
加载更多 完成后 隐藏的footer 比较好吧， 
现在的问题 在加载更多 失败之后，就算自己重置 也需要增加延迟操作，而且体验不是很好。
能否在footer 加载更多完成之后 在内部增加这个操作，设置几百毫秒 自动隐藏 底部指示器?

**Comment by peng8350** [comment]
隐藏回弹footer,参考[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/customindicator/footer_underscroll.dart)的实现,
