### ISSUE TITLE
手势过快会导致页面超出可视范围

### ISSUE THREAD

**Issue by daniuwo** [peng8350/flutter_pulltorefresh#111]
升级1.4.5后滑动手势过快导致页面滚动距离太远超出了屏幕可视范围, 整个页面都跑出屏幕可视范围了,过一会儿才会自动划回来

**Comment by peng8350** [comment]
请给个样例代码,我这里不知道重现这问题,还有我想知道这几个问题:
1.是下拉还是上拉?
2.大概在ScrollView的什么位置(offset=?)滑动手势太快造成这现象?

**Comment by peng8350** [comment]
暂时给child里ScrollView强定义physics:BouncingScrollPhysics(),可临时解决。

**Comment by daniuwo** [comment]
> 暂时给child里ScrollView强定义physics:BouncingScrollPhysics(),可临时解决。

非常感谢 问题得到解决.

**Comment by gaojuanjuan** [comment]
1.4.6也有这个问题

**Comment by peng8350** [comment]
这个问题有一定可能性还是会存在的,存在的原因十不离九是因为maxOverScrollExtent或者maxUnderScrollExtent默认是double.infite,如果还遇到这个问题的话,给这个属性一个有限值
