### ISSUE TITLE
Refresh Indicator error

### ISSUE THREAD

**Issue by medke** [peng8350/flutter_pulltorefresh#113]
I am using pull_to_refresh plugin in two project, they are both running the same code (SmartRefresher that has a ListView child) and on the same machine. One of them is working fine, the second one is showing this error:

I/flutter (31927): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (31927): The following NoSuchMethodError was thrown while dispatching notifications for
I/flutter (31927): ValueNotifier<RefreshStatus>:
I/flutter (31927): The method 'call' was called on null.
I/flutter (31927): Receiver: null
I/flutter (31927): Tried calling: call()
I/flutter (31927): 
I/flutter (31927): When the exception was thrown, this was the stack:
I/flutter (31927): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (31927): #1      RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:160:16)
I/flutter (31927): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter (31927): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:266:5)
I/flutter (31927): #4      _RefreshIndicatorState&State&IndicatorStateMixin.mode= (package:pull_to_refresh/src/internals/indicator_wrap.dart:324:28)
I/flutter (31927): #5      RefreshIndicatorState._dispatchModeByOffset.<anonymous closure> (package:pull_to_refresh/src/internals/indicator_wrap.dart:118:9)
I/flutter (31927): (elided 13 frames from package dart:async)
I/flutter (31927): 
I/flutter (31927): The ValueNotifier<RefreshStatus> sending notification was:
I/flutter (31927):   ValueNotifier<RefreshStatus>#276ac(RefreshStatus.refreshing)

**Comment by peng8350** [comment]
May be headerMode=null,you should debug.If you can give more details,I will find out reason easily
