### ISSUE TITLE
切换皮肤后_refreshController.position.addListener()不回调了

### ISSUE THREAD

**Issue by tianyu704** [peng8350/flutter_pulltorefresh#114]
使用Provider管理皮肤颜色，当切换皮服之后，执行了didChangeDependencies(),但_refreshController.position.addListener()这里面再上下滑动时不回调了

**Comment by peng8350** [comment]
90%的可能性是因为内部ScrollPosition被更新替换了,你需要在更新那一刻重新addListener

**Comment by peng8350** [comment]
如果你需要监听位置变化,给child设置ScrollController好点,虽然代价是失去ios滚动顶部功能

**Comment by tianyu704** [comment]
好的，确实重新addListener管用，不过，得延时setData更新一下。给child设置ScrollController也是管用的。改成设置给child设置ScrollController了
