### ISSUE TITLE
1.4.6 报错

### ISSUE THREAD

**Issue by 3067200952** [peng8350/flutter_pulltorefresh#116]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  RefreshController c = RefreshController();
  @override
  void dispose() { 
    c.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SmartRefresher(
        controller: c,
        enablePullDown: true,
        enablePullUp: false,
        onRefresh: ()async{
          await Future.delayed(Duration(milliseconds: 1000));
          c.refreshCompleted();
        },
        child: ListView.builder(
          itemBuilder: (ctx,index){
            return Container(
              margin: EdgeInsets.only(top: 10),
              color: Colors.red,
              height: 20,
            );
          },
        ),
      ),
    );
  }
}

**Comment by 3067200952** [comment]
I/flutter (11587): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (11587): The following assertion was thrown during performLayout():
I/flutter (11587): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1283 pos 12:
I/flutter (11587): 'correctedOffset.isFinite': is not true.

**Comment by peng8350** [comment]
直接复制代码，问题没出现。具体再详细描述一下，模拟器，flutter版本号。

**Comment by 3067200952** [comment]
非常抱歉，目前问题已经不存在了，昨天升级过后，只要滑动就报错卡死，今天重新测试了几次，发现问题已经不存在了，不清楚昨天是什么情况

**Comment by 3067200952** [comment]
项目升级后，发现了新的问题，内部的listview，gridview等的padding属性无效了，默认的physics在快速下滑的时候，可以直接触发刷新

**Comment by peng8350** [comment]
#115 已经修正padding属性问题,版本暂未发布, 你可以在child里用ClampingScrollPhysics,这样快速下滑撞到顶部时会停下来。

**Comment by 3067200952** [comment]
ok,感谢

**Comment by 50431040** [comment]
'correctedOffset.isFinite': is not true. 
请问这个怎么解决的
