### ISSUE TITLE
1.4.6因为IOS列表滑动的惯性导致自动触发刷新问题

### ISSUE THREAD

**Issue by luckysmg** [peng8350/flutter_pulltorefresh#118]
因为惯性，导致我很快滑倒顶部的时候自动触发了刷新，能不能就是设置在惯性到达顶部的时候不刷新呢？

**Comment by peng8350** [comment]
暂时没有布尔值控制,下个版本考虑追加

**Comment by peng8350** [comment]
已经修复,enableBallsticRefresh可控制这点，默认为false,不根据弹性触发刷新,这点之前我没注意到
