### ISSUE TITLE
Custom header doesn't receive onTap event

### ISSUE THREAD

**Issue by pedromassango** [peng8350/flutter_pulltorefresh#120]
I have a custom header with a button inside, when I click the button it doesn't recieve the onTap event.
@peng8350

**Comment by peng8350** [comment]
Yes，it doesn‘t support ontap before 1.4.7 .I think it no need to add on tap.after adding. Twolevel feature ,on tap now support

**Comment by pedromassango** [comment]
Maybe you should let it up to the user. 

I fixed by upgrading to the version 1.4.7. Thanks for the library @peng8350
