### ISSUE TITLE
关于listview controller的问题

### ISSUE THREAD

**Issue by crystal-lee** [peng8350/flutter_pulltorefresh#121]
我想做一个聊天的界面，首先加载15条，并且list view定位到最后，
当下拉的时候，我会在list view的0位置添加新的15条数据，但这时候会跳到第0条
我想加载新数据后，不要跳转，需要使用list view的controller控制位置，但是设置controller报错了

不论给不给SmartRefresher设置controller都会报错

```
Widget buildView(ChatContentListState state, Dispatch dispatch,
    ViewService viewService) {
  final ListAdapter adapter = viewService.buildAdapter();
  state.controller2.jumpTo(state.controller2.position.maxScrollExtent);
  return Column(children: <Widget>[
    Expanded(
        child: SmartRefresher(controller: null,
        onRefresh: () => dispatch(ChatContentListActionCreator.onRefreshAction()),
        enablePullDown: true,
        enablePullUp: false,
//        controller: state.controller,
          child: ListView.builder(
            controller: state.controller2,
            itemBuilder: adapter.itemBuilder,
            itemCount: adapter.itemCount,),
        ))
  ],);
```

**Comment by peng8350** [comment]
首先Smartrefrefresh里controller一定不能为null,其次，我不明白为什么你要在build方法里jumpTo，这时界面还没重刷出来的，所以会出现你说的跳到第0条

**Comment by crystal-lee** [comment]
我再试试，Smartrefrefresh里的controller为null的时候不是会取ListView的controller么？

第一次加载要定位到最后一条，然后每次下拉加载定位到当前位置，我需要list view的Controller去控制位置

如果Smartrefrefresh 设置了controller ，ListView也设置controller，会报错

**Comment by peng8350** [comment]
大佬，你应该在listView开启reverse:true,然后enablepullup 为true,在，这样才是实现翻转的正确做法.例子我已经在readme里给出了

**Comment by crystal-lee** [comment]
大佬，你说的对，这样可以了。。。
谢谢大佬🙏

**Comment by crystal-lee** [comment]
大哥，又被卡住了，使用了reverse后，下拉加载更多数据很完美，
但是如果数据小于一屏的时候，上面就会留出空白了，这个有方法处理么

**Comment by peng8350** [comment]
那不是空白,是footer被隐藏掉了,因为很多人的需求是不满一屏就隐藏掉它。如果你不想隐藏,全局设置hideFooterWhenNorFull为false即可

**Comment by crystal-lee** [comment]
应该不是这个意思，因为reverse了。
如果数据很多，显示正常

但如果数据不满一屏，我想让数据靠上显示，而不是显示到最下面

**Comment by peng8350** [comment]
你可以不满一屏时关闭刷新,满一屏就开刷新,翻转数据源

**Comment by crystal-lee** [comment]
新手，不太会，还在入门，就先这样把。
item的高度也不一定，算起来也麻烦。
谢谢哥
