### ISSUE TITLE
android默认的physics效果导致调用_refreshController.requestRefresh()无法刷新

### ISSUE THREAD

**Issue by a272312970** [peng8350/flutter_pulltorefresh#123]
android默认的physics效果，scrollPosition如果不是在顶部，快速滚动到顶部会有一个阻断效果，并不会下拉到能刷新的位置，导致调用_refreshController.requestRefresh()无法刷新，请问有好的解决办法吗？

**Comment by peng8350** [comment]
这个问题刚刚已经发现并解决了,正准备push版本
