### ISSUE TITLE
关于在安卓中的惯性越界回弹

### ISSUE THREAD

**Issue by luckysmg** [peng8350/flutter_pulltorefresh#124]
在iOS中，利用惯性到达顶部的时候如果速度不为0，那么会触发越界回弹，但是SmartRefresher在安卓中利用惯性到达顶部的时候如果速度不为0时会弹出水波纹的效果而不是越界回弹，能否加一个这样的效果从而让安卓和iOS两端的体验一致呢，就是能够有越界回弹的效果，或者设置一个属性让用户定制是否启用越界回弹

**Comment by peng8350** [comment]
如果你想两个平台惯性越界的话，设置BouncingScrollPhysics即可

**Comment by peng8350** [comment]
Clamping阻断它肯定是要的，不然会冲出视图范围

**Comment by luckysmg** [comment]
感觉不行😂，BouncingScrollPhysics在你的刷新框架下并没有用

**Comment by peng8350** [comment]
```

ListView.separated(
      physics: BouncingScrollPhysics(),

```
可以起作用

**Comment by luckysmg** [comment]
但是我的场景用不了这个啊，我整体是一个SmartRefresher包裹listView，然后listVIew的孩子有一个轮播图和一个listView

**Comment by peng8350** [comment]
那我不太明白你的场景是什么,能不能具体描述一下或者给个样例代码,就是你上面不是说了,两个平台效果一样,又要通过惯性越界回弹的话,就是Bouncing最适合了

**Comment by luckysmg** [comment]
我的代码和图片发你邮箱了你看看呗

**Comment by luckysmg** [comment]
如图

**Comment by luckysmg** [comment]
`import 'package:cached_network_image/cached_network_image.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app/entity/news_entity.dart';
import 'package:flutter_app/entity_factory.dart';
import 'package:flutter_app/other_pages/item_detail_page.dart';
import 'package:flutter_swiper/flutter_swiper.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

NewsEntity _newsEntity;
RefreshController _refreshController = RefreshController(initialRefresh: false);
GlobalKey<_HomePageState> _homePageKey = GlobalKey();

RefreshController getRefreshController() {
  return _refreshController;
}

List<String> _imageUrl = [
  'http://pic37.nipic.com/20140113/8800276_184927469000_2.png',
  'http://pic29.nipic.com/20130530/12174133_162640398000_2.jpg',
  'http://pic.58pic.com/58pic/13/82/74/92q58PICeSI_1024.jpg',
  'http://pic25.nipic.com/20121112/9252150_150552938000_2.jpg'
];

dynamic _page = 1;

class HomePage extends StatefulWidget {

  HomePage({Key  key}) : super(key: _homePageKey);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  dynamic type = 1;

  @override
  void initState() {
    super.initState();
    _getHttpInfo().then((data) {
      setState(() {
        _newsEntity = EntityFactory.generateOBJ(data);
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_newsEntity == null) {
      return Scaffold(
        appBar: AppBar(
          title: Text('首页'),
          backgroundColor: Colors.red,
        ),
        body: Center(
          child: CupertinoActivityIndicator(
            radius: 15,
          ),
        ),
      );
    } else {
      return Scaffold(
        appBar: AppBar(
          title: Text('首页'),
          backgroundColor: Colors.red,
        ),
        body: RefreshConfiguration(
          enableBallisticRefresh: false,
          headerBuilder: () => WaterDropHeader(),
          footerBuilder: () => ClassicFooter(),
          child: SmartRefresher(
            enablePullUp: true,
            enablePullDown: true,
            controller: _refreshController,
            onRefresh: _refreshData,
            onLoading: _loadMoreData,
            child: MainView(),
          ),
        ),
      );
    }
  }
}

void _loadMoreData() {
  _page++;
  _getHttpInfo().then((data) {
    NewsEntity tempEntity = EntityFactory.generateOBJ(data);
    _homePageKey.currentState.setState(() {
      _newsEntity.data.addAll(tempEntity.data);
      tempEntity = null;
      _refreshController.loadComplete();
    });
  });
}

void _refreshData() {
  _page = 1;
  _getHttpInfo().then((data) {
    _homePageKey.currentState.setState(() {
      _newsEntity = null;
      _newsEntity = EntityFactory.generateOBJ(data);
      _refreshController.refreshCompleted();
    });
  });
}

Future _getHttpInfo() async {
  Response response = await Dio().get('https://www.apiopen.top/satinGodApi',
      queryParameters: {'type': 1, 'page': _page});
  print(response.data);
  return response.data;
}

class MainView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: true,
      physics: BouncingScrollPhysics(),
      children: <Widget>[
        SizedBox(
          height: ScreenUtil.getInstance().setHeight(30),
        ),
        Container(
          height: ScreenUtil.getInstance().setHeight(300),
          child: Swiper(
            itemBuilder: (context, index) {
              return ClipRRect(
                borderRadius: BorderRadius.circular(18),
                child: Image.network(
                  _imageUrl[index],
                  fit: BoxFit.cover,
                ),
              );
            },
            itemCount: _imageUrl.length,
            viewportFraction: 0.9,
            scale: 0.85,
            autoplay: true,
          ),
        ),
        SizedBox(
          height: ScreenUtil.getInstance().setHeight(20),
        ),
        ListView.builder(
          itemBuilder: ((context, index) {
            return _ListItem(index);
          }),
          physics: NeverScrollableScrollPhysics(),
          shrinkWrap: true,
          itemCount: _newsEntity.data.length,
        ),
      ],
    );
  }
}

class _ListItem extends StatelessWidget {
  int _index;

  _ListItem(this._index);

  @override
  Widget build(BuildContext context) {
    return InkWell(
      splashColor: Colors.transparent,
      onTap: () {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (BuildContext context) =>
                DetailPage(_newsEntity.data[_index])));
      },
      child: Row(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.all(15),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(18),
              child: CachedNetworkImage(
                imageUrl: _newsEntity.data[_index].header,
                width: ScreenUtil.getInstance().setWidth(130),
                height: ScreenUtil.getInstance().setHeight(120),
                fit: BoxFit.fill,
              ),
            ),
          ),
          SizedBox(
            width: ScreenUtil.getInstance().setWidth(20),
          ),
          Container(
            width: ScreenUtil.getInstance().setWidth(480),
            height: ScreenUtil.getInstance().setHeight(120),
            child: Stack(
              children: <Widget>[
                Container(
                  alignment: Alignment.topLeft,
                  child: Text(
                    _newsEntity.data[_index].text,
                    maxLines: 3,
                    textAlign: TextAlign.left,
                    overflow: TextOverflow.ellipsis,
                    style: TextStyle(
                      fontSize: ScreenUtil.getInstance().setSp(22),
                      fontStyle: FontStyle.italic,
                    ),
                  ),
                ),
                Align(
                  alignment: Alignment.bottomLeft,
                  child: Text(
                    _newsEntity.data[_index].passtime,
                    style: TextStyle(color: Colors.black38),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
`

**Comment by luckysmg** [comment]
import 'package:cached_network_image/cached_network_image.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app/entity/news_entity.dart';
import 'package:flutter_app/entity_factory.dart';
import 'package:flutter_app/other_pages/item_detail_page.dart';
import 'package:flutter_swiper/flutter_swiper.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

NewsEntity _newsEntity;
RefreshController _refreshController = RefreshController(initialRefresh: false);
GlobalKey<_HomePageState> _homePageKey = GlobalKey();

RefreshController getRefreshController() {
  return _refreshController;
}

List<String> _imageUrl = [
  'http://pic37.nipic.com/20140113/8800276_184927469000_2.png',
  'http://pic29.nipic.com/20130530/12174133_162640398000_2.jpg',
  'http://pic.58pic.com/58pic/13/82/74/92q58PICeSI_1024.jpg',
  'http://pic25.nipic.com/20121112/9252150_150552938000_2.jpg'
];

dynamic _page = 1;

class HomePage extends StatefulWidget {

  HomePage({Key  key}) : super(key: _homePageKey);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  dynamic type = 1;

  @override
  void initState() {
    super.initState();
    _getHttpInfo().then((data) {
      setState(() {
        _newsEntity = EntityFactory.generateOBJ(data);
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    if (_newsEntity == null) {
      return Scaffold(
        appBar: AppBar(
          title: Text('首页'),
          backgroundColor: Colors.red,
        ),
        body: Center(
          child: CupertinoActivityIndicator(
            radius: 15,
          ),
        ),
      );
    } else {
      return Scaffold(
        appBar: AppBar(
          title: Text('首页'),
          backgroundColor: Colors.red,
        ),
        body: RefreshConfiguration(
          enableBallisticRefresh: false,
          headerBuilder: () => WaterDropHeader(),
          footerBuilder: () => ClassicFooter(),
          child: SmartRefresher(
            enablePullUp: true,
            enablePullDown: true,
            controller: _refreshController,
            onRefresh: _refreshData,
            onLoading: _loadMoreData,
            child: MainView(),
          ),
        ),
      );
    }
  }
}

void _loadMoreData() {
  _page++;
  _getHttpInfo().then((data) {
    NewsEntity tempEntity = EntityFactory.generateOBJ(data);
    _homePageKey.currentState.setState(() {
      _newsEntity.data.addAll(tempEntity.data);
      tempEntity = null;
      _refreshController.loadComplete();
    });
  });
}

void _refreshData() {
  _page = 1;
  _getHttpInfo().then((data) {
    _homePageKey.currentState.setState(() {
      _newsEntity = null;
      _newsEntity = EntityFactory.generateOBJ(data);
      _refreshController.refreshCompleted();
    });
  });
}

Future _getHttpInfo() async {
  Response response = await Dio().get('https://www.apiopen.top/satinGodApi',
      queryParameters: {'type': 1, 'page': _page});
  print(response.data);
  return response.data;
}

class MainView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: true,
      physics: BouncingScrollPhysics(),
      children: <Widget>[
        SizedBox(
          height: ScreenUtil.getInstance().setHeight(30),
        ),
        Container(
          height: ScreenUtil.getInstance().setHeight(300),
          child: Swiper(
            itemBuilder: (context, index) {
              return ClipRRect(
                borderRadius: BorderRadius.circular(18),
                child: Image.network(
                  _imageUrl[index],
                  fit: BoxFit.cover,
                ),
              );
            },
            itemCount: _imageUrl.length,
            viewportFraction: 0.9,
            scale: 0.85,
            autoplay: true,
          ),
        ),
        SizedBox(
          height: ScreenUtil.getInstance().setHeight(20),
        ),
        ListView.builder(
          itemBuilder: ((context, index) {
            return _ListItem(index);
          }),
          physics: NeverScrollableScrollPhysics(),
          shrinkWrap: true,
          itemCount: _newsEntity.data.length,
        ),
      ],
    );
  }
}

class _ListItem extends StatelessWidget {
  int _index;

  _ListItem(this._index);

  @override
  Widget build(BuildContext context) {
    return InkWell(
      splashColor: Colors.transparent,
      onTap: () {
        Navigator.of(context).push(MaterialPageRoute(
            builder: (BuildContext context) =>
                DetailPage(_newsEntity.data[_index])));
      },
      child: Row(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.all(15),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(18),
              child: CachedNetworkImage(
                imageUrl: _newsEntity.data[_index].header,
                width: ScreenUtil.getInstance().setWidth(130),
                height: ScreenUtil.getInstance().setHeight(120),
                fit: BoxFit.fill,
              ),
            ),
          ),
          SizedBox(
            width: ScreenUtil.getInstance().setWidth(20),
          ),
          Container(
            width: ScreenUtil.getInstance().setWidth(480),
            height: ScreenUtil.getInstance().setHeight(120),
            child: Stack(
              children: <Widget>[
                Container(
                  alignment: Alignment.topLeft,
                  child: Text(
                    _newsEntity.data[_index].text,
                    maxLines: 3,
                    textAlign: TextAlign.left,
                    overflow: TextOverflow.ellipsis,
                    style: TextStyle(
                      fontSize: ScreenUtil.getInstance().setSp(22),
                      fontStyle: FontStyle.italic,
                    ),
                  ),
                ),
                Align(
                  alignment: Alignment.bottomLeft,
                  child: Text(
                    _newsEntity.data[_index].passtime,
                    style: TextStyle(color: Colors.black38),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by luckysmg** [comment]
class MainView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      shrinkWrap: true,
      physics: BouncingScrollPhysics(),
      children: <Widget>[
        SizedBox(
          height: ScreenUtil.getInstance().setHeight(30),
        ),
        Container(
          height: ScreenUtil.getInstance().setHeight(300),
          child: Swiper(
            itemBuilder: (context, index) {
              return ClipRRect(
                borderRadius: BorderRadius.circular(18),
                child: Image.network(
                  _imageUrl[index],
                  fit: BoxFit.cover,
                ),
              );
            },
            itemCount: _imageUrl.length,
            viewportFraction: 0.9,
            scale: 0.85,
            autoplay: true,
          ),
        ),
        SizedBox(
          height: ScreenUtil.getInstance().setHeight(20),
        ),
        ListView.builder(
          itemBuilder: ((context, index) {
            return _ListItem(index);
          }),
          physics: NeverScrollableScrollPhysics(),
          shrinkWrap: true,
          itemCount: _newsEntity.data.length,
        ),
      ],
    );
  }
}


其中这个MainView的外层被smartRefresh包裹

**Comment by peng8350** [comment]
你用法错了，ListView只能放在SmartRefresher里的child里，因为我内部机制就是判断child是不是ScrollView，是的话取slivers,不是就封一个slivertoboxadapter,你这里相当于scrollable嵌套了。

**Comment by peng8350** [comment]
你MainView里外围ListView可以换成Column
