### ISSUE TITLE
为啥，我运行demo都运行不了？

### ISSUE THREAD

**Issue by Alexwsc** [peng8350/flutter_pulltorefresh#125]
看了原项目，发现example里也有pubspec.yaml配置文件，果断只运行这个，可是各种报错，看了pubspec.yaml才知道，里面真是错误百出，连基本的运行环境environment:都没有配置，果断配置，可是还是红色一大片，在lib的dart文件，导包总是提示找不到，连最基本的import 'package:flutter/material.dart';都找不到，放弃此路，接着运行整个工程，可是就不明白了，为啥有2个pubspec.yaml配置文件，主目录有，example也有，真是，如果是我的问题，那为啥我运行其他的项目都能正常运行，希望原作者能整理一下，最起码能让我download下来，导包，配置一下pubspec.yaml配置文件，（或者是release版本，配置一下）能正常运行起来example。

**Comment by peng8350** [comment]
问题没出现,我在example里pubspec.yaml get一下就ok了,等待遇到和楼主同样问题的人解答

**Comment by JakeWoki** [comment]
把example里的refresh_animatedlist_example.dart里的import 'package:example/other/refresh_animatedlist.dart';去掉
也有可能还要把android的sdk版本改成你本地的一致
