### ISSUE TITLE
1.4.9 Android列表滑动的惯性导致自动触发刷新问题

### ISSUE THREAD

**Issue by bailyzheng** [peng8350/flutter_pulltorefresh#127]
https://github.com/peng8350/flutter_pulltorefresh/issues/118

加了enableBallisticRefresh: false依然不行，从底部滑动到顶部就会触发刷新

**Comment by peng8350** [comment]
贴出样例代码,问题不能重现,安卓真机测试。你用Notificationlistener打印一下这个print(_refreshController.position.activity),因为只有DragScrollActivity或者DrivenActivity才可以触发刷新的逻辑

**Comment by bailyzheng** [comment]
@peng8350 我观察错了，enableBallisticRefresh属性是有效的，滚动到最上方的时候那个刷新图标会显示出来，但是实际上并没有请求数据。

如果这个刷新图标向上滚动的时候不显示出来就好了

**Comment by peng8350** [comment]
之前版本有对clamping引擎惯性拦截越界回滚操作，拦截它越界也是不好的，主要是那个水波纹的效果没办法去掉，看起来很奇怪的。

**Comment by bailyzheng** [comment]
不会触发刷新操作，本问题关闭，其他优化项再提issue
