### ISSUE TITLE
refreshingIcon is never used in ClassicHeader

### ISSUE THREAD

**Issue by devx-ubiquity** [peng8350/flutter_pulltorefresh#129]
Hi,
i'm using the last version 1.4.9 .
i specify the 'refreshingIcon' parameter in the ClassicHeader constructor. (classic_indicator.dart. line 54)
'refreshingIcon ' is never used in _buildIcon method . (classic_indicator.dart, line 107)

Regards,

**Comment by peng8350** [comment]
#128 the same
