### ISSUE TITLE
从当前页面跳出，再跳回，调用页面自动下拉刷新，有bug

### ISSUE THREAD

**Issue by yaozongchao** [peng8350/flutter_pulltorefresh#13]
从当前页面A Push出去到页面B，再从页面B Pop回到页面A，同时调用页面A的下拉刷新，`_refreshController.requestRefresh(true)`，这时会有下拉刷新的动作，但是看不到`headerIndicator`，而且刷新完毕，`ListView`位置会往上串，代码的example也能够付现，请作者详查。同时对你的库表达谢意。

**Comment by peng8350** [comment]
好的,只不过我现在忙不过来,在考研复习状态,等12月尾结束后才有时间

**Comment by peng8350** [comment]
你说的可能是因为我之前没在requestRefresh方法里进行对scrollController位置的变化,现在已经添加了
