### ISSUE TITLE
loadFailed()上拉加载失败后，后面一直不能继续拉取数据

### ISSUE THREAD

**Issue by a272312970** [peng8350/flutter_pulltorefresh#130]
loadFailed()上拉加载失败后，不能继续拉取数据，这种体验很不好，假如有的情况是弱网环境就那一会儿网不好，上拉加载失败。然后马上网又好了，后面的数据就拉取不到了

**Comment by peng8350** [comment]
可以的，默认情况下是 提供点击重新加载数据，如果你想失败也可以通过上拉加载，你可以打开enableLoadingwhenFailded这个布尔值

**Comment by a272312970** [comment]
1.4.9中没找到这个属性呀

**Comment by peng8350** [comment]
在RefreshConfiguartion里的,文档有写
