### ISSUE TITLE
SingleScrollView或者ListView嵌套SmartRefresher问题

### ISSUE THREAD

**Issue by dengzhiguiios** [peng8350/flutter_pulltorefresh#131]
问题描述: 
      原本的方案是最外层就是SmartRefresher,child是ListView,
发现数据源clear,然后addAll之后会自动滚动到顶部 , 
然后现在是ListView1嵌套SmartRefresher,再嵌套ListView2,
此时发现ListView2设置禁止滑动失败, 
看了源码发现SmartRefresher是默认允许child组件可滑动的,
这个时候会导致外层的ListView1可滑动,ListView2也可滑动(禁止滑动失效).

建议:
     建议刷新滚动顶部处理交给使用者自己控制 , 
或者SmartRefresher的滚动模式根据childView来设定

**Comment by peng8350** [comment]
没看懂,首先是不允许在SmartRefresher中child使用NeverScrollPhysics和shrinkWrap=true,这样做会炸掉内存当数据量大的时候

**Comment by dengzhiguiios** [comment]
问题已解决,是我的问题,那个刷新滚动到顶部是因为我clear数据的时候setState了一次导致滚动到顶部的,
作者框架使用还是比较方便,感谢作者
