### ISSUE TITLE
包裹在折叠控件中，刷新后会自动折叠

### ISSUE THREAD

**Issue by HeVTion** [peng8350/flutter_pulltorefresh#133]
Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: yello,
      body: SafeArea(
          child: NestedScrollView(  //scrollview
        controller: _scrollController,
        headerSliverBuilder: (context, bool) {  //头部折叠
          return [
            SliverAppBar(
              expandedHeight: ScreenUtil.getInstance().setHeight(100),
              pinned: false,
              elevation: 0,
              primary: false,
              brightness: Brightness.light,
              flexibleSpace: mySearch(),
//                bottom: myTabBar(),
            ),
            SliverPersistentHeader(
              delegate: SliverTabBarDelegate(myTabBar(), color: Colors.white),
              pinned: true,
              floating: false,
            ),
          ];
        },

刷新后，自动滑到顶部，折叠SliverAppBar

**Comment by peng8350** [comment]
代码详细点，smartrefresher还有child,还有nested里的_scrollController做了什么操作

**Comment by HeVTion** [comment]
NestedScrollView 放了 headerSliverBuilder 

SafeArea(
          child: NestedScrollView(
        controller: _scrollController,
        headerSliverBuilder: (context, bool) {
          return [
            SliverAppBar(
              expandedHeight: ScreenUtil.getInstance().setHeight(100),
              pinned: false,
              elevation: 0,
              primary: false,
              brightness: Brightness.light,
              flexibleSpace: mySearch(),
//                bottom: myTabBar(),    ///tabbar 会悬浮于顶部
            ),
            SliverPersistentHeader(
              delegate: SliverTabBarDelegate(myTabBar(), color: Colors.white),
              pinned: true,
              floating: false,
            ),
          ];
        },
        body: Container(
          color: Colors.white,
          padding: EdgeInsets.all(0),
          child: TabBarView(controller: _tabController, children: <Widget>[
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
            myPage(),
          ]),
        ),
      ))  


///smartrefresher 中放了ListView.builder ， 
  myPage() {
    return SmartRefresher(
      child: ListView.builder(
        padding: EdgeInsets.all(0),
        itemBuilder: (BuildContext context, int i) {
          return Container(
              color: Colors.white,
              padding: EdgeInsets.only(left: 15, right: 15, top: 15),
              child: FractionallySizedBox(
                child: i % 2 == 1 ? listA(mData[i]) : listB(mData[i]),
              ));
        },
        itemCount: mData.length,
      ),
      controller: _refreshController,
    );
  }

///_scrollController 什么也没做。

因为，也就是说nested上有个head可以被折叠，滑动到顶部后显示， 使用smart之后没有滑动到顶部，直接折叠了head

**Comment by peng8350** [comment]
![Untitled](https://user-images.githubusercontent.com/19425362/61462275-ed270980-a9a4-11e9-9e06-bddb8412d059.gif)
我没看出来哪里有问题啊,你可以对比一下这里的[例子](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/useStage/Nested.dart),看看哪里有问题

**Comment by JamesGZM** [comment]
> ![Untitled](https://user-images.githubusercontent.com/19425362/61462275-ed270980-a9a4-11e9-9e06-bddb8412d059.gif)
> 我没看出来哪里有问题啊,你可以对比一下这里的[例子](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/useStage/Nested.dart),看看哪里有问题

加了 scrollController 就会有问题
