### ISSUE TITLE
首页进去后不会渲染, 是空白页.

### ISSUE THREAD

**Issue by j787701730** [peng8350/flutter_pulltorefresh#138]
使用版本是1.5.1, 开发时没问题, 打包真机app一进去, 会是空白页, 点击到其他导航, 再点击回来就正常渲染了. 
`import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_swiper/flutter_swiper.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'news_list.dart';

class News extends StatefulWidget {
  @override
  _NewsState createState() => _NewsState();
}

class _NewsState extends State<News> with TickerProviderStateMixin {
  RefreshController _refreshController;

  AnimationController animationLoadingController;
  Animation animationLoading;

  List banner = [
    {'img': 'banner1', 'title': 'App 1.6.2版本上线：模拟器迭代与太古装备展示'},
    {'img': 'banner2', 'title': '晒成绩，夺头衔！十七赛季全民大秘境挑战赛启动'},
  ];
  int page = 0;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _refreshController = RefreshController();
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    _refreshController.dispose();
    if (animationLoadingController != null) {
      animationLoadingController.dispose();
    }
  }

  _loading() {
    animationLoadingController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: 2000),
    );
    animationLoading = Tween(begin: 0.0, end: 1.0).animate(animationLoadingController);
    animationLoadingController.addListener(() {
//      print((animationLoadingController.value * (7 - 1 + 1) + 1).toInt());
      setState(() {});
    });

    animationLoadingController.addStatusListener((AnimationStatus status) {
//      print('new ${animationLoadingController.status}');
      if (status == AnimationStatus.completed) {
        animationLoadingController.reset();
        animationLoadingController.forward();
        //当动画在开始处停止再次从头开始执行动画
      } else if (status == AnimationStatus.dismissed) {
        animationLoadingController.forward();
      }
    });
    animationLoadingController.forward();
  }

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;
    ScreenUtil.instance = ScreenUtil(width: 640, height: 1136)..init(context);
    precacheImage(AssetImage("images/head_loading1.png"), context);
    precacheImage(AssetImage("images/head_loading2.png"), context);
    precacheImage(AssetImage("images/head_loading3.png"), context);
    precacheImage(AssetImage("images/head_loading4.png"), context);
    precacheImage(AssetImage("images/head_loading5.png"), context);
    precacheImage(AssetImage("images/head_loading6.png"), context);
    precacheImage(AssetImage("images/head_loading7.png"), context);
    precacheImage(AssetImage("images/head_loading8.png"), context);
    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        titleSpacing: 0,
        title: Container(
          height: 56,
          decoration: BoxDecoration(
              image: DecorationImage(
            image: AssetImage('images/img_search.png'),
            fit: BoxFit.contain,
          )),
          child: Row(
            children: <Widget>[
              Container(
                  padding: EdgeInsets.only(left: 20),
                  child: Image.asset(
                    'images/icon_search.png',
                    width: 16,
                  )),
              Container(
                padding: EdgeInsets.only(left: 4),
                child: Text(
                  '搜索关键词',
                  style: TextStyle(color: Color(0xffB5A88E), fontSize: 14),
                ),
              )
            ],
          ),
        ),
      ),
      body: Container(
        color: Color(0xffE8DAC5),
        child: SmartRefresher(
          controller: _refreshController,
//          onOffsetChange: _onOffsetChange,
          onRefresh: () async {
            _loading();
            await Future.delayed(Duration(milliseconds: 2000));
            animationLoadingController.reset();
            animationLoadingController.stop();
            _refreshController.refreshCompleted();
          },
          enablePullUp: true,
          header: CustomHeader(
            refreshStyle: RefreshStyle.Behind,
            builder: (c, m) {
              return Container(
                child: Center(
                  child: Image.asset(
                    'images/head_loading${animationLoadingController == null ? 1 : (animationLoadingController.value * (8 - 1.01 + 1) + 1).toInt()}.png',
                    width: ScreenUtil.getInstance().setWidth(78),
                    height: ScreenUtil.getInstance().setWidth(84),
                  ),
                ),
              );
            },
          ),
          footer: CustomFooter(
            loadStyle: LoadStyle.ShowWhenLoading,
            builder: (BuildContext context, LoadStatus mode) {
              Widget body;
              if (mode == LoadStatus.idle) {
                body = Text("pull up load");
              } else if (mode == LoadStatus.loading) {
//                body =  CupertinoActivityIndicator();
                body = Text('loading');
              } else if (mode == LoadStatus.failed) {
                body = Text("Load Failed!Click retry!");
              } else {
                body = Text("No more Data");
              }
              return Container(
                height: 55.0,
                child: Center(child: body),
              );
            },
          ),
          onLoading: () async {
            // monitor network fetch
            await Future.delayed(Duration(milliseconds: 2000));
            // if failed,use loadFailed(),if no data return,use LoadNodata()
//            items.add((items.length+1).toString());
            if (mounted)
              setState(() {
                page = page + 1;
              });
            _refreshController.loadComplete();
          },
          child: ListView(
            children: <Widget>[
              Container(
                height: width / 640 * 260,
                child: Swiper(
                  autoplay: true,
                  itemBuilder: (BuildContext context, int index) {
                    return Stack(
                      fit: StackFit.expand,
                      children: <Widget>[
                        new Image.asset(
                          "images/${banner[index]['img']}.jpg",
                          fit: BoxFit.fill,
                        ),
                        Positioned(
                            bottom: 24,
                            left: 10,
                            width: width - 20,
                            child: Text(
                              banner[index]['title'],
                              style: TextStyle(
                                  color: Color(0xffF5DA9C),
                                  fontSize: ScreenUtil.getInstance().setSp(30),
                                  fontFamily: 'SourceHanSansCN'),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ))
                      ],
                    );
                  },
                  itemCount: banner.length,
                  pagination: new SwiperPagination(
                      builder: RectSwiperPaginationBuilder(
                          size: const Size(22.0, 10.0),
                          activeSize: const Size(22.0, 10.0),
                          activeColor: Color(0xffF5DA9C),
                          color: Color(0x91908C87))),
//                  control: new SwiperControl(),
                ),
              ),
              NewsList(page)
            ],
          ),
        ),
      ),
    );
  }
}
`

**Comment by peng8350** [comment]
是升级了1.5.1才有这个问题吗?感觉像是build方法里有耗时的操作

**Comment by j787701730** [comment]
> 是升级了1.5.1才有这个问题吗？感觉像是建造方法里有耗时的操作

之前是用1.5.0版本的, 打包后不行, 才升级到1.5.1, 试了下还是不行.

**Comment by j787701730** [comment]
改成最简单的, 返回一个Text还是渲染不出来. 我导航栏是用BottomNavigationBar写的. 
  `return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        titleSpacing: 0,
        title: Container(
          height: 56,
          decoration: BoxDecoration(
              image: DecorationImage(
            image: AssetImage('images/img_search.png'),
            fit: BoxFit.contain,
          )),
          child: Row(
            children: <Widget>[
              Container(
                  padding: EdgeInsets.only(left: 20),
                  child: Image.asset(
                    'images/icon_search.png',
                    width: 16,
                  )),
              Container(
                padding: EdgeInsets.only(left: 4),
                child: Text(
                  '搜索关键词',
                  style: TextStyle(color: Color(0xffB5A88E), fontSize: 14),
                ),
              )
            ],
          ),
        ),
      ),
      body: Container(
        color: Color(0xffE8DAC5),
        child: SmartRefresher(
          controller: _refreshController,
//          onOffsetChange: _onOffsetChange,
          onRefresh: () async {
            await Future.delayed(Duration(milliseconds: 2000));
            _refreshController.refreshCompleted();
          },
          enablePullUp: true,
          header: CustomHeader(
            refreshStyle: RefreshStyle.Behind,
            builder: (c, m) {
              return Container(
                child: Center(
                  child: Text('loading'),
                ),
              );
            },
          ),
          footer: CustomFooter(
            loadStyle: LoadStyle.ShowWhenLoading,
            builder: (BuildContext context, LoadStatus mode) {
              Widget body;
              if (mode == LoadStatus.idle) {
                body = Text("pull up load");
              } else if (mode == LoadStatus.loading) {
//                body =  CupertinoActivityIndicator();
                body = Text('loading');
              } else if (mode == LoadStatus.failed) {
                body = Text("Load Failed!Click retry!");
              } else {
                body = Text("No more Data");
              }
              return Container(
                height: 55.0,
                child: Center(child: body),
              );
            },
          ),
          onLoading: () async {
            // monitor network fetch
            await Future.delayed(Duration(milliseconds: 2000));
            // if failed,use loadFailed(),if no data return,use LoadNodata()
//            items.add((items.length+1).toString());
            if (mounted) setState(() {});
            _refreshController.loadComplete();
          },
          child: ListView(
            children: <Widget>[
              Container(
                height: width / 640 * 260,
                child: Text('BBS'),
              ),
            ],
          ),
        ),
      ),
    );`

**Comment by j787701730** [comment]
问题算解决了, 加个状态, 能正常渲染.  `bool flag = true;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _init();
  }

  _init() async {
    await Future.delayed(Duration(seconds: 2));
    setState(() {
      flag = false;
    });
  }`   在build里面在判断下   `flag
            ? Center(
                child: Image.asset('images/head_loading1.png'),
              )
            : SmartRefresher()`

**Comment by khaitq7** [comment]
I am sorry .
But I will like to add for the perfect question @peng8350 . 
Because i hope my comment i will support the others research easy for solve .

**TAG : ide loading fresh when pull up refresh completed**

`return Scaffold(
            body: SmartRefresher(
              enablePullDown: true,
              enablePullUp: true,
              header: WaterDropHeader(),
              footer: CustomFooter(
                  loadStyle: LoadStyle.ShowWhenLoading,
                  builder: (BuildContext context,LoadStatus mode){

                  Widget body ;
                  if(mode==LoadStatus.idle){
                    body =  Text("pull up load");

                  }
                  else if(mode==LoadStatus.loading){
                    body =  CupertinoActivityIndicator();
                  }
                  else if(mode == LoadStatus.failed){
                    body = Text("Load Failed!Click retry!");
                  }
                  else if(mode == LoadStatus.canLoading){
                    body = Text("release to load more");
                  }
                  else{
                    body = Text("No more Data");
                  }
                  return Container(
                    height: 55.0,
                    child: Center(child:body),
                  );
                },
              ),
              controller: _refreshController,
              onRefresh: _onRefresh,
              onLoading: _onLoading,
              child: ListView(
                children: <Widget>[
                  SizedBox(height : 100),
                  SizedBox(height : 100),
                ],
              ),
            ),
          );`

Thank for author lib
