### ISSUE TITLE
Refresh indicator not reaching headerTriggerDistance

### ISSUE THREAD

**Issue by ssants** [peng8350/flutter_pulltorefresh#139]
The headerTriggerDistance is 80 by default, but for some reason my application could only reach a max offset of 78, so the onRefresh callback was never called. 

To work around this I had to manually set headerTriggerDistance to something smaller in a RefreshConfiguration

**Comment by peng8350** [comment]
you can set maxOverScrollExtent > headerTriggerDistance

**Comment by ssants** [comment]
That also fixes the issue, although I found the minimum value for maxOverScrollExtent to hit headerTriggerDistance was 32. Thanks for the help
