### ISSUE TITLE
Unable to refresh

### ISSUE THREAD

**Issue by KyllianDM** [peng8350/flutter_pulltorefresh#140]
Hello,
Before the last update, my ListViews were loading on initialization with the SmartRefresher and were refreshing with the normal gesture, but he doens't work anymore.

**Comment by peng8350** [comment]
I think you should attach a sample code,or gif ,else I don't why can not trigger refresh

**Comment by KyllianDM** [comment]
Hello, this is a gif of when I arrived on the first page of my app.

![image](https://user-images.githubusercontent.com/9364594/61948597-85764d00-afa8-11e9-97b7-f0e45185afac.png)

**Comment by peng8350** [comment]
try this 
```dart
RefreshConfiguration(
      headerTriggerDistance: 60.0,
      maxOverScrollExtent: 120.0, 
     child:SmartRefresher(.....)
)
```

**Comment by KyllianDM** [comment]
Hi, yes, it's work now. But why it wasn't working before ?

**Comment by peng8350** [comment]
I think the reason is maxOverScrollExtent default value change to 30 in 1.5.1,maxOverScrollExtent limits the maximum distance beyond the edge,so when value too small,This leads to the inability to reach the header Trigger Distance.just like this issue, #139 .

**Comment by KyllianDM** [comment]
Okay, I see. Thanks for your help!
