### ISSUE TITLE
The getter 'pixels' was called on null

### ISSUE THREAD

**Issue by a272312970** [peng8350/flutter_pulltorefresh#142]
检测到package:pull_to_refresh/src/internals/indicator_wrap.dart中pixels的调用可能为null，具体原因没细查，请作者注意判断修复一下吧

**Comment by peng8350** [comment]
目前没看见过这个警告抛出过一次，如果有，你可以指出在什么情况下会出现

**Comment by peng8350** [comment]
确实有这个问题,不过很难触发,TabBarView情况产生的,我的直觉是TabBarView的Bug,它切换时有一定概率产生两个同样的页面,感觉就是这个问题

**Comment by ycyranqingjjs** [comment]
> 确实有这个问题,不过很难触发,TabBarView情况产生的,我的直觉是TabBarView的Bug,它切换时有一定概率产生两个同样的页面,感觉就是这个问题

使用TabBarView会触发这个The getter 'scrollExtent' was called on null.的错误bug,就是切换到其他页面之后再返回到这个包含TabBarView 的页面的时候就必现

**Comment by peng8350** [comment]
额,我知道为什么position为空了,不关tabbarview的事,这个问题之所以很难重现，那是因为需要下拉刷新,等待完成之后,准备回弹那几十毫秒的时间才能产生。而我在等待下一帧那一瞬间忽略判断是否被dispose掉
