### ISSUE TITLE
SmartRefresher的子空间放Column,子一级是多个widget和listVIew,导致一直上拉不成功

### ISSUE THREAD

**Issue by zhujinsheng** [peng8350/flutter_pulltorefresh#143]
代码如下：
![image](https://user-images.githubusercontent.com/16300475/62181149-ea54ed00-b384-11e9-876d-9942ab9b3a1a.png)
![image](https://user-images.githubusercontent.com/16300475/62181222-25572080-b385-11e9-9a4c-5770c5218aca.png)

**Comment by peng8350** [comment]
#124 详见最后的回复,  README存在的问题第二点

**Comment by peng8350** [comment]
假如你想多个widget+listview,你可以使用CustomScrollView将多个widget用SliverToBoxAdapter装起来,然后用SliverList代替ListView

**Comment by peng8350** [comment]
child用法问题,仔细阅读[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/README_CN.md/#child)
