### ISSUE TITLE
不知道有没有人遇到过_NestedScrollMetrics这个问题

### ISSUE THREAD

**Issue by YQjiuhao** [peng8350/flutter_pulltorefresh#146]
flutter: The following _CastError was thrown while handling a gesture:
flutter: type '_NestedScrollMetrics' is not a subtype of type 'ScrollPosition' in type cast
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RefreshPhysics.createBallisticSimulation

**Comment by peng8350** [comment]
配合NestedScrollView确实有这个错误抛出,但没造成致命奔溃,下个版本修正

**Comment by YQjiuhao** [comment]
> 配合NestedScrollView确实有这个错误抛出,但没造成致命奔溃,下个版本修正

谢谢

**Comment by peng8350** [comment]
已修正
