### ISSUE TITLE
Header loading like app store

### ISSUE THREAD

**Issue by kekedaine** [peng8350/flutter_pulltorefresh#147]
Plz. How to custom header like apple app store

**Comment by peng8350** [comment]
see [here](https://github.com/peng8350/flutter_pulltorefresh/blob/master/custom_indicator_en.md)

**Comment by kekedaine** [comment]
So i need indicator progress follow scrolldown like apple

**Comment by peng8350** [comment]
I think you need RefreshStyle.Behind+ onOffsetChange+Clipper,the more details please read document
