### ISSUE TITLE
Pageview 嵌套 SmartRefresher：（ListView +ClassicHeader ）下拉刷新触发左右切换

### ISSUE THREAD

**Issue by coku00** [peng8350/flutter_pulltorefresh#149]
Pageview 嵌套 SmartRefresher：（ListView +ClassicHeader ）下拉刷新触发左右切换

**Comment by coku00** [comment]
Pageview 嵌套 SmartRefresher：（ListView +ClassicHeader ）下拉刷新触发左右切换

**Comment by coku00** [comment]
> Pageview 嵌套 SmartRefresher：（ListView +ClassicHeader ）下拉刷新触发左右切换

**Comment by peng8350** [comment]
你有两个选择:
1.在TabBarView设定NeverScrollPhysics不允许它左右滚动
2.在RefreshConfiguration内设定属性enableScrollWhenRefreshCompleted:true，刷新完成回弹不限制滚动

目前来说,想要左右滚动和限制滚动当刷新完毕回弹回去这两个功能同时兼备是不大可能做到的。除非flutter改动scrollable内部实现
