### ISSUE TITLE
Pull to refresh sometimes covers the whole device screen when scrolled with force on a large list  

### ISSUE THREAD

**Issue by bipin000** [peng8350/flutter_pulltorefresh#150]
sometimes my screen goes blank when i swipe down with speed and after few moment my content toggle back in view on a large list of items. Can I define a  size of blank when i swipe down with force ?

**Comment by peng8350** [comment]
```dart

RefreshConfiguration(
      maxOverScrollExtent:100,
      maxUnderScrollExtent:100,
      child: SmartRefresher(...)
)

```

try this,if this can not solve your problem,you can post the sample code

**Comment by bipin000** [comment]
Thanks that's worked. loved this library
