### ISSUE TITLE
The getter 'scrollExtent' was called on null.

### ISSUE THREAD

**Issue by ycyranqingjjs** [peng8350/flutter_pulltorefresh#151]
widget层级关系:
NestedScrollView ---> .Container .--> TabBarView --> SmartRefresher

出现切换到当前的tab时滑不动(只能上下滑动一点距离,超过屏幕的条目没办法滑出来)

错误日志:

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while handling a gesture:
flutter: The getter 'scrollExtent' was called on null.
flutter: Receiver: null
flutter: Tried calling: scrollExtent
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
flutter: #1      RefreshPhysics.applyBoundaryConditions (package:pull_to_refresh/src/internals/refresh_physics.dart:216:43)
flutter: #2      ScrollPosition.applyBoundaryConditions (package:flutter/src/widgets/scroll_position.dart:373:35)
flutter: #3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:202:33)
flutter: #4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:83:18)
flutter: #5      ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:126:5)
flutter: #6      ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:372:14)
flutter: #7      ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:498:12)
flutter: #8      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:383:46)
flutter: #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #10     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:383:7)
flutter: #11     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:253:9)
flutter: #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
flutter: #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #22     _invoke1 (dart:ui/hooks.dart:250:10)
flutter: #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Handler: "onUpdate"
flutter: Recognizer:
flutter:   VerticalDragGestureRecognizer#3ba64
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by ycyranqingjjs** [comment]
> widget层级关系:
> NestedScrollView ---> .Container .--> TabBarView --> SmartRefresher
> 
> 出现切换到当前的tab时滑不动(只能上下滑动一点距离,超过屏幕的条目没办法滑出来)
> 
> 错误日志:
> 
> flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
> flutter: The following NoSuchMethodError was thrown while handling a gesture:
> flutter: The getter 'scrollExtent' was called on null.
> flutter: Receiver: null
> flutter: Tried calling: scrollExtent
> flutter:
> flutter: When the exception was thrown, this was the stack:
> flutter: #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
> flutter: #1 RefreshPhysics.applyBoundaryConditions (package:pull_to_refresh/src/internals/refresh_physics.dart:216:43)
> flutter: #2 ScrollPosition.applyBoundaryConditions (package:flutter/src/widgets/scroll_position.dart:373:35)
> flutter: #3 ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:202:33)
> flutter: #4 ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:83:18)
> flutter: #5 ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:126:5)
> flutter: #6 ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:372:14)
> flutter: #7 ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:498:12)
> flutter: #8 DragGestureRecognizer._checkUpdate. (package:flutter/src/gestures/monodrag.dart:383:46)
> flutter: #9 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> flutter: #10 DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:383:7)
> flutter: #11 DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:253:9)
> flutter: #12 PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
> flutter: #13 PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
> flutter: #14 _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
> flutter: #15 _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> flutter: #16 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> flutter: #17 _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> flutter: #18 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> flutter: #22 _invoke1 (dart:ui/hooks.dart:250:10)
> flutter: #23 _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
> flutter: (elided 3 frames from package dart:async)
> flutter:
> flutter: Handler: "onUpdate"
> flutter: Recognizer:
> flutter: VerticalDragGestureRecognizer#3ba64
> flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

这个bug是升级到 1.5.3 之后出现的,之前版本不存在

**Comment by peng8350** [comment]
问题重现不了,起码附个样例代码把

**Comment by peng8350** [comment]
Got no reply long time. Close this issue
