### ISSUE TITLE
如何监听ListView滚动状态

### ISSUE THREAD

**Issue by cornflower10** [peng8350/flutter_pulltorefresh#152]
这么写监听，监听不了，下拉刷新也用不了
SmartRefresher(
                  enablePullDown: true,
                  enablePullUp: false,
                  header: WaterDropHeader(),
                  child: NotificationListener(
                      child: ListView.builder(
                    itemBuilder: _buildItem,
                    itemCount: _list == null ? 0 : _list.length,
                  ),onNotification: _onNotification,),
                  controller: _refreshController,
                  onRefresh: _onRefresh,
                )

  bool _onNotification(Notification notification) {
    switch (notification.runtimeType) {
      case ScrollStartNotification:
        update(false);
        break;
      case ScrollUpdateNotification:
        update(false);
        break;
      case ScrollEndNotification:
        update(true);
        break;
      case OverscrollNotification:
        update(true);
        break;
    }
    if (notification is ScrollEndNotification) {
    } else if (notification is ScrollUpdateNotification) {
      show = false;
      widget.callback(show);
    }
  }

**Comment by peng8350** [comment]
你要把NotificationListener放到SmartRefresher外部,这个问题其实和 #143 这个人的一样的,其实我在注意问题里文档也有说明,只不过有点隐晦,看来我干脆放到首页说明好点

**Comment by peng8350** [comment]
child用法问题,仔细阅读[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/README_CN.md/#child)
