### ISSUE TITLE
refresh indicator 一直挂在固定位置，也不刷新，需要手动的把listview 往上推下才开始刷新

### ISSUE THREAD

**Issue by SwainZhang** [peng8350/flutter_pulltorefresh#158]
![image](https://user-images.githubusercontent.com/22322315/63700194-ebc6e780-c854-11e9-9926-c96af5bd4484.png)
用的是OnlyListView demo

**Comment by peng8350** [comment]
一般都是松开手才开始刷新的,我估计你是想要ios手机qq版的下拉刷新,到达触发的距离就立马进入刷新状态,你可以设置全局属性skipCanRefresh:true

**Comment by SwainZhang** [comment]
不是，我是拉完了后放开，然后发现竟然不动了，然后我把listview向上推下才开始刷新

**Comment by peng8350** [comment]
这个问题我这里没法重现,我估计和设备有关系,你可以换个设备试试,请提供更多的信息,比如Android的版本,设备型号

**Comment by zhanghuibiao** [comment]
android遇到同样问题，操作如下，手势迅速往下滑动，突然松开，就容易出现该问题

**Comment by peng8350** [comment]
IPhone X用ClampingScrollPhysics发现这个问题了,感谢提醒

**Comment by peng8350** [comment]
@zhanghuibiao @SwainZhang 1.5.6应该解决了,麻烦两位测试一下,因为我手头没有设备能碰到这个问题

**Comment by peng8350** [comment]
此问题没人反馈,应该已经修复了,有的话再提
