### ISSUE TITLE
当数据不满一个屏幕的时候，如何继续上拉加载更多

### ISSUE THREAD

**Issue by Sky24n** [peng8350/flutter_pulltorefresh#16]

**Comment by Sky24n** [comment]
数据不满一个屏幕，没有触发上拉加载更多

**Comment by peng8350** [comment]
我测试了没问题,你用demo跑一下试试

**Comment by Sky24n** [comment]
设置enableOverScroll: false，就 触发不了了；

其他问题
① enableOverScroll: false；onOffsetChange 不回调
② 下拉也会触发加载更多，配置如下：
 enablePullDown: false,
 enablePullUp: true,
