### ISSUE TITLE
让pull up支持pull down一样的效果

### ISSUE THREAD

**Issue by JackyChan** [peng8350/flutter_pulltorefresh#160]
你好，可以让pull up也支持pull down一样的效果吗？需要用户往一拉一拉才会加载更多内容，目前的效果是只要拉到底部就会加载，希望可以设置pull up的加载效果跟horizontal+reverse中的reverse效果一样。谢谢

**Comment by peng8350** [comment]
这个需求,得要打破内部很多变化。而且flutter设计的限制,FrontStyle在底部浮动几乎不能实现。

**Comment by peng8350** [comment]
1.5.5已实现,参照[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/customindicator/footer_underscroll.dart)

**Comment by JackyChan** [comment]
非常感谢！
