### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by KyllianDM** [peng8350/flutter_pulltorefresh#161]
Hello,
Could you please translate the ClassicHeader text ? (Like "Refreshing…", etc) in french ?

Thanks !

**Comment by peng8350** [comment]
I have add international in 1.5.6,but now only support English and Chinese.If you need french,you can give me a pr.because I don't know how to express refresh text correct in French.

**Comment by KyllianDM** [comment]
Do you want me to send you the translated strings ?

________________________________
De : Jpeng <notifications@github.com>
Envoyé : Saturday, September 7, 2019 11:12:25 AM
À : peng8350/flutter_pulltorefresh <flutter_pulltorefresh@noreply.github.com>
Cc : KyllianDM <kylliandm@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [peng8350/flutter_pulltorefresh] Internationalization (#161)


I have add international in 1.5.6,but now only support English and Chinese.If you need french,you can give me a pr.because I don't know how to express refresh text correct in French.

**Comment by peng8350** [comment]
Yes,here are 11 strings that need to be set

```dart

/// interface implements different language
abstract class RefreshString {
  /// pull down refresh idle text
  String idleRefreshText;

  ///  tips user to release gesture to refresh at time
  String canRefreshText;

  /// refreshing state text
  String refreshingText;

  /// refresh completed text
  String refreshCompleteText;

  /// refresh failed text
  String refreshFailedText;

  /// enable open twoLevel and tips user to release gesture to enter two level
  String canTwoLevelText;

  /// pull down load idle text
  String idleLoadingText;

  /// tips user to release gesture to load more at time
  String canLoadingText;

  /// loading state text
  String loadingText;

  /// load failed text
  String loadFailedText;

  /// no more data text
  String noMoreText;
}

```

**Comment by KyllianDM** [comment]
Hello ! 
Here it is.

`/// French
class FrRefreshString implements RefreshString {
  @override
  String canLoadingText = "Relâchez pour charger davantage";

  @override
  String canRefreshText = "Relâchez pour rafraîchir";

  @override
  String canTwoLevelText = "Relâchez pour entrer secondfloor";

  @override
  String idleLoadingText = "Tirez pour charger davantage";

  @override
  String idleRefreshText = "Tirez pour rafraîchir";

  @override
  String loadFailedText = "Chargement échoué";

  @override
  String loadingText = "Chargement…";

  @override
  String noMoreText = "Aucune autre donnée";

  @override
  String refreshCompleteText = "Rafraîchissement terminé";

  @override
  String refreshFailedText = "Rafraîchissement échoué";

  @override
  String refreshingText = "Rafraîchissement…";
}`

**Comment by peng8350** [comment]
Thanks!this has been added to the library

**Comment by voicecode-bv** [comment]
@peng8350 Thanks for this great package! Can you please add the Dutch translations too?

```
class NlRefreshString implements RefreshString {
  @override
  String canLoadingText = "Laat los om meer te laden";

  @override
  String canRefreshText = "Laat los om te verversen";

  @override
  String canTwoLevelText = "Laat los om tweede niveau te laden";

  @override
  String idleLoadingText = "Sleep omhoog om meer te laden";

  @override
  String idleRefreshText = "Sleep omhoog om te vernieuwen";

  @override
  String loadFailedText = "Laden mislukt";

  @override
  String loadingText = "Bezig met laden...";

  @override
  String noMoreText = "Geen andere gegevens gevonden";

  @override
  String refreshCompleteText = "Vernieuwd";

  @override
  String refreshFailedText = "Vernieuwen is mislukt";

  @override
  String refreshingText = "Vernieuwen...";
}
```

**Comment by tranvannhat** [comment]
@peng8350 can you add Vietnamese language. Here is example:

`class EnRefreshString implements RefreshString {
  @override
  String canLoadingText = "Phát hành để tải thêm";

  @override
  String canRefreshText = "Phát hành để làm mới";

  @override
  String canTwoLevelText = "Phát hành để vào tầng hai";

  @override
  String idleLoadingText = "Vuốt lên để tải thêm";

  @override
  String idleRefreshText = "Vuốt xuống để làm mới";

  @override
  String loadFailedText = "Tải lỗi";

  @override
  String loadingText = "Đang tải…";

  @override
  String noMoreText = "Đã tải hết dữ liệu";

  @override
  String refreshCompleteText = "Xong";

  @override
  String refreshFailedText = "Tải lại lỗi";

  @override
  String refreshingText = "Làm mới…";
}
`
