### ISSUE TITLE
怎么把 scrollable 的 glowing over scroll indicator 效果取消呢

### ISSUE THREAD

**Issue by SwainZhang** [peng8350/flutter_pulltorefresh#162]

**Comment by SwainZhang** [comment]
因为我加ScrollConfiguration后，QQ 聊天刷新的indicator 就跑到 footer位置去了

**Comment by SwainZhang** [comment]
不论我使用NotificationListener OverscrollIndicatorNotification.disallowGlow 还是 ScrollBehavior最终的结果都是 indicator 跑到footer位置，变成上拉刷新，即使这样也只能刷新一次，第二次后不论怎么拉都不行拉

**Comment by peng8350** [comment]
1.GlowingOverscrollIndicator它里面不是有一个showLeading,showTrailing属性,你把它设置为false就可以取消水波纹效果了。
2.你reverse为true后,header在底部,变成上拉刷新,这不是bug,是正常的
3.不管怎么拉都不行?我估计是你把ScrollConfiguration放在了SmartRefresher和ListView之间,认真阅读[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/README_CN.md/#child)

**Comment by peng8350** [comment]
参照这里,定义[behaviour](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/other/refresh_glowindicator.dart),然后[主入口](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/main.dart)配置全局水波纹表现行为
