### ISSUE TITLE
搭配webview无法下拉刷新,有没有什么办法或例子

### ISSUE THREAD

**Issue by thunshell** [peng8350/flutter_pulltorefresh#165]
webview:  flutter_inappbrowser

**Comment by peng8350** [comment]
这个你得问flutter那边的维护者，目前WebView貌似不支持放到Scrollable内联合滚动

**Comment by thunshell** [comment]
> 这个你得问flutter那边的维护者，目前WebView貌似不支持放到Scrollable内联合滚动

谢谢
