### ISSUE TITLE
设置可上拉加载更多时，数据不满一页，上拉加载的组件在底部，上拉会复现此bug

### ISSUE THREAD

**Issue by jp1017** [peng8350/flutter_pulltorefresh#166]
![image](https://user-images.githubusercontent.com/7868514/65027516-11837000-d96d-11e9-9d12-1810e921f865.png)

如上是上拉的截图，松手后会看不到“没有更多啦”

**Comment by jp1017** [comment]
需求是如何把‘没有更多啦’放到已有列表数据下面

**Comment by peng8350** [comment]
库内有这个选项可以设置是否跟随内容不难一屏，在属性文档RefreshConfiguration里。我记得某个版本已经默认为跟随，你也可以更新版本

**Comment by jp1017** [comment]
hideFooterWhenNotFull，默认false，但是不好用，就是我这种效果，也不自动加载第二页，还需别的配置吗？ @peng8350

**Comment by peng8350** [comment]
这么做
```dart

shouldFooterFollowWhenNotFull: (mode){
    //对于没有更多数据状态,跟随内容列表,对于其他底部状态,不跟随位于底部
    if(mode==LoadStatus.noMore){
      return true;
    }
    return false;
}

```

**Comment by jp1017** [comment]
@peng8350 这么配置，松手后“没有更多啦”跟随内容列表了，但是不能自动加载第二页，并且上拉的时候“没有更多啦”仍然在最下面显示而不是跟随列表，

**Comment by peng8350** [comment]
![image](https://user-images.githubusercontent.com/19425362/65159615-f5fc9000-da66-11e9-8c5d-2bc046c8f362.png)
你的问题我复现不了,没有更多数据的状态设定就是不能加载更多的数据的,你如果想没有更多数据的情况还能加载,你只能自定义footer给idle额外增加一种布局,目前也没必要弄一个开关控制在没有更多数据下能加载数据。

**Comment by jp1017** [comment]
@peng8350 我的布局是这样的

```
RefreshConfiguration(
      shouldFooterFollowWhenNotFull: (LoadStatus status) {
        if (status == LoadStatus.noMore) {
          return true;
        }
        return false;
      },
      headerTriggerDistance: 60,
      headerBuilder: buildHeader,
      footerBuilder: buildFooter,
      child: Container(
        decoration: BoxDecoration(
            color: bgColor ?? Colours.white,
            borderRadius: hasDecoration
                ? BorderRadius.only(
                    topLeft: Radius.circular(15), topRight: Radius.circular(15))
                : null),
        child: SmartRefresher(
            enablePullUp: loadMore ?? true,
            enablePullDown: refresh ?? true,
            controller: _controller,
            onRefresh: pullToRefresh,
            onLoading: loadingMore,
            child: getBody()),
      ),
    );
```

**Comment by peng8350** [comment]
我大概知道你什么问题，getBody里你返回的不是ListView这类控件吧，不是的话会展到最大的高度和SmartRefresher匹配。所以永远在底部，还有请认真阅读Readme内child的用法。

**Comment by peng8350** [comment]
说实在，当初不该把ScrollView限制为Widget,这样会让很多人会误用。但不这么做，你们想存放空视图或者PageView这种填满高度的child,你们需要每次LayoutBuilder来估计高度

**Comment by jp1017** [comment]
getBody()返回的就是ListView啊，readme看了，不大懂，没提供设置背景色的正确代码呢

**Comment by jp1017** [comment]
@peng8350 demo here: https://github.com/jp1017/flutter_refresh_issue

上拉就会有这个问题了

**Comment by peng8350** [comment]
@jp1017 
![image](https://user-images.githubusercontent.com/19425362/65701001-2cfc2280-e0b3-11e9-8a86-1d05a983e627.png)
没问题吧.....

**Comment by jp1017** [comment]
不是这个，刚打开页面，有两个数据，上拉试试，最底部会出现“Release to load more”，不是应该出现在两个数据的下面吗？

![Screenshot_2019-09-27-10-03-45-467_flutter_refresh_issue](https://user-images.githubusercontent.com/7868514/65736627-3c5c8980-e10e-11e9-8b05-8b65b18cc044.png)

**Comment by peng8350** [comment]
...这个我上面已经说了可以设置的,不是bug。我都打了注释了的,我还以为你应该明白了。

```
shouldFooterFollowWhenNotFull: (mode){
    //对于没有更多数据状态,跟随内容列表,对于其他底部状态,不跟随位于底部

      return true;

}
```

**Comment by jp1017** [comment]
好吧，先这样吧
