### ISSUE TITLE
上拉加载和下拉刷新使用同一种gif指示器的报错问题

### ISSUE THREAD

**Issue by jahnli** [peng8350/flutter_pulltorefresh#167]
期望：上拉加载和下拉刷新使用同一种gif加载器

目前报错：
会提示这样一个报错
![image](https://user-images.githubusercontent.com/20943608/65028281-6c699700-d96e-11e9-8179-21838c9473cd.png)

![image](https://user-images.githubusercontent.com/20943608/65028246-59ef5d80-d96e-11e9-9cb4-dd69825ee2d5.png)
![image](https://user-images.githubusercontent.com/20943608/65028258-62479880-d96e-11e9-9da5-fbdb59cfd3f6.png)

**Comment by peng8350** [comment]
Header和footer采用不同机制原理来实现的，要区分，所以你把header放进footer会报错。footer要可以使用CustomFooter或者继承LoadIndicatorState

**Comment by jahnli** [comment]
那请问custom footer 是否支持gif




在2019年09月18日 00:53，Jpeng 写道：

Header和footer采用不同机制原理来实现的，要区分，所以你把header放进footer会报错。footer要可以使用CustomFooter或者继承LoadIndicatorState

**Comment by peng8350** [comment]
可以,实现的方法和CustomHeader基本一样

**Comment by jahnli** [comment]
请问大佬有没有类似的例子参考下。
![image](https://user-images.githubusercontent.com/20943608/65114565-8f04ba00-da19-11e9-91b5-89eec1d86ceb.png)  目前看到的这个custom 无法控制gif

**Comment by peng8350** [comment]
已增加gifFooter的例子

**Comment by jahnli** [comment]
我自己尝试用custome footer 已经完成功能，明天再参考一下大佬的例子




在2019年09月18日 22:49，Jpeng 写道：

已增加gifFooter的例子
