### ISSUE TITLE
Refresh completed text in ios

### ISSUE THREAD

**Issue by meshkani75** [peng8350/flutter_pulltorefresh#168]
After refreshing ends, a text appears on the top of the screen, exactly where the refresh indicator was located (only on ios).
Is there any way to delete this text?
![Annotation 2019-09-18 232450](https://user-images.githubusercontent.com/53332174/65177833-bf297880-da6c-11e9-877b-ee66d43c6958.png)

**Comment by peng8350** [comment]
ClassicHeader has an attribute:completedText, just set to “”

**Comment by quynhntph04960** [comment]
header: WaterDropHeader(
        complete: Text(""),
      ),

**Comment by quynhntph04960** [comment]
header: WaterDropHeader(
        complete: Text(""),
      ),
