### ISSUE TITLE
Custom RefreshStatus text

### ISSUE THREAD

**Issue by lyquocnam** [peng8350/flutter_pulltorefresh#17]
hi author, can i custom RefreshStatus text will be display to difference ?
ex: `No more data` -> `empty data` ?

**Comment by peng8350** [comment]
The indicator is not fixed, which requires you to customize a layout to different states.The construction indicator has been shown in the document.

**Comment by lyquocnam** [comment]
yes, i see. It should be place on document too.
Thanks author !
