### ISSUE TITLE
ClassicFooter设置autoLoad:false无法上拉加载

### ISSUE THREAD

**Issue by lvyandev** [peng8350/flutter_pulltorefresh#170]
![QQ截图20190920154600](https://user-images.githubusercontent.com/18045999/65309117-0a9f6c00-dbbe-11e9-8124-7cb4f50f8e50.png)

![1](https://user-images.githubusercontent.com/18045999/65309263-4f2b0780-dbbe-11e9-91e9-bdbaab01dc8a.gif)

版本1.5.6

**Comment by peng8350** [comment]
autoLoad的意思不是像Android的SmartRefreshLayout的autoLoad一个意思,你大概是想要取消通过惯性加载更多的效果把,enableBallsticLoad:false

**Comment by lvyandev** [comment]
对对，我的用法有问题。
还有个问题，有办法取消SmartRefrsher的水波纹效果吗？ListView已经设置了
```
shrinkWrap: true,
physics: NeverScrollableScrollPhysics(),
```
