### ISSUE TITLE
Version 1.5.6 uses webview component gesture conflicts

### ISSUE THREAD

**Issue by zpcsa** [peng8350/flutter_pulltorefresh#172]
When the webview component is used in the project, after clicking the web page, return to the list, pull-down refresh, the 1.5.6 version will conflict, the pull-down gesture is invalid. Version 1.1.6 works fine

**Comment by peng8350** [comment]
Can you attach the example code how to work fine in 1.1.6?

**Comment by zpcsa** [comment]
I am very sorry about the problem of my project itself.
