### ISSUE TITLE
如何实现下拉加载数据，而不导致数据直接跳转到首部？

### ISSUE THREAD

**Issue by speanut-land** [peng8350/flutter_pulltorefresh#174]
聊天界面下拉加载历史记录，看了readme和issues，但是没有可以解决问题的答案。询问一下，已经设置了reverse与enablePullDown: false, enablePullUp: true,但是每次向下拉的时候，触发onLoading都会导致视图直接跳转到最近的一条数据了而不是刚刚加载数据的位置。不知描述的是否正确？希望作者能够告知如何解决。感谢作者的花费的精力与时间🙏🙏

**Comment by peng8350** [comment]
你可以参加qq聊天列表的案例，我不知道你为什么reverse为false,上拉加载理论上要开始reverse.如果你保持不反转，你每次上拉加载数据，setState调用后，在那个准备刷新下一帧的时间内，scrollcontroller里有一个方法 correctpixels修正新加入布局的高度。如果你不知道新加入的布局有多少，那你肯定要开启reverse

**Comment by speanut-land** [comment]
是有开启reverse:true   刚刚看了一下写的issues ,确实是有歧义的,对作者造成了误解,请问是example里面是有qq聊天列表的案例是吗？如果是的话  会关闭这个issues的。麻烦作者了～～
