### ISSUE TITLE
建议优化点

### ISSUE THREAD

**Issue by CoderXiaoming** [peng8350/flutter_pulltorefresh#178]
> refreshController调用requestRefresh，方法里有默认500的动画时间。但实际测试，手动调用requestRefresh，控件会立马回调onfresh。这就导致刷新头刚刚往下走的时候，就刷新成功了，刷新体验不好

![Snip20190929_4](https://user-images.githubusercontent.com/23111683/65834951-0b997180-e313-11e9-9120-820ad0713aa4.png)
![Snip20190929_5](https://user-images.githubusercontent.com/23111683/65834957-29ff6d00-e313-11e9-8e09-c6b99f15abd6.png)
![Snip20190929_6](https://user-images.githubusercontent.com/23111683/65834959-2ff54e00-e313-11e9-8621-2a3478284df2.png)

> 我临时在onfresh回调里加了个500的延时，刷新头的动画能够走完，这时候的刷新体验很好。
希望这点能优化下这块的优化体验。
 
![Snip20190929_8](https://user-images.githubusercontent.com/23111683/65835032-00931100-e314-11e9-9f5f-f8ff4304222a.png)

**Comment by peng8350** [comment]
问题已经修复,现在改为跑到顶部时才开始刷新
