### ISSUE TITLE
指定iconPos为上下时没起作用

### ISSUE THREAD

**Issue by JackyChan** [peng8350/flutter_pulltorefresh#179]
你好，使用iconPos指定图标位置为IconPosition.top或IconPosition.bottom时不起效果，只有左右有效果。

**Comment by peng8350** [comment]
![image](https://user-images.githubusercontent.com/19425362/66026500-9359c880-e52b-11e9-8fb1-2a9d12d92955.png)
问题不能重现

**Comment by JackyChan** [comment]
> ![image](https://user-images.githubusercontent.com/19425362/66026500-9359c880-e52b-11e9-8fb1-2a9d12d92955.png)
> 问题不能重现

是只能针对刷新吗？footer呢？

**Comment by peng8350** [comment]
@JackyChan 加大indicator的高度或者缩小spacing,因为我内部用的是Wrap控件
