### ISSUE TITLE
第一页10条没有占满屏幕的时候，不会自动加载第二页

### ISSUE THREAD

**Issue by SunflowerGJ** [peng8350/flutter_pulltorefresh#181]
第一页10条没有占满屏幕的时候，不会自动加载第二页，footer还是在屏幕底部，需要上拉才能加载出第二页。

**Comment by peng8350** [comment]
没看懂你的问题,再详细描述一下,或者干脆给个gif图。footer在屏幕底部还是追随列表可以自由设定,上拉才能加载更多,当然你也可以自己触发加载更多。

**Comment by dotcink** [comment]
是想第一页加载出来后，如果不满一屏，就自动触发加载，直到满一屏，或者加载失败/没有更多。

**Comment by SunflowerGJ** [comment]
----- 原始邮件 -----
发件人：dotcink <notifications@github.com>
收件人：peng8350/flutter_pulltorefresh <flutter_pulltorefresh@noreply.github.com>
抄送人：SunflowerGJ <gaojie603@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[peng8350/flutter_pulltorefresh]_第一页10条没有占满屏幕的时候，不会自动加载第二页_(#181)
日期：2019年12月29日 20点12分

是想第一页加载出来后，如果不满一屏，就自动触发加载，直到满一屏，或者加载失败/没有更多。

**Comment by peng8350** [comment]
controller里有一个requestLoading主动触发加载更多,判断是否满一屏,你可以通过ScrollPosition去判断

**Comment by parcool** [comment]
> controller里有一个requestLoading主动触发加载更多,判断是否满一屏,你可以通过ScrollPosition去判断

能否给个示例，怎么通过`ScrollPosition`去判断？我之前想的是当刷新完成或加载更多后去获取`SmartRefresher`里的`child`的高度与整个容器的高度作对比，结果发现通过`child`获取到的高度始终是一个定值。

**Comment by HannibalKcc** [comment]
@parcool

`SmartRefresher` 里的 `child` 基本都是固定值，特别是 `child` 是继承于 `ScrollView`，因为按照 `flutter` 的规则，滚动组件的高度就是可视区域高度而不是滚动高度，所以就是固定的。

至于怎么通过 `ScrollPosition` 判断是否满一屏幕，可以参考官方源码 `ScrollPhysics.shouldAcceptUserOffset`

``` dart
  bool shouldAcceptUserOffset(ScrollMetrics position) {
    if (parent == null)
      return position.pixels != 0.0 || position.minScrollExtent != position.maxScrollExtent;
    return parent!.shouldAcceptUserOffset(position);
  }
```

有兴趣顺便看一下该方法的几个重载，你就懂了
