### ISSUE TITLE
萌新求解答

### ISSUE THREAD

**Issue by taylor618** [peng8350/flutter_pulltorefresh#185]
The following assertion was thrown building partner_news_list(dirty, state: ListState#df969):
I/flutter ( 8171): search RefreshConfiguration anscestor return null,please  Make sure that RefreshConfiguration is the
I/flutter ( 8171): ancestor of that element

这个是少什么东西了？谢谢大家

**Comment by peng8350** [comment]
请使用没有命名的构造函数,copyAnscestor要确保祖先结点存在RefreshConfiguration才能用

**Comment by taylor618** [comment]
![image](https://user-images.githubusercontent.com/45160843/66892214-b604da80-f01d-11e9-8131-5b962fc4c0eb.png)
我是直接copy demo 的代码的参数都是跟你的一样但是还是不知道那里出了问题，您可以解答下吗？

**Comment by peng8350** [comment]
你直接把.copyAncestor 和context删掉就可以了
