### ISSUE TITLE
滑动惯性问题

### ISSUE THREAD

**Issue by rdsuncn** [peng8350/flutter_pulltorefresh#187]
ListView里数据较多的时候，几乎没有惯性滚动。可以对比另外一个插件 flutter_refresh

**Comment by peng8350** [comment]
这问题，我没遇到过。请附上可以触发的样例代码。

**Comment by rdsuncn** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'dart:io';
import 'package:dio/dio.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

import 'news_item.dart';

class NewsList extends StatefulWidget {
  final String categoryId;

  final String categoryName;

  NewsList({Key key, this.categoryId, this.categoryName}) : super(key: key);

  _NewsListState createState() => _NewsListState();
}

class _NewsListState extends State<NewsList> {

  List _listItems;
  int _pageIndex = 1;

  _getNewsList() async {
    print('getNewsList');
    var url = 'http://gh.crec.cn:9080/zt-api/information/list?pageIndex=$_pageIndex&pageSize=10&categoryId=' + widget.categoryId; 

    var result;
    try {
      // var request = await httpClient.getUrl(Uri.parse(url));
      // var response = await request.close();
      Response response = await Dio().get(url);
      if (response.statusCode == HttpStatus.ok) {
        setState(() {
          _listItems.addAll(response.data['data']);
        });
      } else {
        result =
            'Error getting IP address:\nHttp status ${response.statusCode}';
      }

    } catch (exception) {
      print(exception);
      result = 'Failed getting IP address';
    }
  }

  @override
  void initState() {
    super.initState();

    _listItems = List();
    print(widget.categoryId);
    this._getNewsList();
  }

  RefreshController _refreshController =
      RefreshController(initialRefresh: false);

  void _onRefresh() async{
    // monitor network fetch
    //await Future.delayed(Duration(milliseconds: 1000));
    _pageIndex = 1;
    await _getNewsList();
    // if failed,use refreshFailed()
    _refreshController.refreshCompleted();
  }

  void _onLoading() async{
    // monitor network fetch
    //await Future.delayed(Duration(milliseconds: 1000));
    _pageIndex += 1;
    await _getNewsList();
    // if failed,use refreshFailed()
    _refreshController.loadComplete();
  }

  @override
  Widget build(BuildContext context) {
    if (_listItems == null) {
      return new Center(
        heightFactor: 6,
        child: new Text('加载中...'),
      );
    }

    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(
          widget.categoryName,
          style: TextStyle(fontSize: 18.0),
        ),
        backgroundColor: Colors.blue,
      ),
      child: SafeArea(
        child: SmartRefresher(
          enablePullDown: true,
          enablePullUp: true,
          controller: _refreshController,
          onRefresh: _onRefresh,  
          onLoading: _onLoading,    
          child: ListView.builder(
          scrollDirection: Axis.vertical,
          itemCount: _listItems.length,
          itemBuilder: (context, index) {
            return NewsItem(item: _listItems[index],);
          }
          ),
        ),
        ),
    );
    
  }
}`

**Comment by peng8350** [comment]
问题已发现

**Comment by peng8350** [comment]
我猜测你应该用的是MaterialClassicalHeader吧,只有这两个header会产生这个问题,如果你定义header:ClassicHeader(),问题就没有了,那是因为MaterialClassicHeader我做了一个错误的操作,导致刷新过于频繁,所以才出现你所说的数据量大,没有惯性滑动现象吧
