### ISSUE TITLE
How can I use the MaterialClassicHeader icon as my own loading icon?

### ISSUE THREAD

**Issue by AbeerNS** [peng8350/flutter_pulltorefresh#188]
I'm using pull-to-refresh and I like the MaterialClassicHeader icon, and want to use it instead of the default CircularProgressIndicator widget from Material library (for other loading purposes).

Is it possible?

Thanks

**Comment by peng8350** [comment]
Sorry, I don't quite understand what you mean. My understanding is: do you want to use the materialClassicHeader as a footer?

**Comment by AbeerNS** [comment]
I want to use this widget in my app

![image](https://user-images.githubusercontent.com/53301190/67007459-1bc19700-f0f0-11e9-906a-1d90bc5e3486.png)

instead of the default one from flutter:
![image](https://user-images.githubusercontent.com/53301190/67007520-427fcd80-f0f0-11e9-8bad-797663dfea72.png)

**Comment by peng8350** [comment]
I think you should include RefreshProgressIndicator

**Comment by AbeerNS** [comment]
thank you, that's what I was looking for
