### ISSUE TITLE
数据较多时，上拉加载固定在底部不动了，滚动页面不会再更新数据

### ISSUE THREAD

**Issue by zhengzhigang** [peng8350/flutter_pulltorefresh#189]
我的数据一页10条，当加载道13页的时候页面跳了一下，加载更多固定到了底部，没反应了

![image](https://user-images.githubusercontent.com/22734797/67006165-f1cf9b00-f116-11e9-8172-d80d3024b7ae.png)

**Comment by peng8350** [comment]
这是非常常见的问题,请认真阅读[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/README_CN.md/#child),

**Comment by peng8350** [comment]
你要放一个标题和列表,正确的做法是采取CustomScrollView里放一个SliverToBoxAdapter和SliverList

**Comment by zhengzhigang** [comment]
好的，我试试，刚开始flutter，经验不足

**Comment by sm9i** [comment]
> 你要放一个标题和列表，正确的做法是采取CustomScrollView里放一个SliverToBoxAdapter和SliverList

我试过这。。但是 多滑几次 也会出现这个问题。我只是显示一个 高100的 Container
