### ISSUE TITLE
上拉加载的bug

### ISSUE THREAD

**Issue by nanchaodong** [peng8350/flutter_pulltorefresh#19]
上拉加载网络请求数据回来后会多次触发上拉加载的网络请求

**Comment by cikichen** [comment]
同样遇到了

**Comment by peng8350** [comment]
具体描述一下在什么情况下会触发多次，关键代码，图片，log

**Comment by johanntony** [comment]
同样遇到了

**Comment by 290125120** [comment]
通遇到，有人解决了吗

**Comment by 290125120** [comment]
> 通遇到，有人解决了吗

给sendback加了个200毫秒延迟解决了···但不是长久办法呀

**Comment by peng8350** [comment]
遇到这种情况,可以通过这种方法来解决
```
    SchedulerBinding.instance.addPostFrameCallback((_){
                    _refreshController.sendBack(false, RefreshStatus.idle);
     });
```
这段代码作用就是,等到下一次更新界面的时候,才通知更改指示器的状态为空闲。
之所以有这种问题,大概就是因为界面没被更新就修改指示器的状态造成的误判。

**Comment by peng8350** [comment]
已修复!新版本直接调用即可,内部已经设置成等下一帧再更新

**Comment by wbtvc** [comment]
还是有Bug, 一个container控件全屏，上拉一点点放开会onloading两次

**Comment by wbtvc** [comment]
> 已修复!新版本直接调用即可,内部已经设置成等下一帧再更新

还是有Bug, child是一个container控件全屏大小，上拉一点点放开会onloading两次
