### ISSUE TITLE
请支持Scrollbar

### ISSUE THREAD

**Issue by tzh-goon** [peng8350/flutter_pulltorefresh#193]
请支持 Scrollbar 嵌套 ListView

**Comment by peng8350** [comment]
本来就可以支持ScrollBar, #132

**Comment by tzh-goon** [comment]
@peng8350 
pull_to_refresh: ^1.5.6
无法下拉

SmartRefresher(
          child: Scrollbar(
                  child: ListView.builder(

**Comment by peng8350** [comment]
Scrollbar(
child: SmartRefresher(
child: ListView.builder(

这样才是正确的,child的用法请认真阅读首页
