### ISSUE TITLE
下拉不满一页面，所有数据消失

### ISSUE THREAD

**Issue by newengine** [peng8350/flutter_pulltorefresh#195]

**Comment by peng8350** [comment]
请提供详细的触发条件和情景,这种问题感觉多半是你逻辑上的问题

**Comment by newengine** [comment]
正常情况上拉，下拉都正常， 但是，如果页面已经填满第一页或者更多， 然后下拉更新， 我的streambuilder 读到的数据只是一条 （正常是15条）， 这个时候，下拉完成，整个screen页面就剩下这个最新下拉结果的一条， 其他原来的数据自动消失。

简单代码如下

_refreshController = RefreshController(initialRefresh:true);

SmartRefresher 的参数是在前面的StatefulWidget 传进来


      Scaffold(
        body: Stack(
          children: <Widget>[
            SmartRefresher(
              controller: widget.controller,
              enablePullDown: widget.enablePullDown,
              enablePullUp: widget.enablePullUp,
              onLoading: widget.onLoadMore,
              onRefresh: widget.onRefresh,
              header: WaterDropHeader(),
              child: 
                  new ListView.builder(
                    itemCount: widget.itemCount,
                    itemBuilder: widget.itemBuilder,
                  ),

            ),

            new Offstage(
              offstage: widget.isLoading != true || failedLoading,
              child: new Container(
                alignment: Alignment.center,
                color: Colours.gray_f0,
                child: new ProgressView(),
              ),
            )
          ],
        ),,

**Comment by newengine** [comment]
麻烦了，是我逻辑错误， 我自己在stream bloc 里面清空了数据， 谢谢
