### ISSUE TITLE
结合pageview使用上拉下拉

### ISSUE THREAD

**Issue by thinking001** [peng8350/flutter_pulltorefresh#198]
请问如何结合pageview使用，类似抖音的效果，谢谢！在使用过程中，下拉下拉控件不起作用

**Comment by peng8350** [comment]
不知道你指的效果是什么

**Comment by didiao11300** [comment]
同问

**Comment by peng8350** [comment]
估计你是说,垂直的PageView结合刷新的功能或者水平PageView+水平刷新吧,如果是这两个,目前我的组件机制是几乎没办法实现的

**Comment by didiao11300** [comment]
我解决了，不要适用pageview，使用sliver来写列表，physics 用PagedPhysics()；
原因是：Pageview，自己包了一层，ScrollNotication来监听滑动，以此实现onPageChange的回掉，ScrollNotication并不是scrller或者Scrollable，所以不能联动

**Comment by peng8350** [comment]
@didiao11300 正解

**Comment by peng8350** [comment]
已经[添加](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/otherwidget/refresh_pageView_example.dart)了例子去实现垂直刷新+垂直PageView

**Comment by qq326646683** [comment]
直接这样就可以达到pageview效果
```
SmartRefresher(
      child: ListView.builder(
        physics: const PageScrollPhysics()
      ),
    )
```

**Comment by qq326646683** [comment]
我试了这样也行
```
SmartRefresher(
      child: ListView.builder(
        physics: const PageScrollPhysics(),
      ),
    )
```

**Comment by qcks** [comment]
> 已经[添加](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/otherwidget/refresh_pageView_example.dart)了例子去实现垂直刷新+垂直PageView

例子与PageView的滚动效果相差甚远 @didiao11300  可能是版本原因去除已无效
