### ISSUE TITLE
classic_indicator.dart没有引入'package:meta/meta.dart'包报错

### ISSUE THREAD

**Issue by JakeyYe** [peng8350/flutter_pulltorefresh#2]
![image](https://user-images.githubusercontent.com/20735044/40464135-f3fb83e8-5f4b-11e8-902c-bae2a355a38a.png)
classic_indicator.dart这个文件提示找不到“required”,应该要引入'package:meta/meta.dart'包。

**Comment by JakeyYe** [comment]
Android 编译的过程中提示的该错误。

**Comment by peng8350** [comment]
你试下升级dart或flutter到最新版本试试

**Comment by JakeyYe** [comment]
最新版的Dart或Flutte不引入那个包已经可以直接使用required了？嗯，可以试试。
