### ISSUE TITLE
上拉加载更多的问题

### ISSUE THREAD

**Issue by sm9i** [peng8350/flutter_pulltorefresh#200]
上拉加载更多，如果没有数据的话   Pull up Load more 会一直停留在底部。
调用  refreshController.loadComplete();   refreshController.loadNoData();
两个都没效果，，还是停留在底部。。

布局是SmartRefresher  ListView.builder  

![5A90EDEE1BFCC013CAECB6F4E3C2EB2C](https://user-images.githubusercontent.com/31961133/68069724-3e65d800-fd9f-11e9-9d74-5f5e3cc84538.jpg)

**Comment by peng8350** [comment]
对footer用这个属性loadStyle:LoadStyle.showWhenLoading

**Comment by sm9i** [comment]
我想我找到问题了。。我应该是 loadNoData和 loadComplete  同时调用了。。。就会 这样。。我去掉loadComplete就ok了。

**Comment by sm9i** [comment]
但是初始的话 还是会有 foot 显示。第一次 没有数据的时候

**Comment by sm9i** [comment]
还有个问题，怎么设置 拉到底部松手后才会 触发 loadMore 而不是  碰到就 触发

**Comment by sm9i** [comment]
我也遇到了 loadMore 两次就会很卡。但不是数据源的问题，因为我List返回Container 都很卡。并且直接跳到 顶部
