### ISSUE TITLE
我尝试根据自定义gif demo 运行， 但是会有如下报错，请问应该如何解决

### ISSUE THREAD

**Issue by jahnli** [peng8350/flutter_pulltorefresh#202]
![image](https://user-images.githubusercontent.com/20943608/68215664-952b1600-001a-11ea-8dba-e4375f5ee5fe.png)

I tried to run a custom GIF demo, but when I quit, I got the error

**Comment by peng8350** [comment]
估计是你没有把gifController.dispose掉

**Comment by jahnli** [comment]
我已经dispose掉了，但还是有此错误




在2019年11月06日 16:43，Jpeng 写道：

估计是你没有把gifController.dispose掉

**Comment by peng8350** [comment]
把gif_image升级到1.0.1试试
