### ISSUE TITLE
 pull up throw a exception

### ISSUE THREAD

**Issue by lyf571321556** [peng8350/flutter_pulltorefresh#204]
Another exception was thrown: Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/pointer_signal_resolver.dart:32:12

code :
return StreamBuilder(
      stream: _projectListBloc.projectListStream,
      builder: (context, snapshot) {
        return Scaffold(
          body: SmartRefresher(
            controller: _refreshController,
            enablePullDown: true,
            enablePullUp: true,
            header: WaterDropHeader(
              waterDropColor: Theme.of(context).primaryColor,
            ),
            onLoading: () {
              _projectListBloc.onLoadMore();
            },
            onRefresh: () {
              _projectListBloc.onRefresh();
            },
            child: ListView.builder(
                itemExtent: 100,
                itemCount: snapshot.data == null ? 0 : snapshot.data.length,
                itemBuilder: (BuildContext context, int index) {
                  return Container(
                    child: Text(snapshot.data[index]),
                  );
                }),
          ),
        );
      },
    );

**Comment by peng8350** [comment]
If you still have this issue,you can renew an issue.remember give more details
