### ISSUE TITLE
scaffold包含bottomnavigationbar的时候 底部的上拉刷新进度看不到

### ISSUE THREAD

**Issue by lyf571321556** [peng8350/flutter_pulltorefresh#205]
比如这样的布局

Scaffold(
          appBar: MyAppBar(
          body: Scaffold(
          body: SmartRefresher()),
          drawer: new Drawer(
            child: MainLeftMenuPage(),
          ),
          bottomNavigationBar: NavigationBarWidget(
            _tabController,
            key: _NavigationBarStateKey,
          ),
        )

当然有其他路径可以解决，比如不用脚手架， 自己实现，不过应该可以作为一个点考虑下；

**Comment by lyf571321556** [comment]
不是NavigationBarWidget导致的底部上拉加载进度看不到，去掉了也还是被遮挡的

**Comment by jz8912** [comment]
最后如何解决的？
