### ISSUE TITLE
iOS 上 bounces 滚动效果 onLoading 后回弹的问题

### ISSUE THREAD

**Issue by ghostpancn** [peng8350/flutter_pulltorefresh#208]
问题视频：https://youtu.be/fUErlYRgJj8
onLoading 加载数据快的时候弹性滚动还没恢复的过程中插入 item，会导致回弹一截，速度快的时候可能导致回弹一大截。
视频是例子中 shimmer_indicator.dart 中将 onLoading 方法内的延时缩小到 200 毫秒可以复现。
这种情况怎么去避免？目前项目中临时解决做了个延时。可以在滚动恢复之后再去触发回调吗？

**Comment by g754687222** [comment]
我也遇到了这个问题，我是安卓，设置platform: TargetPlatform.iOS时，滑动加载更多，列表还会自动滚动，正常应该卡住，底部显示新的数据，目前我是listview.builder 设置了 physics: ClampingScrollPhysics(),

**Comment by peng8350** [comment]
这个问题即便不用我的库也有这问题。要解决的话,强行只能加载触发后切断弹性,而且触发加载回调也要考虑没有弹性的情况,很复杂。临时的解决方法就是根据你自己的需求去延时再请求数据。

**Comment by peng8350** [comment]
已经增加方法终止回弹

**Comment by joechan-cq** [comment]
这个issue解决了？我用1.6.3的版本发现在回弹过程中loadMore数据出现，并不会终止回弹，还是会继续往回滚动

**Comment by joechan-cq** [comment]
找到原因了，只有在loadMore完成之后，再设置给SmartRefresher{enablePullUp：false}时才会出现，也就是最后一次loadMore行为。
因为loadMore成功，加载了最后一波数据后，触发了`IndicatorStateMixin.disposeListener()`方法，移除了listener。然后调用refreshController.loadComplete()之后，里面的mode产生变化，但listeners为空，所以不会触发`_handleModeChange`方法，也就不会执行`_position.beginActivity(IdleScrollActivity(_position as ScrollActivityDelegate));`，所以回弹没能取消掉
