### ISSUE TITLE
上拉加载十多屏之后出现bug！

### ISSUE THREAD

**Issue by ltq2017** [peng8350/flutter_pulltorefresh#209]
每次上拉加载十多屏之后，就会出现白屏闪一下，然后就一直卡在pull up Load more 
ListView就无法滚动。
queryMessageList()方法中的数据能读出来，

void _onRefresh() async{
     
    skipWhileId=null;
    isRefresh=true;
    queryMessageList();
    await Future.delayed(Duration(milliseconds: 500));
    if(!mounted)return;
    _refreshController.refreshCompleted();
  }

  void _onLoading() async{

    queryMessageList();
    await Future.delayed(Duration(milliseconds: 500));
    if(!mounted)return;
    if(!isMore)_refreshController.loadNoData();
    _refreshController.loadComplete(); 
  }
 Widget _listView=ListView.builder(
      shrinkWrap:true,
      controller:_scrollController,
      itemCount: items.length, 
      itemBuilder: (BuildContext context, int index) {
        var result= ListTile(
            leading:IconFont.setIcon(
              code: 0xe672,
              color: AppTheme.font_color_666,
              size: 28.0
            ),
            title:Text(items[index].subject,style: TextStyle(fontSize: 16.0,color: AppTheme.font_color_333,decoration: TextDecoration.none),),
            subtitle:Text(items[index].content,style: TextStyle(fontSize: 12.0,color: AppTheme.font_color_666,decoration: TextDecoration.none,),maxLines: 3,overflow: TextOverflow.ellipsis,),
            trailing: IconFont.setIcon(
              code: 0xe673,
              color: AppTheme.font_color_666,
              size: 23.0
            ),
            onTap: (){},
          );
        var result2=Container(
          child:Column(
              children: <Widget>[
              result,
              Divider(height: 1.0,)
            ],
          ),
        );
        return result2;
      },
    );
    _listView=Material(type: MaterialType.transparency,child: _listView,);

    Widget _body=SmartRefresher(
      enablePullDown:true,
      enablePullUp:true,
      header: WaterDropMaterialHeader(),
      controller: _refreshController,
      onRefresh:_onRefresh,
      onLoading: _onLoading,
      child: _listView,
    );
    _body=Container(
      width: double.infinity,
      height: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
      ),
      child: _body,
    );

换成官方的刷新就正常了
 _listView=RefreshIndicator(//下拉刷新
        onRefresh:_onRefresh,
        displacement:80.0,
        color:AppTheme.main_color,
        backgroundColor: Colors.white,
        child:_listView
     );

**Comment by TreeLiked** [comment]
我也遇到了这个问题，加载十多屏后就卡在那里了

**Comment by peng8350** [comment]
显然,卡顿的问题在于你给ListView外部再包一个Material,然后我内部当作无滚动来处理了,Material应该放在SmartRefresher外部,请好好看README
