### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by g754687222** [peng8350/flutter_pulltorefresh#213]
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'value' was called on null.
    Receiver: null
    Tried calling: value
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
    #1      RefreshPhysics.createBallisticSimulation (package:pull_to_refresh/src/internals/refresh_physics.dart:293:31)
    #2      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:146:43)
    #3      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:206:5)
    #4      ScrollPositionWithSingleContext.animateTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:179:7)
    #5      RefreshController.requestRefresh.<anonymous closure>.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:650:17)
    <asynchronous suspension>
    #6      _rootRunUnary (dart:async/zone.dart:1132:38)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
    #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
    #10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
    #11     Future._complete (dart:async/future_impl.dart:512:7)
    #12     new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
    #13     _rootRun (dart:async/zone.dart:1120:38)
    #14     _CustomZone.run (dart:async/zone.dart:1021:19)
    #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #17     _rootRun (dart:async/zone.dart:1124:13)
    #18     _CustomZone.run (dart:async/zone.dart:1021:19)
    #19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
    #20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
    #21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
    #22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
    #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by Dolphii** [comment]
看下你的CustomFooter或者Header里面是不是没写builder方法

**Comment by g754687222** [comment]
是我自己些的有问题，页面没有创建，我就调用了requestRefresh
