### ISSUE TITLE
It is not work, when the child is "NestedScrollView",

### ISSUE THREAD

**Issue by pizi6** [peng8350/flutter_pulltorefresh#216]
like this:
`SmartRefresher(
          child: NestedScrollView(
                   ...
                   body:TabBarView(
                             children:[
                                          SmartRefresher(
                                          child:CustomScrollView()
                                          )
                             ]
      )
 )`

**Comment by peng8350** [comment]
I think you should read the README carefully

**Comment by peng8350** [comment]
If you need SmartRefresher wrap NestedScrollView,there is impossiable to implements,NestedSrollView not support outside bouncing,for more details,you can check the source code in nested_scroll_view.dart,I have tried this way but failed!
