### ISSUE TITLE
哔哩哔哩那个例子可不可以完善？我需要TabBar可以切换的那种，但没找到好的实现方式

### ISSUE THREAD

**Issue by Zhayanyu** [peng8350/flutter_pulltorefresh#221]

**Comment by luddite1989** [comment]
这个无法实现的，除非自己写。

**Comment by luddite1989** [comment]
> _No description provided._

兄弟，目前这个无法实现的，除非自己写。你有方法通知我哦，谢谢

**Comment by peng8350** [comment]
它那个是要通过NestedScrollView做,而现在NestedScrollView不完善,很多问题,所以放弃了

**Comment by a272312970** [comment]
![image](https://user-images.githubusercontent.com/23735064/77642419-97294d80-6f98-11ea-88be-bae9e03dacb9.png)
如图，RefreshController中这边一个延迟50秒的任务，此时销毁widget的话，headerMode已经被dispose了也就为null了，此时去赋值的话未判空会造成空指针，望修复
