### ISSUE TITLE
这个例子中加入pulltofresh会失效

### ISSUE THREAD

**Issue by badboy-tian** [peng8350/flutter_pulltorefresh#226]
没作用

https://www.jianshu.com/p/ca79eb54a356

**Comment by peng8350** [comment]
得要看你在哪里做刷新,如果你想在SliverAppBar下面做刷新,你可以使用NestedScrollView+SmartRefresher+ListView,例子也有,在Nested.dart,如果是在上面做刷新,目前做不到,因为NestedScrollView不支持外部越界回滚。
