### ISSUE TITLE
下拉卡顿

### ISSUE THREAD

**Issue by xielei0317** [peng8350/flutter_pulltorefresh#229]
偶尔存在下拉卡顿，然后页面卡死

**Comment by xielei0317** [comment]
今天已经能够100%复现了，就是返回从下一级页面返回到有pulltorefresh的页面的时候，再次下拉就会卡死，请问这个该怎么解决？

**Comment by peng8350** [comment]
@medz 确实是用法问题,shrinkWrap这属性它会把Viewport展开到跟里面所有内容一样的大小,也就是说里面每个item没有缓存,你可以在item里dispose打个log,它是不会调用的当shrinkwrap=true,这么多item显示在一个界面肯定炸呀。你这里没必要使用shrinkWrap+NeverScroll,ListView.builder直接作为SmartRefresher's child

**Comment by peng8350** [comment]
关闭了,这个问题我在开启shrinkWrap了就可以完美重现了,我很肯定就是shrinkWrap导致卡顿。如果有出现卡顿或者数据量到达某个程度无法滑动(回退到初始位置)的问题,解决方法就是把ListView或GridView或CustomScrollView作为SmartRefresher的child。切记不要开启shrinkWrap且与SmartRefresher的child分离。

**Comment by CodeGather** [comment]
> 关闭了,这个问题我在开启shrinkWrap了就可以完美重现了,我很肯定就是shrinkWrap导致卡顿。如果有出现卡顿或者数据量到达某个程度无法滑动(回退到初始位置)的问题,解决方法就是把ListView或GridView或CustomScrollView作为SmartRefresher的child。切记不要开启shrinkWrap且与SmartRefresher的child分离。

如果关闭了shrinkWrap，高度就没有办法自动计算了，怎么解决动态添加数据，是否有好的方案实现

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/93738845-6198b080-fc19-11ea-8a7d-06016fd4e3a6.png)
@peng8350 最近又出现了！！

我现在用法基本就是按照标准用法，将 CustomScrollView 作为 SmartRefresher 的 child！之前版本修改过然后不再卡顿。现在是即使这种标准用法也会卡顿！

**Comment by medz** [comment]
接上一个，这个在 Android 环境下和 iOS 测试环境下不卡顿，使用 Xcode 正式打包出来的 ipa 安装后，下拉太长会卡顿！轻轻下拉很近刚好能触发刷新的时候不卡顿。下拉很长距离才会卡顿。我测了另一个下拉刷新组件和 flutter 自带的下拉组件都不会出现这个问题！

**Comment by peng8350** [comment]
@CodeGather 你误解了吧,没说一定不能使用shrinkWrap,如果你想SmartRefresher嵌套在某个ListView的内部,你可以开启shrinkwrap(在SmartRefresher属性有shrinkWrap),事实上SmartRefresher也就是一个CustomScrollView来的。不过,说实在我很少见有下拉刷新套在ListView里面的需求。

**Comment by TENX-S** [comment]
> +1 更新到最新版本后，android 没事，iOS 下拉卡顿。很迷。大佬肯定要说我用法问题了。我直接截图贴我用法的代码把！
> 
> ![image](https://user-images.githubusercontent.com/5564821/76034990-55018300-5f7b-11ea-9c84-87bdd13b1d8a.png)
> 
> 下面是页面卡顿效果：
> ![IMG_5970](https://user-images.githubusercontent.com/5564821/76035049-73677e80-5f7b-11ea-84a0-f935df55e109.PNG)
> 
> 这不是快速截屏的。而是要卡大约三四秒。
> 
> 之前都是好好的，更新到 `^1.5.8` 版本后就这样了。下面是我的环境信息：
> 
> ![image](https://user-images.githubusercontent.com/5564821/76035196-d6591580-5f7b-11ea-8c31-f39236a890cd.png)

Hi, @medz. I'm wondering that how do you implement this tab and bottom bar ? Do you use any dependencies or plugins?
Thanks in advance! 

I know this is **definitely not** the right place to ask this kind of question, but I can't figure out how to contact you, my apologies here.

**Comment by medz** [comment]
> > +1 更新到最新版本后，android 没事，iOS 下拉卡顿。很迷。大佬肯定要说我用法问题了。我直接截图贴我用法的代码把！
> > ![image](https://user-images.githubusercontent.com/5564821/76034990-55018300-5f7b-11ea-9c84-87bdd13b1d8a.png)
> > 下面是页面卡顿效果：
> > ![IMG_5970](https://user-images.githubusercontent.com/5564821/76035049-73677e80-5f7b-11ea-84a0-f935df55e109.PNG)
> > 这不是快速截屏的。而是要卡大约三四秒。
> > 之前都是好好的，更新到 `^1.5.8` 版本后就这样了。下面是我的环境信息：
> > ![image](https://user-images.githubusercontent.com/5564821/76035196-d6591580-5f7b-11ea-8c31-f39236a890cd.png)
> 
> Hi, @medz. I'm wondering that how do you implement this tab and bottom bar ? Do you use any dependencies or plugins?
> Thanks in advance!
> 
> I know this is **definitely not** the right place to ask this kind of question, but I can't figure out how to contact you, my apologies here.

Multiple Scaffold widgets can be nested. Scaffold can be nested.

**Comment by medz** [comment]
> > +1 更新到最新版本后，android 没事，iOS 下拉卡顿。很迷。大佬肯定要说我用法问题了。我直接截图贴我用法的代码把！
> > ![image](https://user-images.githubusercontent.com/5564821/76034990-55018300-5f7b-11ea-9c84-87bdd13b1d8a.png)
> > 下面是页面卡顿效果：
> > ![IMG_5970](https://user-images.githubusercontent.com/5564821/76035049-73677e80-5f7b-11ea-84a0-f935df55e109.PNG)
> > 这不是快速截屏的。而是要卡大约三四秒。
> > 之前都是好好的，更新到 `^1.5.8` 版本后就这样了。下面是我的环境信息：
> > ![image](https://user-images.githubusercontent.com/5564821/76035196-d6591580-5f7b-11ea-8c31-f39236a890cd.png)
> 
> Hi, @medz. I'm wondering that how do you implement this tab and bottom bar ? Do you use any dependencies or plugins?
> Thanks in advance!
> 
> I know this is **definitely not** the right place to ask this kind of question, but I can't figure out how to contact you, my apologies here.

@TENX-S Multiple Scaffold widgets can be nested. Scaffold can be nested.

**Comment by TENX-S** [comment]
> > > +1 更新到最新版本后，android 没事，iOS 下拉卡顿。很迷。大佬肯定要说我用法问题了。我直接截图贴我用法的代码把！
> > > ![image](https://user-images.githubusercontent.com/5564821/76034990-55018300-5f7b-11ea-9c84-87bdd13b1d8a.png)
> > > 下面是页面卡顿效果：
> > > ![IMG_5970](https://user-images.githubusercontent.com/5564821/76035049-73677e80-5f7b-11ea-84a0-f935df55e109.PNG)
> > > 这不是快速截屏的。而是要卡大约三四秒。
> > > 之前都是好好的，更新到 `^1.5.8` 版本后就这样了。下面是我的环境信息：
> > > ![image](https://user-images.githubusercontent.com/5564821/76035196-d6591580-5f7b-11ea-8c31-f39236a890cd.png)
> > 
> > 
> > Hi, @medz. I'm wondering that how do you implement this tab and bottom bar ? Do you use any dependencies or plugins?
> > Thanks in advance!
> > I know this is **definitely not** the right place to ask this kind of question, but I can't figure out how to contact you, my apologies here.
> 
> @TENX-S Multiple Scaffold widgets can be nested. Scaffold can be nested.

Thank you for the reply.

I seem to understand a bit. And if it doesn't bother you too much, would you mind sending me a demo to learn some stuff like that.

Best regards!

**Comment by medz** [comment]
@TENX-S Code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int index = 1;
  PageController pageController;

  @override
  void initState() {
    super.initState();
    pageController = PageController(
      initialPage: index,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        controller: pageController,
        children: [
          HomePage(),
          Explore(),
          Search(),
        ],
        physics: const NeverScrollableScrollPhysics(),
      ),
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: index,
        onTap: (int index) {
          this.setState(() {
            this.index = index;
            pageController.jumpToPage(index);
          });
        },
        items: [
          BottomNavigationBarItem(
            label: 'Home',
            icon: Icon(Icons.home)
          ),
          BottomNavigationBarItem(
            label: 'Explore',
            icon: Icon(Icons.explore)
          ),
          BottomNavigationBarItem(
            label: 'Search',
            icon: Icon(Icons.explore)
          ),
        ],
      ),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with SingleTickerProviderStateMixin {
  TabController controller;

  @override
  void initState() {
    super.initState();
    controller = TabController(initialIndex: 0, length: 3, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: TabBar(tabs: [
            Tab(text: 'Tab 1'),
            Tab(text: 'Tab 2'),
            Tab(text: 'Tab 2'),
          ],
          controller: controller,
          isScrollable: true
        ),
      ),
      body: TabBarView(
        controller: controller,
        children: [
          Text('Tab 1'),
          Text('Tab 2'),
          Text('Tab 3'),
        ],
      ),
    );
  }
}

class Explore extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Explore'),
      ),
    );
  }
  
}

class Search extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text('Search');
  }
  
}
```

**Comment by TENX-S** [comment]
> @TENX-S Code:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   int index = 1;
>   PageController pageController;
> 
>   @override
>   void initState() {
>     super.initState();
>     pageController = PageController(
>       initialPage: index,
>     );
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: PageView(
>         controller: pageController,
>         children: [
>           HomePage(),
>           Explore(),
>           Search(),
>         ],
>         physics: const NeverScrollableScrollPhysics(),
>       ),
>       bottomNavigationBar: BottomNavigationBar(
>         currentIndex: index,
>         onTap: (int index) {
>           this.setState(() {
>             this.index = index;
>             pageController.jumpToPage(index);
>           });
>         },
>         items: [
>           BottomNavigationBarItem(
>             label: 'Home',
>             icon: Icon(Icons.home)
>           ),
>           BottomNavigationBarItem(
>             label: 'Explore',
>             icon: Icon(Icons.explore)
>           ),
>           BottomNavigationBarItem(
>             label: 'Search',
>             icon: Icon(Icons.explore)
>           ),
>         ],
>       ),
>     );
>   }
> }
> 
> class HomePage extends StatefulWidget {
>   @override
>   _HomePageState createState() => _HomePageState();
> }
> 
> class _HomePageState extends State<HomePage> with SingleTickerProviderStateMixin {
>   TabController controller;
> 
>   @override
>   void initState() {
>     super.initState();
>     controller = TabController(initialIndex: 0, length: 3, vsync: this);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>           title: TabBar(tabs: [
>             Tab(text: 'Tab 1'),
>             Tab(text: 'Tab 2'),
>             Tab(text: 'Tab 2'),
>           ],
>           controller: controller,
>           isScrollable: true
>         ),
>       ),
>       body: TabBarView(
>         controller: controller,
>         children: [
>           Text('Tab 1'),
>           Text('Tab 2'),
>           Text('Tab 3'),
>         ],
>       ),
>     );
>   }
> }
> 
> class Explore extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Explore'),
>       ),
>     );
>   }
>   
> }
> 
> class Search extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Text('Search');
>   }
>   
> }
> ```

Thanks a lot!

**Comment by wds1181977** [comment]
已解决，根本原因是  shrinkWrap: true, 不要这样写，尽量用SliverGrid SliverList
