### ISSUE TITLE
iOS SafeArea

### ISSUE THREAD

**Issue by danielgchap** [peng8350/flutter_pulltorefresh#232]
Hi there, 
great work on this!
One question. When I pull to refresh and the SmartRefresher pops to the top (after letting go) and is displaying 'Refreshing', the text is underneath that annoying black hardware tab on an iPhone X.
How can I lower the text of the SmartRefresher so that it's not concealed under that?

I've tried working with SafeArea and am unsure which parameter within your pub will fix this.

Thank you!

**Comment by peng8350** [comment]
get no reply,this issue will be close.If you still have this issue,reopen it.
