### ISSUE TITLE
PageView 嵌套 listview 数据超过一屏 无法手动下拉刷新

### ISSUE THREAD

**Issue by yanghengyh** [peng8350/flutter_pulltorefresh#233]
SmartRefresher( child: PageView.builder(
                physics: ClampingScrollPhysics(),
                itemBuilder: (context, index) {
                  return ListView()

                },
                itemCount: 3,
                dragStartBehavior: DragStartBehavior.down,
              ))

**Comment by peng8350** [comment]
肯定没法下拉刷新啊,因为ListView是占满全部位置的,更高的优先级

**Comment by LinXiaoTao** [comment]
那怎么解决呢？
