### ISSUE TITLE
更新了flutter后footer出现错误：SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.

### ISSUE THREAD

**Issue by what2003** [peng8350/flutter_pulltorefresh#234]
更新了flutter后footer出现错误：SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.    

════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.
The render object whose geometry violates the constraints is the following: RenderSliverLoading#36d29 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
The remainingPaintExtent is 237.0, but the paintOrigin + paintExtent is 292.0.
The paintOrigin and paintExtent must cause the child sliver to paint within the viewport, and so cannot exceed the remainingPaintExtent.
The relevant error-causing widget was
    CustomFooter 
lib/forum_main.dart:39
When the exception was thrown, this was the stack
#0      RenderSliver.debugAssertDoesMeetConstraints.<anonymous closure> 
package:flutter/…/rendering/sliver.dart:1215
#1      RenderSliver.debugAssertDoesMeetConstraints 
package:flutter/…/rendering/sliver.dart:1229
#2      RenderObject.layout.<anonymous closure> 
package:flutter/…/rendering/object.dart:1770
#3      RenderObject.layout 
package:flutter/…/rendering/object.dart:1772
#4      RenderViewportBase.layoutChildSequence 
package:flutter/…/rendering/viewport.dart:451
...
The following RenderObject was being processed when the exception was fired: RenderSliverLoading#36d29 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderSliverLoading#36d29 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 237.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 487.0 cacheOrigin: 0.0 )
    geometry: SliverGeometry(scrollExtent: 0.0, paintExtent: 55.0, paintOrigin: 237.0, maxPaintExtent: 55.0, hasVisualOverflow: true, cacheExtent: 55.0)
        scrollExtent: 0.0
        paintExtent: 55.0
        paintOrigin: 237.0
        maxPaintExtent: 55.0
        hasVisualOverflow: true
        cacheExtent: 55.0
    child: _RenderLayoutBuilder#47e10 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: paintOffset=Offset(0.0, -0.0) (can use size)
        constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
        size: Size(375.0, 55.0)
        child: RenderSemanticsGestureHandler#d6f37 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: offset=Offset(0.0, 0.0) (can use size)
            constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
            size: Size(375.0, 55.0)
            gestures: tap
            child: RenderPointerListener#3324b relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none> (can use size)
                constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
                size: Size(375.0, 55.0)
                behavior: opaque
                listeners: down
                child: RenderConstrainedBox#ad0f9 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none> (can use size)
                    constraints: BoxConstraints(w=375.0, 0.0<=h<=Infinity)
                    size: Size(375.0, 55.0)
                    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=55.0)
════════════════════════════════════════════════════════════════════════════════

**Comment by yanjiaxue** [comment]
me too

**Comment by XenonChau** [comment]
The same as yours.

**Comment by XenonChau** [comment]
You can try warp smart refresher with a exactly height container if your tile is not dynamic height.
```
Container(
        height: 100.0 * _dataSource.length,
        child: SmartRefresher(
          ......
```

### **It will be a temporary solution.**

**Comment by progid** [comment]
I have the same issue.

**Comment by GENL** [comment]
Same issue.

**Comment by peng8350** [comment]
已修复

**Comment by patchimou** [comment]
Still having this issue
