### ISSUE TITLE
_refreshController.loadNoData();执行后再执行_onRefresh函数，底部“没有更多数据了”文字依旧显示

### ISSUE THREAD

**Issue by GanZhiXiong** [peng8350/flutter_pulltorefresh#239]
经测试，必须要在_onRefresh函数里面执行_refreshController.resetNoData();就不会再显示底部“没有更多数据了”。
代码如下：
```
void _onRefresh() {
    print('_MembersListPageState._onRefresh');
    _refreshController.resetNoData();
    pageNo = 1;
    _getData(pageNo);
  }
  
  void _onLoading() {
    print('_MembersListPageState._onLoading');
    pageNo++;
    _getData(pageNo);
  }
```
**在_onRefresh里面调用_refreshController.resetNoData();这样的写法似乎有点麻烦了**
能简化一下吗？

**Comment by peng8350** [comment]
主要是刷新后不一定要重设没有更多的状态,你可以refreshCompleted(resetFooterState: false)来简化操作。

**Comment by alvindrakes** [comment]
@peng8350 应该是 refreshCompleted(resetFooterState: true) 才是 @GanZhiXiong 想要的答案。
