### ISSUE TITLE
FutureBuilder with dynamic data not refreshing

### ISSUE THREAD

**Issue by losrobots** [peng8350/flutter_pulltorefresh#243]
Hi,

I'm having issues getting pull to refresh working with FutureBuilder building a dynamic list. When I pull down from the top, nothing happens. 

Below is a dumbed down version of my code: 

```
Widget build(BuildContext context) {
    return Scaffold(
        appBar: new AppBar(title: new Text("My Orders")),
        body: SmartRefresher(
            enablePullDown: true,
            enablePullUp: true,
            header: MaterialClassicHeader(),
            footer: CustomFooter(
              builder: (BuildContext context, LoadStatus mode) {
                return Container(height: 0.0);
              },
            ),
            controller: _refreshController,
            onRefresh: _onRefresh,
            onLoading: _onLoading,
            child: FutureBuilder(
                future: _getOrders(),
                builder: (context, snapshot) {
                  return new ListView.builder(
                    itemBuilder: (c, i) => 
                        Card(child: Center(child: Text(snapshot.data[i]))),
                    itemExtent: 248.0,
                    itemCount: snapshot.data.length,
                  );
                })));
  }

 Future _getOrders() async {
    return ["1","2","3","4","5","6", "7", "8", "9"];
  }
```

![ezgif-3-06a35ee0847b](https://user-images.githubusercontent.com/8251085/72843211-0f595700-3c68-11ea-9cb1-a1f04474c5cd.gif)

Thanks in advance for your help.

**Comment by peng8350** [comment]
you misunderstand the "child" usage,read README carefully

**Comment by losrobots** [comment]
I've tried a lot of different things. How about some help rather than just dismissing me entirely?

**Comment by peng8350** [comment]
FutureBuilder should be outside SmartRefresher.It mean SmartRefresher's child must be extends ScrollView(If you have a Scrollable Widget). about why to do so. you can read [this](https://github.com/peng8350/flutter_pulltorefresh#child).

**Comment by losrobots** [comment]
Thank you. I will try that.
