### ISSUE TITLE
When using a CupertinoTabbarScaffold switching tabs can break refresher

### ISSUE THREAD

**Issue by phillipthelen** [peng8350/flutter_pulltorefresh#244]
This happens when using CupertinoTabBarScaffold with CupertinoTabBarViews. If you switch tabs while the refresh is happening and then go back to the tab that was refreshing, the ListView (probably also happens with other widgets, but that's what I observed it with) is still moved down to the position it had during the refreshing, but the refresh widget is gone and pulling down also does not trigger another refresh.

My guess is that switching tabs destroys the widget somehow and it gets stuck in a weird state?

**Comment by peng8350** [comment]
Sorry,I don’t understand.Can you give me a gif or video?I guess this issue is similar with #134
