### ISSUE TITLE
Scroll position issue when using NestedScrollView and NestedRefresh

### ISSUE THREAD

**Issue by ryankauk** [peng8350/flutter_pulltorefresh#245]
If you use your example NestedRefresh and supply initialRefresh to the refresh controller you will notice the scroll position does not stay at the top and after animation ends the top sits halfway through card 2.

**Comment by peng8350** [comment]
this problem indeed exist ,but I have no idea how to fix this.because Nestedscrollview itself has many problems,you can check flutter issue.It is not advice to use NestedScrollVIew+Refresh
