### ISSUE TITLE
如何实现默认铺满整个屏幕的？

### ISSUE THREAD

**Issue by parcool** [peng8350/flutter_pulltorefresh#248]
![image](https://user-images.githubusercontent.com/12092478/74115926-4c23c880-4bec-11ea-83a2-ea8789e4ac38.png)

如图。首次请求如果条数较少且item高度自适应，就有可能出现图上的每页铺满屏幕却没自动加载更多，此时再往上拉的时候感觉底部的‘加载更多’提示像bug一样。
问题：如何实现默认根据屏幕与item的数据高度自动加载更多以铺满屏幕？

**Comment by wangxiaobupt** [comment]
起始数量不满一屏幕的时候 加载更多会很奇怪 会瞬间下去

**Comment by peng8350** [comment]
1.你可以自定义一个Sliver组件,根据前面占据的大小,决定自身需要布局的大小,以实现铺满整个屏幕。我demo里已经有例子实现
2.不满一页自动加载更多, 你可以通过ScrollPosition里minScrollExtentn==0且maxScrollExtent==0
