### ISSUE TITLE
Empty space between item and header.

### ISSUE THREAD

**Issue by lifenautjoe** [peng8350/flutter_pulltorefresh#25]
Hey there,

First of all, thanks for the great library! Onto the issue...

There's an empty space between one of the items and the pull to refresh item.

Here's the demostration.

![empty-space](https://user-images.githubusercontent.com/12737509/48314297-c9b2f000-e5c7-11e8-9f29-49b2fa87761b.gif)

**Comment by lifenautjoe** [comment]
Btw, I would love to donate to keep the library ongoing, so if you create a paypal account or similar let me know! I'll be happy to invite you some coffees :-)

**Comment by lifenautjoe** [comment]
If I remove the `CupertinoNavigationBar`, the problem is gone.

**Comment by lifenautjoe** [comment]
For anyone experiencing this, I just moved to the https://pub.dartlang.org/packages/loadmore library.

**Comment by peng8350** [comment]
I've just tested that without using my library, this problem still occurs.

**Comment by peng8350** [comment]
Oh,This is not a Bug.Using SafeArea that the problem is solved.
```
   new SafeArea(
      child: new SmartRefresher(.....)
  )
```
