### ISSUE TITLE
上拉加载更多后，使用.loadComplete();后，底部的loading不回弹

### ISSUE THREAD

**Issue by cnsponmas** [peng8350/flutter_pulltorefresh#250]
return SmartRefresher(controller: refreshController,
      child: _buildContent(),
      enablePullUp: true,
      enablePullDown: false,
      onLoading: () async{
       this.widget.loadMore();
       await Future.delayed(Duration(milliseconds: 1000));
       refreshController.loadComplete();
       setState(() {});
      },
      footer: ClassicFooter(),

    )

**Comment by cnsponmas** [comment]
想给horizontal_data_table 这个库得外层套一个上拉加载更多

**Comment by SukkCoder** [comment]
解决了吗？下啦刷新也不会弹

**Comment by peng8350** [comment]
定义footer里的style为LoadStyle.ShowWhenLoading
