### ISSUE TITLE
Why List-View Builder returns children with fixed height and width in SmartRefresher Widget?

### ISSUE THREAD

**Issue by ahzmie** [peng8350/flutter_pulltorefresh#254]
I can't change the height or the width of the List-View builder's children. It always gives me children of a full-screen width and fixed height.

I know that the problem is because I'm using SmartRefresher, but how can I solve it?

`SmartRefresher(
      enablePullDown: true,
      enablePullUp: true,
      header: BezierCircleHeader(
        bezierColor: Colors.deepPurpleAccent,
        enableChildOverflow: false,
      ),
      footer: CustomFooter(
        builder: (BuildContext context, LoadStatus mode) {
          Widget body;
          if (mode == LoadStatus.idle) {
            body = Text("pull up load");
          } else if (mode == LoadStatus.loading) {
            body = CircularProgressIndicator();
          } else if (mode == LoadStatus.failed) {
            body = Text("Load Failed!Click retry!");
          } else if (mode == LoadStatus.canLoading) {
            body = Text("release to load more");
          } else {
            body = Text("No more Data");
          }
          return Container(
            height: 55.0,
            child: Center(child: body),
          );
        },
      ),
      controller: _refreshController,
      onRefresh: _onRefresh,
      onLoading: _onLoading,
      child: ListView.builder(
          itemCount: items.length,
          itemExtent: 100.0,
          itemBuilder: (ctx, i) {
Container(
                  width: 50,
                  height: 600,)
          }`

**Comment by peng8350** [comment]
this is not the library problem.You can read the flutter document how to use ListView
