### ISSUE TITLE
这个组件不支持PageView，有办法解决么

### ISSUE THREAD

**Issue by 18138870200** [peng8350/flutter_pulltorefresh#255]
Container(
      width: Application.appManage.width,
      height: Application.appManage.width,
      child: SmartRefresher(
        scrollDirection: Axis.horizontal,
        enablePullDown: true,
        enablePullUp: true,
        header: CustomHeader(
            builder: (BuildContext context, RefreshStatus mode) {
              Widget body;
              final style = TextStyle(
                fontSize: 12.0,
                color: Color(0xFF262626),
              );
              if (mode == RefreshStatus.idle) {
                body = Text("下拉刷新", style: style);
              } else if (mode == RefreshStatus.refreshing) {
                body = Column(
                  children: <Widget>[
                    Padding(
                      padding: const EdgeInsets.all(4.0),
                      child: SpinKitThreeBounce(
//                            color: Colors.black,
                        size: 8.0,
                        itemBuilder: (_, int index) {
                          return DecoratedBox(
                            decoration: BoxDecoration(
                              color: index.isEven
                                  ? Color(0XFF555555)
                                  : Color(0XFFBBBBBB),
                              borderRadius: BorderRadius.circular(4.0),
                            ),
                          );
                        },
                      ),
                    ),
                    Text("刷新中", style: style),
                  ],
                );
              } else if (mode == RefreshStatus.failed) {
                body = Text("刷新失败！点击重试！", style: style);
              } else if (mode == RefreshStatus.canRefresh) {
                body = Text("松手刷新", style: style);
              } else {
                body = Text("刷新完成", style: style);
              }
              return Container(
//                        color: Colors.red,
                  height: 50.0,
                  child: Center(child: body));
            }),
        footer: ClassicFooter(),
        controller: refreshController,
        onRefresh: (){
          print("33333");
        },
        onLoading: (){
          print("fffffffff");
        },
        child:PageView.builder(
            scrollDirection: Axis.horizontal,
           itemCount: 3,
            itemBuilder: (context, index){

              Color color = Colors.blue;
            if(index==1){
              color = Colors.red;
            }else if(index==2){
              color = Colors.yellow;
            }
            return Container(
              color: color,
              width: Application.appManage.width,
              height: Application.appManage.width,);

        })

        /*PageView(
          controller: _controller,
          scrollDirection: Axis.horizontal,
          children: <Widget>[
            Container(
              color: Color(0XFF000000),
              width: Application.appManage.width,
              height: Application.appManage.width,),
            Container(
              color: Color(0XFFcccccc),
              width: Application.appManage.width,
              height: Application.appManage.width,),
            Container(
              color: Color(0XFF000000),
              width: Application.appManage.width,
              height: Application.appManage.width,),
          ],

        ),*/
      ),
    )

**Comment by didiao11300** [comment]
同问

**Comment by peng8350** [comment]
没办法解决,目前组件的机制无法支持,除非重构

**Comment by peng8350** [comment]
修复我之前的答案,什么方向结合都可以支持,参考 #198

**Comment by 18138870200** [comment]
谢谢




| |
尚钢
|
|
邮箱：shang464708476@163.com
|

签名由 网易邮箱大师 定制

在2020年06月27日 20:52，Jpeng 写道：

修复我之前的答案,什么方向结合都可以支持,参考 #198
