### ISSUE TITLE
How to acheive the refresh indicator as like in basic example?

### ISSUE THREAD

**Issue by srishalu** [peng8350/flutter_pulltorefresh#256]
There is so much examples given in your documentation.  None of them are not brief and its quite confusing. How to achieve the refresh indicator as water drop for tabs?

Thanks in advance

**Comment by ghenry** [comment]
Set your header. See Example on pub.dev

**Comment by peng8350** [comment]
I understand this is very difficult to implement.It need you to understand flutter animation api and sliver in rendering .
