### ISSUE TITLE
加载更多在两个不同场景下遇到了问题

### ISSUE THREAD

**Issue by gaoyong06** [peng8350/flutter_pulltorefresh#261]
例如取动态下的评论列表：

场景1： 没有评论时：显示 "当前没有评论"
场景2： 取了N次以后：显示 "没有数据了"

目前只有一个：LoadStatus.noMore
没法区分这两种状态

这个问题似乎和库关系不大，但是因为都是页面的footer，所以统一放在一起，感觉好一些。

另外，还有个想法，就是当 场景1 （没有评论时），给 禁止 并且 隐藏了，但是我没找到 对应的方法（使用 LoadStatus.noMore 会引发其他问题），大家是怎么处理这个问题的？

**Comment by peng8350** [comment]
你可以根据你给的状态,显示footer不同的文字的。
