### ISSUE TITLE
包裹在折叠控件中，刷新后会自动折叠

### ISSUE THREAD

**Issue by qcdys** [peng8350/flutter_pulltorefresh#270]
#133 
@peng8350 

重现步骤
二级页面返回一级页面 回调model.refreshController.requestRefresh();
SliverPersistentHeader 100%折叠

示例
NavigatorUtils.pushResult(context, PackRouter.packAddPage, (res) {
              model.refreshController.requestRefresh();
            });

**Comment by JeremyMing** [comment]
同问，遇到了一样的问题

**Comment by peng8350** [comment]
已修正
