### ISSUE TITLE
Difference between _onRefresh and _onLoading?

### ISSUE THREAD

**Issue by rignaneseleo** [peng8350/flutter_pulltorefresh#272]
Please update the doc with a better explanation of how to use this 2 methods.
For how it is written now it is confusing,  you have the monitor network fetch in both.

In my case I'd like to use and keep the spinning animation to load data from the cloud and then when it is loaded, refresh a ListView. I've put the load data in the onRefresh and the refresh with setState in the onLoading but only the first is called:

 ```
 onRefresh: () async {
                  await checkMembersRegistrations(forced: true);//get data from cloud

                  _refreshController.refreshCompleted();
                },
  onLoading: () async {
                  await loadAndGetMembersList();//refresh of the listview

                  _refreshController.loadComplete();
                },

```

**Comment by idmontie** [comment]
Looks like `onRefresh` is fired when a pull down occurs, `onLoading` is called when a pull up occurs.

**Comment by rignaneseleo** [comment]
From my experience, the `onRefresh` is fired when you pull down, the `onLoading` is called only at the first widget build to initiate some objects or get the initial list. 

I'm still waiting some official documentation about this.

**Comment by boyuanx** [comment]
In my app, `onLoading` is not called at all. Even with `initialRefresh = true`, it calls `onRefresh` instead of `onLoading`.

**Comment by peng8350** [comment]
There are two stiuations:
1. when reverse:false,(1)pull down reach distance will callback onRefresh,(2) pull up reach distance will callback onLoading
2. when reverse:true,(1)pull down reach distance will callback onLoading,(2) pull up  reach distance will callback onRefresh
