### ISSUE TITLE
Load more freezing List ui

### ISSUE THREAD

**Issue by ManojMM026** [peng8350/flutter_pulltorefresh#274]
Hello I am using load more functionality through onLoading. I am fetching 25 at a time. It works smooth for about 5 times exactly after 6th it snaps/glitches and reset backs to initial position and get stuck there. 

I am using latest version :   pull_to_refresh: ^1.5.8.

I am calling
`  if (refreshController.isLoading) {
      refreshController.loadComplete();
    }`
whenever I am done receiving data. I cross check if I have correct array and data, no issue on my side. I am stuck here please help.

**Comment by ManojMM026** [comment]
I can confirm this is problem with lib. 
I tried different one it worked.

**Comment by EaglesChen** [comment]
Same as this issues, I observed that isLoading == false

**Comment by leszekkrol** [comment]
i had the same issue, any update?

**Comment by peng8350** [comment]
I guess you setting shrinkWrap to true.The solution is easy,setting shrinkWrap to false and move the ScrollView as SmartRefresher's child.
