### ISSUE TITLE
Using AnimatedList rather than ListView broke the functionality of Pull to refresh.

### ISSUE THREAD

**Issue by jigarpatel17** [peng8350/flutter_pulltorefresh#276]
When I have used AnimatedList instead of ListView for showing data in listing, it seems like SmartRefresher unable to handle pull to refresh.

```
SmartRefresher(
    enablePullDown: true,
    header: WaterDropHeader(),
    controller: _refreshController,
    onRefresh: _onRefresh,
    onLoading: _onLoading,
    child: AnimatedList(
          initialItemCount: 100,
          itemBuilder: (context, index, animation) =>
              _buildItem(context, 'data: ${index + 1}', animation),
          ),
)
```

Is there any one to keep both the things together?

**Comment by peng8350** [comment]
It can work with AnimatedList,But your usage has mistake,you must use CustomScrollView+SliverAnimatedList,see [here](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/otherwidget/refresh_animatedlist_example.dart)
