### ISSUE TITLE
明明执行了RefreshCompleted(),但是还是提示刷新中

### ISSUE THREAD

**Issue by EaglesChen** [peng8350/flutter_pulltorefresh#277]
![image](https://user-images.githubusercontent.com/30282214/79375730-ac880b00-7f8b-11ea-8456-9f4d76fc3cc1.png)

```
void _onRefresh(Action action, Context<RewardCollectionState> ctx) {
  getMoment().then((moments) {
    ctx.dispatch(RewardCollectionActionCreator.modify((clone) {
      clone.moments = moments;
    }));
    ctx.state.refreshController.refreshCompleted();
  }).catchError((e) {
    ctx.state.refreshController.refreshFailed();
  });
}
```

**Comment by delayhsiao** [comment]
兄弟用的是fish-redux吧？我也遇到这个问题了，你有方案了嘛？

**Comment by zx19** [comment]
一样 fish-redux 中不行

**Comment by zx19** [comment]
> 兄弟用的是fish-redux吧？我也遇到这个问题了，你有方案了嘛？

解决了吗?

**Comment by XinleZhou2018** [comment]
@zx19 我也遇到一样的问题，我加了一个延时执行，500毫秒

**Comment by peng8350** [comment]
你们是不是没有在clone方法中引用同一个refreshController?

```dart
 refrshState clone() {

    return refrshState()
    ..refreshController = refreshController
```

**Comment by EaglesChen** [comment]
> 你们是不是没有在clone方法中引用同一个refreshController?
> 
> ```dart
>  refrshState clone() {
> 
>     return refrshState()
>     ..refreshController = refreshController
> ```

老哥clone里面肯定是引用了，我暂时用LocalProps解决，目前没有发现问题。
![image](https://user-images.githubusercontent.com/30282214/88377859-82d45080-cdd2-11ea-8238-cf78d444ae19.png)

**Comment by EaglesChen** [comment]
#314

**Comment by peng8350** [comment]
Localpros也行。反正引起这个问题的根本原因是因为refreshController被替换为另一个refreshController(Hashcode不一致），我内部并没有做应对这情况的更新替换操作，所以会出问题。

**Comment by XinleZhou2018** [comment]
@peng8350 我把refreshController放到了Localpros里面，但是仍然需要延迟500毫秒调用refreshCompleted等，才能成功。否则无法进行上拉加载更多。

**Comment by EaglesChen** [comment]
> @peng8350 我把refreshController放到了Localpros里面，但是仍然需要延迟500毫秒调用refreshCompleted等，才能成功。否则无法进行上拉加载更多。

effect 代码贴出来看看

**Comment by XinleZhou2018** [comment]
```
        //更改列表数据源，渲染列表
        ctx.dispatch(
            MainMapActionCreator.updateListViewData(currentListViewData));

        Timer _timer;
        const sec = const Duration(milliseconds: 500);
        _timer = new Timer.periodic(sec, (Timer timer) {
          if (currentListViewData.length >=
              MainMapLocalProps.of(ctx).originListViewDataArray.length) {
            ctx.broadcast(StationListViewActionCreator.onChangeLoadMoreStatus(
                LoadMoreStatus.LoadMore_NoMoreData));
          } else {
            ctx.broadcast(StationListViewActionCreator.onChangeLoadMoreStatus(
                LoadMoreStatus.LoadMore_Success));
          }
          _timer.cancel();
        });
```

**Comment by XinleZhou2018** [comment]
@EaglesChen 补充一下，我的ListView是作为一个page的component，我在page层面的effect中获取数据后，刷新ListView数据源（connector连接的方式）
