### ISSUE TITLE
Does not work if webview is child of SmartRefresher

### ISSUE THREAD

**Issue by thatsenam** [peng8350/flutter_pulltorefresh#278]
SmartRefresher(
      controller: _refreshController,
          child: WebView(
          initialUrl: state.url,
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (WebViewController webViewController) {
            webController = webViewController;
            _controller.complete(webViewController);
          }),
    );

My phone turns off as soon as I run this code. I tried at least 50 times. why it does not work?

**Comment by peng8350** [comment]
It does not support WebView for now.
