### ISSUE TITLE
初始化的时候header会闪一下

### ISSUE THREAD

**Issue by DreamBuddy** [peng8350/flutter_pulltorefresh#28]
_headerHeight 默认是0 这时候header会显示在顶部，然后拿到了header的真实高度以后，才会给top赋值 隐藏到顶部~

**Comment by AstrayV** [comment]
遇到了同样的问题，你解决了吗？

**Comment by zhiwupei** [comment]
tabbar来回切换也会闪

**Comment by peng8350** [comment]
那是因为我内部要获取header的高度,flutter貌似没有办法在界面画出来之前获得真实的高度,所以要二次渲染。不过现在改了,直接给予height属性设置和header同样的高度,虽然这样确实有点奇葩,但是也不得不这样做。

**Comment by peng8350** [comment]
暂时这个问题已修复,如果有好的解决方案,请提一下
