### ISSUE TITLE
Infinite Loop not working 

### ISSUE THREAD

**Issue by harpreet9629** [peng8350/flutter_pulltorefresh#280]
I am using custom infinite loop for load more and it freeze, i don't know my code is correct or wrong. please help me
![carbon](https://user-images.githubusercontent.com/26606638/79888594-8e525d00-841a-11ea-80ea-4e894adcb0d4.png)
![carbon1](https://user-images.githubusercontent.com/26606638/79888600-8f838a00-841a-11ea-94da-07b7e8ded1d9.png)

**Comment by peng8350** [comment]
I think the reason for your problem is that your item is not cached, If your categoryPosts return too much items,It will slow down the ui performance.I suggest you to use ListView.builder instead of SingleChildScrollView
