### ISSUE TITLE
如何在禁用手动下拉刷新的同时，又可以用代码requestRefresh？

### ISSUE THREAD

**Issue by ykrank** [peng8350/flutter_pulltorefresh#282]
现在页面有这样的需求，请问怎么解决

**Comment by peng8350** [comment]
库本身就可以实现,但可能会有点复杂,现在我已经添加了一个例子去实现你的需求,思路就是点击按钮时,把enablepulldown设为true,然后主动触发刷新,当刷新状态转为idle时,把enablePulldown设置为false,详细请看[这里](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/example/useStage/tapbutton_refresh.dart)
