### ISSUE TITLE
组件是否支持onRefresh、onLoading不能同时进行？

### ISSUE THREAD

**Issue by jokerShuai** [peng8350/flutter_pulltorefresh#288]
示例：
1.已经加载2页数据[1-10][11-20]
2.同时进行上拉加载数据[21-30]、下拉刷新数据[1-10]。但是上拉加载,比下拉刷新先返回数据
3.那么最终的数据将会变成[1-10][21-30],导致中间页丢失的

**Comment by peng8350** [comment]
你可以用页数作出判断是否才添加上去的,刷新成功时,中断加载更多也可以
