### ISSUE TITLE
onRefresh之后，onLoading不执行

### ISSUE THREAD

**Issue by anhuiwangwei** [peng8350/flutter_pulltorefresh#289]
第一次网络请求，onLoading执行走网络请求，加载数据，执行loadNoData；下拉刷新，onRefresh执行走网络请求。此前操作全部正常。此时滑动到最后一条数据，onLoading不执行，无法走网络请求。麻烦看一下

**Comment by peng8350** [comment]
是的,没有更多数据的状态下是无法执行加载操作的,如果你想执行的话,你可以设置enableLoadingWhenNoData:true,这属性在RefreshConfiguration
