### ISSUE TITLE
How to manage ScrollController of SingleChildScrollView in SmartRefresher?

### ISSUE THREAD

**Issue by 5hirish** [peng8350/flutter_pulltorefresh#290]
With the following widget tree layout, the `controller` of `SingleChildScrollView` doesn't work. How should arrange my widget tree so that the controller `ScrollController` responds to `controller.animateTo(...)` or others.

```
SmartRefresher(
      enablePullDown: true,
      enablePullUp: false,
      header: WaterDropMaterialHeader(),
      controller: refreshController,
      onRefresh()=> : _onRefresh(context),
      child: SingleChildScrollView(
           controller: _controller,
           child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                mainAxisAlignment: MainAxisAlignment.start,
                children: <Widget>[.....]
           ) 
      ),
);
```

**Comment by 5hirish** [comment]
I have solved this issue temporarily by replacing the `SingleChildScrollView -> Column` widget arrangement with a `ListView`

**Comment by peng8350** [comment]
you needn't SingleChildScrollView,this is not support,you can put SingleChild to SmartRefresher's child directly.
