### ISSUE TITLE
RTL problem

### ISSUE THREAD

**Issue by ali-tafakkori** [peng8350/flutter_pulltorefresh#295]
**Hello** 
I try to use ` SmartRefresher`  in RTL app but it has bug.

![Sample](https://i.ibb.co/vmHMdMq/Screenshot-1589556670-1.png2)
According to the image does not start from the top and it has margin.

**Comment by peng8350** [comment]
I think this is not the lib problem,you may give a margin to it,try to use Scaffold

**Comment by peng8350** [comment]
please attach the example code

**Comment by ahmadnagilu** [comment]
i have same problem

**Comment by ahmadnagilu** [comment]
just change app locale to Locale('fa', 'IR') to see problem
