### ISSUE TITLE
上滑加载更多 30条以后界面布局错乱BUG

### ISSUE THREAD

**Issue by mingyouzhu** [peng8350/flutter_pulltorefresh#297]
### 数据量少的情况下没有任何问题 但是一但加载30~40条数据后界面就出现异常不能滑动了

![正常](https://user-images.githubusercontent.com/37821420/83627340-56b60380-a5c9-11ea-8f00-272aae784ab3.JPG) 

![上滑加载30~40条以后界面异常](https://user-images.githubusercontent.com/37821420/83627336-5453a980-a5c9-11ea-9e95-19fd19d7161c.JPG)

**Comment by peng8350** [comment]
更新1.6.0试试还有没有错乱,还有确保内部没有使用shrinkWrap:true

**Comment by peng8350** [comment]
关闭了,和之前很多issue都是一样的,GridView一定是要作为SmartRefresher里的child,不可分离
