### ISSUE TITLE
child是ListView时，无法下拉刷新

### ISSUE THREAD

**Issue by hu70258tao** [peng8350/flutter_pulltorefresh#301]
SmartRefresher(
          enablePullUp: false,//禁止上拉加载
          physics: AlwaysScrollableScrollPhysics(),
          controller: refreshController,
          header: WaterDropMaterialHeader(),
          onRefresh: (){
            Fimber.e("下拉刷新:${BlocProvider.of<ScanBloc>(context)}");
            BlocProvider.of<ScanBloc>(context).add(ScanEStartLoad());
          },
          child:BlocProvider<MessageBloc>(
            create: (_)=>MessageBloc(),
            child: BlocListener<MessageBloc,MessageState>(
              listener: (_,state){
                if(state.message!=null){
                  Toast.show(state.message,context,duration: 3);
                }
              },
              child: BlocBuilder<ScanBloc,ScanState>(
                condition: (pre,current){
                  if(current is ScanSEndLoad){
                    refreshController.refreshCompleted();
                  }
                  return true;
                },
                builder: (_,state){
                  if(state is ScanSInit){
                    return Center(child: Text("请下拉刷新"));
                  }else if(state is ScanSACChange){
                    return Center(child: Text("${state.value}",style: TextStyle(fontSize: 40)));
                  }else if(state is ScanSEndLoad){
                    List<Widget> rows = List<Widget>();
                    rows.add(Container(height: 10,color: Colors.red));
                    for(DataScanDevice device in state.devices ){
                      rows.add(BlocProvider<ScanDeviceBloc>(
                        create: (_)=>ScanDeviceBloc(device,BlocProvider.of<MessageBloc>(context)),
                        child: ScanDevicePage(),
                      ));
                    }
                    rows.add(Container(height: 10,color: Colors.red,));
//                    return Container(
//                      height: MediaQuery.of(context).size.height*0.8,
//                      color: Colors.yellow,
//                      child: ListView.separated(
//                        physics: AlwaysScrollableScrollPhysics(),
//                        itemBuilder: (context, index)=>rows[index],
//                        separatorBuilder: (context, index)=>Container(color: Colors.blue,height: 10),
//                        itemCount: rows.length
//                      ),
//                    );
                    return ListView.builder(
                      itemCount: 20,
                      itemExtent: 20,
                      itemBuilder: (_,i)=>Center(child: Text("$i"),),);
                  }else{
                    return Center(child: Text("待定"));
                  }
                },
              ),
            )
          ),
        )

**Comment by peng8350** [comment]
你贴的代码child是blocprovider而不是ListView,blocprovider在外,smartrefresher在内才可以
