### ISSUE TITLE
配合使用ScrollablePositionedList时，下拉刷新和上拉加载无效？

### ISSUE THREAD

**Issue by Ian0903** [peng8350/flutter_pulltorefresh#303]
为了能sscrollTo指定的item使用了官方的widget库ScrollablePositionedList，发现作为PullToRefresh的child时，无法触发刷新和加载更多。

**Comment by peng8350** [comment]
确实没办法兼容这控件,只要没有办法存放到CustomScrollView就不可以。你可以咨询他们是否可以支持放到CustomScrollView,作为一个Sliver组件。

**Comment by taozhipeng1990** [comment]
两个很牛的组件就没法组在一起用吗？

**Comment by jejer** [comment]
scrollTo 貌似没好的解决方案
