### ISSUE TITLE
手动requestRefresh报错

### ISSUE THREAD

**Issue by tupobi** [peng8350/flutter_pulltorefresh#304]
E/flutter (  446): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'state' was called on null.
E/flutter (  446): Receiver: null
E/flutter (  446): Tried calling: state
E/flutter (  446): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (  446): #1      RefreshController.requestRefresh (package:pull_to_refresh/src/smart_refresher.dart:643:23)
E/flutter (  446): #2      _PropertyListWidgetState.initState.<anonymous closure> (package:flutterhouse730/pages/sale_or_rent_house_list_page/widgets/property_list_widget.dart:43:26)
E/flutter (  446): #3      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (  446): #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (  446): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (  446): #6      CastStreamSubscription._onData (dart:_internal/async_cast.dart:83:11)
E/flutter (  446): #7      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (  446): #8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (  446): #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (  446): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (  446): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter (  446): #12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter (  446): #13     _WhereStream._handleData (dart:async/stream_pipe.dart:209:12)
E/flutter (  446): #14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter (  446): #15     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (  446): #16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (  446): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (  446): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (  446): #19     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
E/flutter (  446): #20     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
E/flutter (  446): #21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
E/flutter (  446): #22     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (  446): #23     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (  446): #24     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (  446): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (  446): #26     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (  446): #27     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (  446): #28     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (  446): #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (  446): #30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (  446): #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

**Comment by peng8350** [comment]
这个问题已经修复,但没有发布版本,请见 #275
