### ISSUE TITLE
problem with Nested Scroll View

### ISSUE THREAD

**Issue by Dn-a** [peng8350/flutter_pulltorefresh#31]
Hi guys,
 SmartRefresher with SliverAppBar don't work.
the widget does not collapse, but I would like it to be like this:
[image](https://steemitimages.com/p/qjrE4yyfw5pEPvDbJDzhdNXM7mjt1tbr2kM3X28F6SraZkmRBCzjs3owUxTWgpZ1oeb86HLn3xrAPkaw5HvScyVBHLC8W9icVQcYw8yJnb8i2WyaMwZAASsP?format=match&mode=fit)
is there a way to do it?
thanks

**Comment by jacksun0124** [comment]
I got same issue.  SmartRefresher part won't close SliverAppBar when SliverAppBar is expanded. 

It seems like SmartRefresher break the physics between SliverAppBar and the listview with SmartRefresher. 

Does anyone have solution?

**Comment by peng8350** [comment]
The problem has been fixed. Version 1.3.0 uses the isNestWrapped attribute to be compatible.
