### ISSUE TITLE
遇到SliverAppbar的时候，SliverAppbar会自动折叠，整个页面会自动向上滚动

### ISSUE THREAD

**Issue by keluokeda** [peng8350/flutter_pulltorefresh#312]
![SVID_20200706_171157_1 2020-07-06 17_14_15](https://user-images.githubusercontent.com/16809185/86577542-f68df500-bfac-11ea-86ca-6cd1883a66ed.gif)
[项目地址](https://github.com/keluokeda/flutter_smart_sliver_error)

**Comment by peng8350** [comment]
已修正
