### ISSUE TITLE
刷新后，listview列表数据不是最新的，请帮我看看哪里的问题

### ISSUE THREAD

**Issue by 453055141** [peng8350/flutter_pulltorefresh#315]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:xerox/config/routes.dart';
import 'package:xerox/http/api.dart';
import 'package:xerox/http/http_manager.dart';
import 'package:xerox/models/article/article_list_entity.dart';
import 'package:xerox/models/i_page_entity.dart';

class ArticlesPage extends StatefulWidget {
  //大区ID
  final String regionalId;

  //国家ID
  final String countryId;

  const ArticlesPage({Key key, this.regionalId, this.countryId})
      : super(key: key);

  @override
  _ArticlesPageState createState() => _ArticlesPageState();
}

class _ArticlesPageState extends State<ArticlesPage> {
  Future future;

  IPageEntity _iPageEntity = IPageEntity();

  List<ArticleListEntity> _list = List();

  RefreshController _refreshController = RefreshController(initialRefresh: false);

  void _onRefresh() async {
    //重置分页参数到初始值并销毁列表
    _iPageEntity = IPageEntity();
    _list.clear();
    future = _getList();
    _refreshController.refreshCompleted();
  }

  void _onLoading() async {
    if (_iPageEntity.current == _iPageEntity.pages) {
      //当前页等于总页数，则无法加载
      _refreshController.loadNoData();
    } else {
      _iPageEntity.current = _iPageEntity.current + 1;
      future = _getList();
      _refreshController.loadComplete();
    }
    if (mounted) setState(() {});
  }

  @override
  void initState() {
    super.initState();
    future = _getList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
          child: buildFutureBuilder()),
    );
  }

  FutureBuilder<List<ArticleListEntity>> buildFutureBuilder() {
    return FutureBuilder<List<ArticleListEntity>>(
          future: future,
          builder: (context, snapshot) {
            switch (snapshot.connectionState) {
              case ConnectionState.none:
                return Center(
                  child: Text('加载中……'),
                );
              case ConnectionState.waiting:
              case ConnectionState.active:
                return Center(
                  child: CircularProgressIndicator(),
                );
              case ConnectionState.done:
                if (snapshot.hasError) {
                  return Center(child: Text("Error occurs! ${snapshot.error}"));
                } else if (snapshot.hasData) {
                  return buildSmartRefresher();
                }
            }
            return Center(
              child: Text('加载中……'),
            );
          },
        );
  }

  SmartRefresher buildSmartRefresher() {
    return SmartRefresher(
      enablePullDown: true,
      enablePullUp: true,
      header: WaterDropHeader(),
      footer: ClassicFooter(
        loadStyle: LoadStyle.ShowWhenLoading,
      ),
      controller: _refreshController,
      onRefresh: _onRefresh,
      onLoading: _onLoading,
      child: ListView.builder(
        padding: EdgeInsets.only(top: 30),
        itemCount: _list.length,
        itemBuilder: (context, index) => _dataList(context, _list[index]),
      ),
    );
  }

  Widget _dataList(BuildContext context, ArticleListEntity entity) {
    return Container(
      alignment: Alignment.center,
      padding: EdgeInsets.all(10),
      child: RaisedButton(
        splashColor: Colors.blue,
        padding: EdgeInsets.all(10),
        elevation: 6,
        highlightColor: Colors.cyan,
        textColor: Colors.deepOrange,
        child: Text(entity.title, style: TextStyle(fontSize: 20)),
        onPressed: () {},
      ),
    );
  }

  Future<List<ArticleListEntity>> _getList() async {
    Map<String,dynamic> map = await HttpManager().postAsync(
      url: API.GET_ARTICLES,
      tag: null,
      data: {
        "regionalId": widget.regionalId,
        "countryId": widget.countryId,
        "current": _iPageEntity.current,
        "size": _iPageEntity.size
      },
    );
    _iPageEntity = IPageEntity().fromJson(map);
    List<dynamic> list = _iPageEntity.records;
    if(null == list){
      return null;
    }
    List<ArticleListEntity> listEntity =
        list.map((e) => ArticleListEntity().fromJson(e)).toList();
    _list.addAll(listEntity);
    return listEntity;
  }
}

**Comment by peng8350** [comment]
这种问题建议直接到StackOverFlow那里发问比较快

**Comment by peng8350** [comment]
明显是你没有setState
