### ISSUE TITLE
NestedScrollView SmartRefresher 嵌套，onLoading不触发

### ISSUE THREAD

**Issue by hanlin19900610** [peng8350/flutter_pulltorefresh#317]
NestedScrollView -》SmartRefresher-》ListView ，这种嵌套时，SmartRefresher的onLoading不会被触发
`NestedScrollView(
            controller: _controller,
            headerSliverBuilder: (context, bool) {},
            body: Container(
              width: double.infinity,
              height: double.infinity,
              child: ViewStateWidget(
                state: value.viewState,
                errorRetry: () => value.initData(),
                emptyRetry: () => value.initData(),
                successWidget: SmartRefresher(
                  header: ClassicHeader(),
                  footer: ClassicFooter(),
                  controller: value.refreshController,
                  enablePullUp: true,
                  enablePullDown: true,
                  onRefresh: () => value.refresh(init: true),
                  onLoading: () => value.loadMore(),
                  child: ListView.builder(
                    itemBuilder: (context, index) =>
                        _buildItem(context, index, value.list),
                    itemCount: value.list.length,
                  ),
                ),
              ),
            ),
          )
`

**Comment by peng8350** [comment]
你这个代码例子里,我不知道ViewStateWidget是哪个库的,所以没法重现问题,经过实测在这种嵌套的情况,onLoading可以触发

**Comment by hanlin19900610** [comment]
`body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [
            SliverToBoxAdapter(
              child: Container(
                width: double.infinity,
                height: 300,
                color: Colors.red,
              ),
            ),
          ];
        },
        body: SmartRefresher(
          controller: _controller,
          header: ClassicHeader(),
          footer: ClassicFooter(),
          enablePullUp: true,
          enablePullDown: true,
          onRefresh: () => refresh(),
          onLoading: () => loadMore(),
          child: ListView.builder(
            itemBuilder: (context, index) =>
                ListTile(title: Text('Item: $index'),),
            itemCount: list.length,
          ),
        ),
      ),`
我是这么写的，但是还是无法触发onLoading

**Comment by peng8350** [comment]
你给的例子实测是可以触发onLoading,我猜测你可能是两种可能引起的:
1.autoLoad你设置了false
2.达不到footer触发距离,可加大maxUnderScrollExtent或者减少footerTriggerDistance解决
以上参数全是在RefreshConfiguration

**Comment by hanlin19900610** [comment]
是的，我看到了这个了，RefreshConfiguration里面的设置hideFooterWhenNotFull给设置成true了，然后怎么都不触发上拉了，现在已经解决了，非常感谢
