### ISSUE TITLE
headerBuilder is invalid

### ISSUE THREAD

**Issue by aa89797771** [peng8350/flutter_pulltorefresh#324]
headerBuilder is invalid in RefreshConfiguration.copyAncestor function.
In Original code, this is:  
`headerBuilder = RefreshConfiguration.of(context).headerBuilder,`
rather than like:
`footerBuilder =
            footerBuilder ?? RefreshConfiguration.of(context).footerBuilder,`

**Comment by peng8350** [comment]
ok,thanks report
