### ISSUE TITLE
Pull to refresh doesn't work if CustomScrollView children exceeds screen height

### ISSUE THREAD

**Issue by moseskarunia** [peng8350/flutter_pulltorefresh#328]
## Flutter Doctor

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-ID)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.47.3)
>  
> [✓] Connected device (1 available)            
> 
> • No issues found!

## pull_to_refresh version

> pull_to_refresh: 1.6.0

## Code
```
/// Unrelated codes

SmartRefresher(
  controller: _refreshController,
  onRefresh: () => _onRefresh(context),
  enablePullDown: true,
  child: CustomScrollView(
    controller: _scrollController,
    slivers: <Widget>[
      SliverToBoxAdapter(child: Container(height: 30)),
      SliverToBoxAdapter(child: Container(height: 30)),
      SliverToBoxAdapter(child: Container(height: 30)),
      SliverList(
        delegate: SliverChildBuilderDelegate(
          (context, index) { 
            /// return any widget
          },
          childCount: 10
        );
      ),
    ],
  )
);
```

## Additional Details

1. The problem persists (cannot pull to refresh) even if I removes `SliverList`, and use a lot of `SliverToBoxAdapter` instead.
2. The pull to refresh is functional as expected if I replace CustomScrollView with ListView containing a lot of children.

**Comment by peng8350** [comment]
I copy your code and use the same version and channel,It can pull down refresh normally.May be you can check RefreshConfiguration paramter.

**Comment by moseskarunia** [comment]
There's a detail I omitted (that I thought is not important at first), it's that I use `BlocBuilder` after `SmartRefresher` but before `CustomScrollView`.

I need to lift up that `BlocBuilder` to the very top during my workaround as well.

**Comment by peng8350** [comment]
README has said that SmartRefresher’s child must be ListView,GridView,CustomScrollView.If tha layout structure is SmartRefresher->bloc->custom ,it will cause you cannot pulltorefresh.
