### ISSUE TITLE
NestedScrollView里面有SliverPersistentHeader，body是ListView的时候，用这个刷新手势有冲突怎么解决啊

### ISSUE THREAD

**Issue by FPJack** [peng8350/flutter_pulltorefresh#329]

**Comment by peng8350** [comment]
能不能具体点?在NestedScrollView外面做刷新还是在ListView外面?如果你是想在NestedScrollView外面做刷新的话,那么这个问题可以关闭了,目前不可能实现。

**Comment by FPJack** [comment]
ListView不添加刷新的时候拖拽ListView往上滑动是NestedScrollView整体往上移动的，当NestedScrollView 里面的SliverPersistentHeader滑动到顶部悬浮不动的时候才是ListView内部滑动，这是NestedScrollView系统的嵌套滑动效果，但是ListView添加刷新之后滑动ListView是ListView内部直接滑动了，NestScrollview并不会往上移动

**Comment by peng8350** [comment]
你是阻断了NestedScrollView里的PrimaryScrollController了吧

**Comment by FPJack** [comment]
我没有做任何其他设置，ListView去掉刷新然后又可以正常滑动了，加上刷新滑动响应就变了

**Comment by peng8350** [comment]
请附上重现代码

**Comment by FPJack** [comment]
import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';

class RefreshTest extends StatefulWidget {
  @override
  _RefreshTestState createState() => _RefreshTestState();
}
class _RefreshTestState extends State<RefreshTest> {
  final List tabbarTitles = ["评论","转发"];
  TabController _controller;
@override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller = TabController(length: tabbarTitles.length, vsync: ScrollableState());
}
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("title"),),
      body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled){
            return [
              SliverToBoxAdapter(
                child: Container(color: Colors.orange,height: 200,child: Text("content"),alignment: Alignment.center,),
              ),
              SliverPersistentHeader(
                pinned: true,
                floating: true,
                delegate: SliverAppBarDelegateObj1(
                  minHeight: 50,
                  maxHeight: 50,
                  child: Container(
                      color: Colors.white,
                      alignment: Alignment.centerLeft,
                      child: TabbarWidget1(tabbarTitles,_controller)),
                ),
              ),
            ];
          },
          body: TabBarView(
            controller: _controller,
            children: [
              Test1(),
              RefreshListView()
            ],
          )),
    );
  }
}
class RefreshListView extends StatefulWidget {
  @override
  _RefreshListViewState createState() => _RefreshListViewState();
}

class _RefreshListViewState extends State<RefreshListView> {
  List<String> items = ["1", "2", "3", "4", "5", "6", "7", "8"];
  RefreshController _refreshController =
  RefreshController(initialRefresh: false);

  void _onRefresh() async{
    // monitor network fetch
    await Future.delayed(Duration(milliseconds: 1000));
    // if failed,use refreshFailed()
    _refreshController.refreshCompleted();
  }

  void _onLoading() async{
    // monitor network fetch
    await Future.delayed(Duration(milliseconds: 1000));
    // if failed,use loadFailed(),if no data return,use LoadNodata()
    items.add((items.length+1).toString());
    if(mounted)
      setState(() {

      });
    _refreshController.loadComplete();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SmartRefresher(
        enablePullDown: true,
        enablePullUp: true,
        header: WaterDropHeader(),
        footer: CustomFooter(
          builder: (BuildContext context,LoadStatus mode){
            Widget body ;
            if(mode==LoadStatus.idle){
              body =  Text("上拉加载");
            }
            else if(mode==LoadStatus.loading){
//              body =  CupertinoActivityIndicator();
              body = Text("加载中");
            }
            else if(mode == LoadStatus.failed){
              body = Text("加载失败！点击重试！");
            }
            else if(mode == LoadStatus.canLoading){
              body = Text("松手,加载更多!");
            }
            else{
              body = Text("没有更多数据了!");
            }
            return Container(
              height: 55.0,
              child: Center(child:body),
            );
          },
        ),
        controller: _refreshController,
        onRefresh: _onRefresh,
        onLoading: _onLoading,
        child: ListView.builder(
          itemBuilder: (c, i) => Card(child: Center(child: Text(items[i]))),
          itemExtent: 100.0,
          itemCount: items.length,
        ),
      ),
    );
  }
}

class Test1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(itemBuilder: (ctx,idx){
      return Text("$idx");
    },
      itemCount: 100,
      padding: EdgeInsets.zero,
    );
  }
}
class SliverAppBarDelegateObj1 extends SliverPersistentHeaderDelegate{
  // 滑动上去时显示在屏幕上的高度
  final double minHeight;
  //child 高度
  final double maxHeight;
  final Widget child;
  SliverAppBarDelegateObj1({@required this.minHeight,@required this.maxHeight,@required this.child});
  @override
  // TODO: implement minExtent
  double get minExtent => minHeight;
  @override
  // TODO: implement maxExtent
  double get maxExtent => maxHeight;
  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    // TODO: implement build
    return child;
  }
  @override
  bool shouldRebuild(SliverAppBarDelegateObj1 oldDelegate) {
    // TODO: implement shouldRebuild
    return minHeight != oldDelegate.minHeight
        || maxHeight != oldDelegate.maxHeight
        || child != oldDelegate.child;
  }
}

class TabbarWidget1 extends StatelessWidget {
  final List titles;
  final TabController _controller;
  final Color indicatorColor;
  TabbarWidget1(this.titles,this._controller,{this.indicatorColor});
  @override
  Widget build(BuildContext context) {
    Color color = indicatorColor == null ? Colors.orange : indicatorColor;
    return Container(
      color: Colors.white,
      child: TabBar(
        isScrollable: true,
        indicatorColor: color,
        labelColor: color,
        unselectedLabelColor: Colors.black,
        //线条高度
        indicatorWeight: 2,
        //线条跟文字等款
        indicatorSize: TabBarIndicatorSize.label,
        //线条底部离文字间距
        indicator: UnderlineTabIndicator(
            borderSide:
            BorderSide(color: color, width: 2),
            insets: EdgeInsets.only(bottom: 7)),
        tabs: tabbars(),
        controller:_controller ,
      ),
    );
  }
  List<Widget> tabbars(){
    final List<Widget> items = [];
    for (var title in titles){
      items.add(Tab(text: title));
    }
    return items;
  }
}
//可把代码复制放工程里UI呈现出来，第一个ListView没有集成刷新是正常的 第二个集成了刷新往上滑动就不一样了

**Comment by peng8350** [comment]
很简单,你去掉Scaffold就行了,原因如同我上面所说

**Comment by FPJack** [comment]
我去掉了Scalffold还是一样的🤦‍♂️🤦‍♂️

**Comment by zplblue** [comment]
> 我去掉了Scalffold还是一样的🤦‍♂️🤦‍♂️

所以后来解决了没。。。

**Comment by xx-li** [comment]
我碰到了一样的问题，没有用Scaffold，问题解决了吗？ @FPJack
