### ISSUE TITLE
使用GridView.builder，在页面打开的一瞬间会在页面中偏下出现mode==LoadStatus.idle时的提示文字“上拉加载”

### ISSUE THREAD

**Issue by LHMing01** [peng8350/flutter_pulltorefresh#330]
使用ListView不会出现，其他代码整体一样，只有GridView和ListView区别
。目前没在真机验证，但是Android和ios模拟器百分百出现
开启：initialRefresh

> RefreshController _refreshController =
  RefreshController(initialRefresh: true);
主要代码结构：

> return Scaffold(
      appBar: 。。。,
      body: SmartRefresher(
          enablePullDown: true,
          enablePullUp: true,
          header: MaterialClassicHeader(
            color: Colors.blue,
          ),
          footer: CustomFooter(
            builder: (BuildContext context,LoadStatus mode){
              Widget body ;
              if(mode==LoadStatus.idle){
                body =  Text("上拉加载");
              }
              。。。。
            },
            loadStyle: LoadStyle.ShowWhenLoading,
          ),
          controller: _refreshController,
          onRefresh: _onRefresh,
          onLoading: _onLoading,
          child: GridView.builder(
        。。。。。
       )
   )
);

pull_to_refresh 版本：

> pull_to_refresh: ^1.6.1

**Comment by peng8350** [comment]
这个问题确实存在,我去年已经反馈过给flutter了([这里](https://github.com/flutter/flutter/issues/36116)),但是到现在为止都还没修复。GridView出问题的原因是因为当它childCount=0时,它返回一个滚动范围大于0的数值(期望应该是等于0),而我内部又依赖preceddingScrollExtent计算前面的滚动范围。

**Comment by peng8350** [comment]
目前,你可以这么做来避免:

```dart
    child:childCount==0?Container():GridView.builder(
    。。。。。
    )
```

**Comment by LHMing01** [comment]
谢谢您的回答，帮我解决了问题！在使用pull_to_refresh时，我还遇到一个问题，当出现加载失败mode == LoadStatus.failed时，footer仍然会在松开后回缩回去，但我觉得这样不是很好，就像你例子中“加载失败！点击重试！”提示的一样，它应当还在最底下保留向用户展示load failed，用户可以点击footer重新加载（或者重新上拉触发加载）这可能需要暴露出一个类似onError的供使用者自己控制，当然您的pull_to_refresh已经很好了，这是我的一个提议。

**Comment by LHMing01** [comment]
> 目前,你可以这么做来避免:
> 
> ```dart
>     child:childCount==0?Container():GridView.builder(
>     。。。。。
>     )
> ```

**Comment by peng8350** [comment]
loadStyle:LoadStyle.ShowAlways,就可以保持底部一直显示
