### ISSUE TITLE
flutter 1.20版本 该组件下拉时候 边界渐变也会跟随着下降

### ISSUE THREAD

**Issue by liwangyong** [peng8350/flutter_pulltorefresh#337]
![image](https://user-images.githubusercontent.com/50942378/90878798-91655600-e3d8-11ea-90f2-8e657f217b63.png)

**Comment by peng8350** [comment]
实测这种情况确实存在,另外flutter doctor,把开始产生这情况的具体版本号告知一下

**Comment by peng8350** [comment]
经过检验,这是flutter有意这么设计的,我不知道material design这样设计是不是合理的。如果你想水波纹保持回原来的样子,你需要自定义GlowOverScrollIndicator,参考官方提供的。
然后把GlowOverScrollIndicator这两行代码注释掉,就不会下沉
```dart
  // 控制水波纹位置
   // _leadingController._paintOffsetScrollPixels = -notification.metrics.pixels;
   // _trailingController._paintOffsetScrollPixels =
   //     -(notification.metrics.maxScrollExtent - notification.metrics.pixels);

```

**Comment by liwangyong** [comment]
![image](https://user-images.githubusercontent.com/50942378/91508210-711e2580-e909-11ea-8b0e-68e291e558b5.png)
flutter 版本 1.20.2  我去试试 谢谢了哈

**Comment by liwangyong** [comment]
ojbk了 谢谢哈
