### ISSUE TITLE
issues with SliverPersistentHeader

### ISSUE THREAD

**Issue by MingleChang** [peng8350/flutter_pulltorefresh#34]
当我在CustomScrollView中使用SliverPersistentHeader做吸顶效果时，如果是用了SmartRefresher且开启了下拉加载，SliverPersistentHeader的吸顶效果将会在屏幕外面

```
SliverPersistentHeader(
              pinned: true,
              floating: false,
              delegate: _SliverAppBarDelegate(
                minHeight: 88,
                maxHeight: 88,
                child: SelectView(),
              ),
            ),
```

正常吸顶效果如下： 
![825341a8-68e2-4c3e-952e-7a7b025cf4e4](https://user-images.githubusercontent.com/2186746/50393237-adda6680-078f-11e9-9c05-44a4067fabac.jpeg)

当使用了SmartRefresher且开启了下拉加载之后如下:
![3d24ac0e-e4d3-41e3-85e2-549d75605907](https://user-images.githubusercontent.com/2186746/50393250-ca769e80-078f-11e9-916a-ca8068f74a44.jpeg)

Suggest：可以考虑使用SliverPersistentHeader来实现下拉组件，可能会避免这个问题

**Comment by MrReN** [comment]
请问你解决了吗，这个问题

**Comment by peng8350** [comment]
已修
