### ISSUE TITLE
请问SmartRefresher的onTwoLevel()方法能否在二楼关闭的时候也调用一次?

### ISSUE THREAD

**Issue by zenozhengs** [peng8350/flutter_pulltorefresh#341]
请问SmartRefresher的onTwoLevel()方法能否在二楼关闭的时候也调用一次,现在只有在二楼打开的时候才会调用,这样在二楼开闭状态变化的时候好做处理.
如果使用RefreshController().isTwoLevel只能用来改变视图,不太好做其他处理

**Comment by airingursb** [comment]
自己监听 headerMode 中 headerStatus 的变换即可。

```dart
refreshController.headerMode.addListener(() {
      if (_refreshController.headerStatus == RefreshStatus.twoLevelClosing) {
        musicBus.emit('__event_closeSecondFloor');
      } else if (_refreshController.headerStatus == RefreshStatus.twoLevelOpening) {
        musicBus.emit('__event_enterSecondFloor');
      }
});
```

**Comment by ZenoZhengs** [comment]
在项目中我也是这么处理的，提这个issue主要是因为两方面原因：

一是本人有点代码洁癖，想来能直接在Widget中处理逻辑，就不用再添加监听了，以后修改的时候也方便找位置

二是从onTwoLevel()命名上来看，很容易让人联想到是二楼状态发生变化就会触发回调，而不是只有打开时触发回调，容易让人产生误解

**Comment by peng8350** [comment]
2.0.0 已新增参数
