### ISSUE TITLE
初次加载时出错

### ISSUE THREAD

**Issue by piziling** [peng8350/flutter_pulltorefresh#350]
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3825
#1      Element._debugCheckStateIsActiveForAncestorLookup 
package:flutter/…/widgets/framework.dart:3839
#2      Element.dependOnInheritedWidgetOfExactType 
package:flutter/…/widgets/framework.dart:3881
#3      Scrollable.of 
package:flutter/…/widgets/scrollable.dart:255
#4      _MaterialClassicHeaderState.initState.<anonymous closure> 
package:pull_to_refresh/…/indicator/material_indicator.dart:79
...
The AnimationController notifying listeners was: AnimationController#93eee(⏮ 0.000; paused)

**Comment by shaohui93** [comment]
你解决了吗？我也出现了这个问题，flutter1.22

**Comment by shaohui93** [comment]
RefreshController和SmartRefresher没绑定之前就使用了  widget.refreshController.refreshCompleted ，增加widget.refreshController.isRefresh 在使用就可以了。loadComplete也增加判断
