### ISSUE TITLE
SmartRefresher外面包Container设置背景颜色，下拉刷新拖动背景颜色怎么修改？

### ISSUE THREAD

**Issue by didyqian** [peng8350/flutter_pulltorefresh#351]
在使用SmartRefresher之前是在ListView外面包一层Container设置背景颜色的，但是改用SmartRefresher之后，ListView外面包Container就无法下拉刷新了，本来想在SmartRefresher外包一层Container设置背景颜色，但是下拉到一定高度背景颜色就随了Container的背景颜色，怎么才能设置下拉的背景颜色随CustomHeader的背景颜色？

**Comment by peng8350** [comment]
1.Container->SmartRefresher->ListView就可以
2.指示器背景颜色，#267
