### ISSUE TITLE
页面中放横向的两个ListView，上拉和下拉失效

### ISSUE THREAD

**Issue by youxinLu** [peng8350/flutter_pulltorefresh#356]
class Test1Page extends StatelessWidget {
  List<String> items = ["1", "2", "3", "4", "5", "6", "7", "8"];
  RefreshController _refreshController =
      RefreshController(initialRefresh: false);

  void _onRefresh() async {
    // monitor network fetch
    await Future.delayed(Duration(milliseconds: 1000));
    // if failed,use refreshFailed()
    _refreshController.refreshCompleted();
  }

  void _onLoading() async {
    // monitor network fetch
    await Future.delayed(Duration(milliseconds: 1000));
    // if failed,use loadFailed(),if no data return,use LoadNodata()
    items.add((items.length + 1).toString());
    _refreshController.loadComplete();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SmartRefresher(
        enablePullDown: true,
        enablePullUp: true,
        header: WaterDropHeader(),
        footer: CustomFooter(
          builder: (BuildContext context, LoadStatus mode) {
            Widget body;
            if (mode == LoadStatus.idle) {
              body = Text("pull up load");
            } else if (mode == LoadStatus.loading) {
              body = CupertinoActivityIndicator();
            } else if (mode == LoadStatus.failed) {
              body = Text("Load Failed!Click retry!");
            } else if (mode == LoadStatus.canLoading) {
              body = Text("release to load more");
            } else {
              body = Text("No more Data");
            }
            return Container(
              height: 55.0,
              child: Center(child: body),
            );
          },
        ),
        controller: _refreshController,
        onRefresh: _onRefresh,
        onLoading: _onLoading,
        child: Row(
          children: [
            Expanded(
              flex: 1,
              child: ListView.builder(
                itemBuilder: (c, i) =>
                    Card(child: Center(child: Text(items[i]))),
                itemExtent: 100.0,
                itemCount: items.length,
              ),
            ),
            Expanded(
              flex: 1,
              child: ListView.builder(
                itemBuilder: (c, i) =>
                    Card(child: Center(child: Text(items[i]))),
                itemExtent: 100.0,
                itemCount: items.length,
              ),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by peng8350** [comment]
首先,我不知道你要实现哪个? 1.两个List共有一个refreser . 2.两个ListView各自一个refresher.
如果是第二个,请认真读README.如果是第一个的话,我很明确跟你讲,要实现难度可能很大,要使用到linkHeader,例子里有,不过可能不够清楚,毕竟没什么人提这个需求,当然你可以使用官方的RefreshIndicator来实现更为方便,它的机制很适合实现这个。
