### ISSUE TITLE
在SmartRefresher组件在Build前调用refreshController。其中headerMode和footMode都为null

### ISSUE THREAD

**Issue by QSKOBE24** [peng8350/flutter_pulltorefresh#36]
@override
  void initState() {
    // TODO: implement initState
    super.initState();

    _refreshController = new RefreshController();

    loadData();
  }

Future<Null> loadData() async {
    try {
       //获取数据
      }
      setState(() {
        //什么都不做，只为触发RefreshIndicator的子控件刷新
      });
      _refreshController.sendBack(false, RefreshStatus.idle);
    } catch (e) {
      _refreshController.sendBack(false, RefreshStatus.failed);
    }
  }

@override
  Widget build(BuildContext context) {
    if(netData.length == 0){
      // 加载菊花
      return CupertinoActivityIndicator();
    }else{
      return new SmartRefresher(
        controller: _refreshController,
        onRefresh: _onRefresh,
        onOffsetChange: _onOffsetCallback,
        child: buildListView(),
      );
    }
  }

当我在initState函数里面实例化controller的时候，这个时候发送一个网络请求获取数据。这个时候bulid函数还未调用。此时我调用 _refreshController.sendBack(false, RefreshStatus.idle);去更新当前的状态就会报这个错：

Tried calling: value=4
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      RefreshController.sendBack (package:pull_to_refresh/src/smart_refresher.dart:385:19)
#2      _RecommendedPageState.loadData (package:QGCodeFlutter/home/recommendedpage.dart:94:26)
<asynchronous suspension>
#3      _RecommendedPageState.initState (package:QGCodeFlutter/home/recommendedpage.dart:30:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#9      Element.inflateWidget (package:flu<…>
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: The setter 'value=' was called on null.

原因是：RefreshController这个类里面的
ValueNotifier<int> _headerMode;
  ValueNotifier<int> _footerMode;
  ScrollController scrollController;
全部都为null。
这个地方是否可以优化一下？？？

**Comment by baoxiehao** [comment]
遇到相同的问题。而且我是在future返回后确认widget是mounted状态才调用 sendBack 的。

**Comment by chenzhicheng163** [comment]
The same problem when i use SmartRefresher in my project！

**Comment by baoxiehao** [comment]
> The same problem when i use SmartRefresher in my project！

Suggest you use EasyRefresh.

**Comment by peng8350** [comment]
不能这么做的,因为你在initState直接请求刷新,这时界面还没被渲染出来,controller和SmartRefresher还没建立起一个连接。你要等到界面被渲染出来后,再调用请求刷新。
```
    SchedulerBinding.instance.addPostFrameCallback((_) {
      _refreshController.requestRefresh(true);
    });
```

**Comment by peng8350** [comment]
已修!可以初始化top和bottom的状态,但如果要请求刷新的操作,必须得等到界面被画出来
