### ISSUE TITLE
The repository is very heavy

### ISSUE THREAD

**Issue by GENL** [peng8350/flutter_pulltorefresh#360]
The repo is very heavy so it take too much time to be fetched by pub or even cloned(It took about 40min but haven cloned anything). Maybe certains files. Can you take a look?

![image](https://user-images.githubusercontent.com/36866702/94074778-dd4d5580-fdf1-11ea-8d0a-ef8737eecd93.png)

In the image above, I forked the repo and try to clone. But it is only 7% for 2Mb. Very heavy.

This problem starts with the version 1.6.0 and above. I add to downgrade to the version 1.5.8 to be able to fetch,

**Comment by peng8350** [comment]
it is normal,because I place many gif in it .you should open proxy to download if your download speed is very low.Please don't post unrelated issue about this library.Suggest you to StackOverflow,may be you can get the answer how to improve github download speed fastly.
