### ISSUE TITLE
flutter升级到1.22后报错

### ISSUE THREAD

**Issue by piziling** [peng8350/flutter_pulltorefresh#361]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
    MaterialClassicHeader 
lib/news/news_home_data_page.dart:212
When the exception was thrown, this was the stack
#2      ScrollPosition.applyNewDimensions 
package:flutter/…/widgets/scroll_position.dart:593
#3      ScrollPositionWithSingleContext.applyNewDimensions 
package:flutter/…/widgets/scroll_position_with_single_context.dart:103
#4      RenderSliverRefresh.performLayout 
package:pull_to_refresh/…/internals/slivers.dart:189
#5      RenderObject.layout 
package:flutter/…/rendering/object.dart:1777
#6      RenderSliverRefresh.layout 
package:pull_to_refresh/…/internals/slivers.dart:147
...

**Comment by peng8350** [comment]
duplicate #352
