### ISSUE TITLE
Header Indicator doesn't disappear after refresh

### ISSUE THREAD

**Issue by nicemanis** [peng8350/flutter_pulltorefresh#362]
Here is the code of the SmartRefresher:
```
final RefreshController _refreshController =
      RefreshController(initialRefresh: false);

SmartRefresher(
  controller: _refreshController,
  header: WaterDropHeader(),
  ...
);
```

If don't specify header and use the default one, the header disappears after refresh as expected.
If I explicitly specify any of the headers, then it does not disappear after the refresh.
My guess is that it doesn't get linked with the controller correctly.

Flutter doctor:
```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)
```

**Comment by peng8350** [comment]
It can't reproduce

**Comment by nicemanis** [comment]
I tested it with `Future.delayed(Duration(milliseconds: 1000));` and then it works correctly, but if I make an API call, then the header won't close. I'm trying to figure out why it doesn't work in the API call case.

**Comment by nicemanis** [comment]
I have added two screenshots with the values of RefreshController. If I use the default controller, you can see that `headerMode` has a listener, but in the case of custom header there are no listeners in the `ObserverList _listeners`.

The strange thing is that the custom header is working for a simple `Future.delayed` or `http.get`, but it does not work for my API calls. I checked, that there is a listener also for custom header if I use a simple `Future.delayed`. I have some extra in-between steps for my API calls, but the refreshing is working correctly with the default header, so I don't know where is the problem.

![custom header](https://user-images.githubusercontent.com/9463816/94422529-e9d60300-018f-11eb-8875-b4b9f7ff631d.png)

![default header](https://user-images.githubusercontent.com/9463816/94422517-e6427c00-018f-11eb-8826-8d50a8d1764e.png)

**Comment by peng8350** [comment]
If http.get can work,may be you should check  your api for fetching data.I think refreshcomplete is not called .

**Comment by nicemanis** [comment]
I'm calling refreshCompleted at the end:
```
    return SmartRefresher(
      controller: _refreshController,
      header: WaterDropHeader(),
      onRefresh: () async {
        await myApiCall();
        _refreshController.refreshCompleted();
```

The problem is that the listener is removed, maybe due to redux rebuild or something else.

**Comment by nicemanis** [comment]
Found the problem. It seems that the `_refreshController` loses the listener on rebuild. You can test it as follows:
1. Run the sample on Android Studio debug mode;
2. Try to refresh the list with custom header - it should work correctly;
3. Press save in the Android Studio to trigger hot reload and trigger rebuild of the list;
4. After the rebuild, the `_refreshController` will have no listeners and if you refresh the list, `.refreshCompleted()` will not close the header

**Comment by peng8350** [comment]
It seem like your refreshController is replaced by another refreshcontroller.refreshcontroller cannot be replaced in all lifecircle.You can check this issue #277 find more details.If you use redux or fish_redux,they may contain this problem.

**Comment by nicemanis** [comment]
Thank you, if I move the controller to the parent scope, it does not get rebuilded and refreshing works as expected.
