### ISSUE TITLE
_pendingDimensions': is not true.

### ISSUE THREAD

**Issue by maomao1020** [peng8350/flutter_pulltorefresh#363]
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 593 pos 12: '_pendingDimensions': is not true.

**Comment by maomao1020** [comment]
https://github.com/flutter/flutter/issues/66240

**Comment by zenkog** [comment]
I had the same problem. Then I found that the new version 1.6.2 has fixed this.

**Comment by peng8350** [comment]
Duplicate #352 .
