### ISSUE TITLE
when data count is small

### ISSUE THREAD

**Issue by ChendayUP** [peng8350/flutter_pulltorefresh#37]

**Comment by ChendayUP** [comment]
<img width="397" alt="wechat0ce03f226237fda27733ee3d121c5f37" src="https://user-images.githubusercontent.com/20022523/50632179-f8bf5f80-0f81-11e9-92b0-19970b3e697e.png">

**Comment by Purus** [comment]
There can be an option  to hide it when count is less than a desired number.

**Comment by morad00** [comment]
add this line at the first of your _footerCreate widget 
if(yourList.length < smallAmountOfItmes && mode == 0 ) return Container();

**Comment by peng8350** [comment]
The most important problem is how to get the height of all items in ListView. If this problem is solved, it will be easy.

**Comment by peng8350** [comment]
Suggest
```

    //100.0 indicate that your item height
     double innerListHeight= _data.length*100.0;
      double listHeight = bc.biggest.height;

   new SmartRefresher( 
       enablePullUp: innerListHeight>listHeight
      .....
   )
```

**Comment by peng8350** [comment]
I couldn't get the actual height of ListView inside my control before the interface was rendered. If I wanted to do this, I would have to render the interface twice, which would result in #28.

**Comment by jaime1990** [comment]
> Suggest
> 
> ```
> 
>     //100.0 indicate that your item height
>      double innerListHeight= _data.length*100.0;
>       double listHeight = bc.biggest.height;
> 
>    new SmartRefresher( 
>        enablePullUp: innerListHeight>listHeight
>       .....
>    )
> ```

然而，如上设置并不起效。 不知各位大佬还有其他良策？

**Comment by peng8350** [comment]
@jaime1990 我在1.4.2已经干掉你先前的问题的了,已去掉计算头部高度
