### ISSUE TITLE
不满一屏时，设置hideFooterWhenNotFull  = true的问题

### ISSUE THREAD

**Issue by XinleZhou2018** [peng8350/flutter_pulltorefresh#373]
不满一屏时，设置hideFooterWhenNotFull  = true。当我下拉刷新的时候，会根据返回的数据判断，如果没有更多数据了就会显示“没有更多了”，
`ctx.state.refreshController.loadNoData();
`
问题：下拉刷新后，数据不满一屏时，“没有更多了”又会显示出来。怎么处理这种问题？

**Comment by peng8350** [comment]
hidefooterwhennotfull=false即可

**Comment by XinleZhou2018** [comment]
@peng8350 但是不满一屏的时候，我不想显示“没有更多了”，怎么可以设置成false呢？
