### ISSUE TITLE
NoSuchMethodError: The method 'setCanDrag' was called on null. Receiver: null Tried calling: setCanDrag()

### ISSUE THREAD

**Issue by BoyYangyang** [peng8350/flutter_pulltorefresh#374]
更新到1.6.2版本日志报错 NoSuchMethodError: The method 'setCanDrag' was called on null. Receiver: null Tried calling: setCanDrag()
具体定位:RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:243)
![图片](https://user-images.githubusercontent.com/27199384/96086003-32155500-0ef4-11eb-8a70-c1c289192223.png)方法为空,请问是什么问题导致的

**Comment by yrom** [comment]
怎么关掉了这个issue，解决了吗？

**Comment by smadey** [comment]
终于找到原因了
因为某些操作（可能是变更 child ）导致同一个 controller 绑定了两个 header
而第1个的 header 未及时释放
第2个 header 初始化时执行的 [RefreshIndicatorState.initState](https://github.com/peng8350/flutter_pulltorefresh/blob/1.6.4/lib/src/internals/indicator_wrap.dart#L651) 
触发了第 1 个的 header 的 [RefreshIndicatorState._handleModeChange](https://github.com/peng8350/flutter_pulltorefresh/blob/1.6.4/lib/src/internals/indicator_wrap.dart#L244)

我暂时用以下方法修复了

```dart
/// 通过找共同的 controller 来识别未及时释放的 header，然后再释放即可修复
mixin _FixMultipleListener on RefreshIndicatorState<RefreshIndicatorBuilder> {
  static final Map<_FixMultipleListener, RefreshController> _map = <_FixMultipleListener, RefreshController>{};

  @override
  void initState() {
    final RefreshController controller = SmartRefresher.of(context)?.controller;
    if (controller != null) {
      _map.forEach((_, __) {
        if (__ == controller) {
          _.disposeListener();
        }
      });
    }
    super.initState();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _map[this] ??= refresher.controller;
  }

  @override
  void dispose() {
    _map.remove(this);
    super.dispose();
  }
}

class _RefreshIndicatorState extends RefreshIndicatorState<_RefreshIndicator> with _FixMultipleListener {}
```

PS: 可以看看我项目中的错误数量
![image](https://user-images.githubusercontent.com/4351454/107225284-92a44100-6a53-11eb-9adc-f241f061cc39.png)
