### ISSUE TITLE
经常会划不动，概率很大，触发条件貌似是下拉很小后释放

### ISSUE THREAD

**Issue by lgGuo** [peng8350/flutter_pulltorefresh#384]

**Comment by peng8350** [comment]
能不能具体点,RefreshConfiguration具体参数,滑到什么距离会触发,flutter版本号,哪个header?

**Comment by lijy91** [comment]
@lgGuo 看下这个是否可以解决你的问题呢 https://github.com/peng8350/flutter_pulltorefresh/pull/387#issuecomment-726477630
