### ISSUE TITLE
Footer did not hide with SliverStaggeredGrid

### ISSUE THREAD

**Issue by andoutica** [peng8350/flutter_pulltorefresh#385]
Hi, 
I got a issue with SliverStaggeredGrid. When I'm using SliverStaggeredGrid, the library worked very well, but one issue, if the items load more just one item added, the footer loading still show on the screen. 

To reproduce this issue , I changed your file refresh_staggered_and_sticky.dart with some change on onLoading method
```
onLoading: () {
            print("onload");
            Future.delayed(const Duration(milliseconds: 2000)).then((val) {
              length += 1;
              if (mounted) setState(() {});
              _refreshController.loadComplete();
            });
          },
```

![Screenshot_2020-11-08-20-23-44-36_77feeaf6e6ebcf0b1a503e90517946c6](https://user-images.githubusercontent.com/7821844/98466238-d5f6d580-2200-11eb-8ce3-19600afdbb44.png)

**Comment by peng8350** [comment]
This should not be a issue.It is a opetional choose.If you want to achieve the effect that same with header,you can reference this [example](https://github.com/peng8350/flutter_pulltorefresh/blob/d6f174627db491fdabe51fabf80569c16f1a12ea/example/lib/ui/example/customindicator/footer_underscroll.dart)

**Comment by smart005** [comment]
列表数据超过一屏且不改变数据集合的情况下确实隐藏不了，@peng8350 你自己可以试一下；
在回调里只写这一句：_refreshController.loadComplete();

**Comment by peng8350** [comment]
其实你只需要改变footer风格就能完事了

```dart
         footer: ClassicFooter(
            loadStyle: LoadStyle.ShowWhenLoading,
          )
```

**Comment by peng8350** [comment]
这种问题之前已经提了很多次,类如 #200,#250。
