### ISSUE TITLE
Multiple widgets used the same GlobalKey when setting key for SmartRefresher

### ISSUE THREAD

**Issue by altush1983** [peng8350/flutter_pulltorefresh#389]
```
final _smartRefresherKey = GlobalKey<SmartRefresherState>();

SmartRefresher(
   key: _smartRefresherKey,
);

```
produce error:
Multiple widgets used the same GlobalKey.
The key [LabeledGlobalKey<SmartRefresherState>#d23c9] was used by multiple widgets. The parents of those widgets were:
- _BodyBuilder
- RefreshConfiguration
A GlobalKey can only be specified on one widget at a time in the widget tree.

**Comment by peng8350** [comment]
I think this issue should be flutter instead this lib.If you use a globalkey to mutiple SmartRefresher at the same time,you will catch this error.

**Comment by peng8350** [comment]
another,I don't understand what you expect to do when you give a globalkey to SmartRefresher

**Comment by altush1983** [comment]
I'm using GlobalKey just for one SmartRefresher instance. GlobalKey is useful in my case to get access to setCanDrug method:
`    _smartRefresherKey.currentState?.setCanDrag(!isKeyboardVisible);`

I made pull request with the fix.

**Comment by peng8350** [comment]
If you need to disable gesture,I suggest you use NeverScrollablePhysics

**Comment by peng8350** [comment]
1.6.3 has fixed it.
