### ISSUE TITLE
After initial loading list scrolls and I cant see first record

### ISSUE THREAD

**Issue by marhyno** [peng8350/flutter_pulltorefresh#391]
Do you have any idea why this occurs ? 
Testing on android right now.
After loading more, no problem, after refreshing also no problem, only when initial loading, it scrolls little bit and hides first record.

![Screenshot_20201112-020822](https://user-images.githubusercontent.com/26349385/98882256-29308880-248c-11eb-8b1e-d7f38af16a70.jpg)

Expanded(
                  child: SmartRefresher(
                enablePullDown: true,
                enablePullUp: true,
                header: WaterDropHeader(
                    complete: Text(AppLocalizations.of(context).translate('refreshDone'),
                        style: TextStyle(color: Colors.white))),
                footer: CustomFooter(
                  builder: (BuildContext context, LoadStatus mode) {
                    Widget body;
                    if (noMoreData) {
                      mode = LoadStatus.noMore;
                    }
                    if (mode == LoadStatus.idle) {
                      body = Text(AppLocalizations.of(context).translate('pullToLoadMore'),
                          style: TextStyle(color: Colors.white));
                    } else if (mode == LoadStatus.loading) {
                      body = RefreshProgressIndicator();
                    } else if (mode == LoadStatus.failed) {
                      body = Text(AppLocalizations.of(context).translate('loadFailedTryAgain'),
                          style: TextStyle(color: Colors.white));
                    } else {
                      body = Text(AppLocalizations.of(context).translate('noMoreData'),
                          style: TextStyle(color: Colors.white));
                    }
                    return Container(
                      alignment: Alignment.bottomCenter,
                      height: 25.0,
                      child: Center(child: body),
                    );
                  },
                ),
                controller: _refreshController,
                onRefresh: refreshRecords,
                onLoading: fetchRecordByDateDesc,
                child: ListView.builder(
                        physics: AlwaysScrollableScrollPhysics(),
                        shrinkWrap: true,
                        itemCount: recordsChronologically?.length ?? 0,
                        itemBuilder: (context, index) {
                          return Column(children: <Widget>[
                            Card(

**Comment by peng8350** [comment]
shrinkWrap:false

**Comment by marhyno** [comment]
nope did not help

**Comment by marhyno** [comment]
Solved with 

ListView.builder(
                      physics: AlwaysScrollableScrollPhysics(),
                      shrinkWrap: true,
                      **primary: false,**
                      itemCount: allRecordsChronologically?.length ?? 0,
