### ISSUE TITLE
加载效果不能隐藏(总感觉有些被关掉的问题仍存在，建议用flutter_easyrefresh这个没那么严重)

### ISSUE THREAD

**Issue by smart005** [peng8350/flutter_pulltorefresh#393]
列表数据超过一屏【数据少于一屏正常】且不改变数据集合的情况下确实隐藏不了，@peng8350 你自己可以试一下；
在回调里只写这一句：_refreshController.loadComplete();

ps：**总感觉有些被关掉的问题，作者试都没试直接当作已解决关掉了**；

**Comment by peng8350** [comment]
别这么无聊行吧?你爱用那个库就用那个库,跑来这里宣传干什么,又不是强迫你用。有些问题我是很确定是这个原因才关闭的,当然也有错误关闭了的,因为本人也有其他事情要做,没那个精力每个都那么仔细

**Comment by smart005** [comment]
👍
