### ISSUE TITLE
How to show refresh indicator at starting when the user visits the page?

### ISSUE THREAD

**Issue by jagadish-pattanaik** [peng8350/flutter_pulltorefresh#397]
I want to show the refresh indicator every time the user visits the page at first for sometime

**Comment by umaqs** [comment]
You can do this using `initialRefresh` property like this:

`RefreshController _refreshController = RefreshController(initialRefresh: true);`

**Comment by jagadish-pattanaik** [comment]
It's not working...or may be it's because I am using page view and in one of the pages whenever the user swipes I want to show the refresh indicator...

**Comment by peng8350** [comment]
@jagadish-pattanaik you can use _refreshController.requestRefresh when onPageChange is called.

**Comment by xunan623** [comment]
用多个 tabpageview里都放一个SmartRefresher 那么点击某个按钮 只显示最后_refreshController.requestRefresh是成功的

**Comment by peng8350** [comment]
@xunan623 那是因为你refreshController共用了多个SmartRefresher,这个用法已经在2.0.0被强制抛出异常
