### ISSUE TITLE
Not support in CustomScrollView

### ISSUE THREAD

**Issue by luodongseu** [peng8350/flutter_pulltorefresh#4]

**Comment by peng8350** [comment]
Thanks  report,I will check this problem

**Comment by peng8350** [comment]
I've found the root of the problem. The buildSlivers implementation in BoxScrollView and CustomScrollView is different, BoxScrollView is a copy of the array, CustomScrollView is a reference array.

**Comment by peng8350** [comment]
it May be fixed!
