### ISSUE TITLE
NestedScrollView中快速向上滑动触顶后会出现刷新header

### ISSUE THREAD

**Issue by jinxing88** [peng8350/flutter_pulltorefresh#400]
正常情况下，快速向上滑动效果如下，触顶后不会出现刷新header
![1606732056394](https://user-images.githubusercontent.com/9638924/100685229-f86eaf80-33b6-11eb-9766-11a3438d3956.gif)
在NestedScrollView中，快速向上滑动效果如下，触顶后会出现刷新header
![1606731994952](https://user-images.githubusercontent.com/9638924/100685660-c6118200-33b7-11eb-99b6-973abc451341.gif)
请问如何在NestedScrollView中达到第一种效果

**Comment by peng8350** [comment]
这个问题问得挺好,但目前来说没有很好的解决办法,库内部physics里applyBoundaryCondition是没有返回错误的。没有阻断回弹,很有可能是因为NestedScrollView里改写了ScrollPosition导致的。估计只有改动NestedScrollView内部的源代码才能解决这个问题。

**Comment by peng8350** [comment]
2.0.0已经修复
