### ISSUE TITLE
如何把下拉的事件给父级Widget处理

### ISSUE THREAD

**Issue by MikaelZero** [peng8350/flutter_pulltorefresh#402]
场景是一个BottomSheetDialog里嵌套了一个刷新
关闭了下拉刷新的功能
现在是想下拉的时候  按照BottomSheetDialog逻辑关闭dialog
但是现在这个下拉事件被SmartRefresher捕捉了

**Comment by peng8350** [comment]
在我demo的例子里面的话,下拉刷新是基本无效的,会传递给父级Widget。

**Comment by MikaelZero** [comment]
是的   demo里的效果是OK的   但是把demo的列表用其他 比如Colunm进行一个嵌套  滑动就会出现问题了

**Comment by peng8350** [comment]
用Column嵌套，相当于两个滚动组件，所以就拦截了
