### ISSUE TITLE
如何首次加载就直接进入刷新状态，不出现下拉动画

### ISSUE THREAD

**Issue by PingTouG** [peng8350/flutter_pulltorefresh#403]
在创建RefreshController时指定initialRefreshStatus = RefreshStatus.refreshing，首次刷新还是出现下拉动画，不应该直接从刷新吗？
```
RefreshController(true, initialRefreshStatus: RefreshStatus.refreshing)
```
后来我又看文档发现可全局配置`skipCanRefresh：直接跳过canRefresh状态进入刷新`，然后试了一下，结果首次刷新时还是会有下拉动画，这个要怎么解决？

**Comment by peng8350** [comment]
这个skipCanRefresh你理解错了,如果你想不出现下拉动画的话,把下拉动画时间设置成0就可以

```dart

  _refreshController.requestRefresh(duration:const Duration(millseconds:0));
```
