### ISSUE TITLE
How to delete footer when there is no more data?

### ISSUE THREAD

**Issue by Ceschref** [peng8350/flutter_pulltorefresh#408]
When I complete loading to load more data but receive no data. I want to remove footer. I called loadNoData() and resetNoData() but do not resolve this. pls, help me fix it!

flutter doctor -v 

> [✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-VN)
    • Flutter version 1.22.4 at /Users/apple/Documents/develop/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)

    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

> [✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)

    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

> [✓] Android Studio (version 4.0)

    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by Ted-chiptech** [comment]
I haven't seen your code, but I think you could build a CustomFooter in SmartRefresher, such as
```
SmartRefresher(
                    header: const ClassicHeader(),
                    footer: CustomFooter(
                      builder: (context, mode) {
                          if(mode == LoadStatus.noMore){
                                 return const SizedBox.shrink();
                           } else{
                                 return Text('blah');
                           }                        
                      },
                    ),
```

**Comment by peng8350** [comment]
```dart
      enablePullUp:_controller.footerStatus!=LoadStatus.nomore,

```
