### ISSUE TITLE
Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'

### ISSUE THREAD

**Issue by wulongcd** [peng8350/flutter_pulltorefresh#417]
新版本的sdk报错：
"pull_to_refresh-1.6.3/lib/src/smart_refresher.dart:273:21: Error: The method 'ancestorWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../flutter/packages/flutter/lib/src/widgets/framework.dart').

**Comment by aktxyz** [comment]
+1

**Comment by vbabaria** [comment]
running into same error and tried downgrading package with no luck, would appreciate any update - thanks

**Comment by daveMcelf** [comment]
I also had this problem and make a pull request to quick fix that problem too. You can check it here. #419

**Comment by a7mdragab** [comment]
+1
