### ISSUE TITLE
SmartRefresher with CustomScrollView

### ISSUE THREAD

**Issue by alyyasser** [peng8350/flutter_pulltorefresh#421]
when using CustomScrollView as SmartRefresher's child, is there a way to make pull-to-refresh header appear after SliverAppBar inside the CustomScrollView? (currently, my pull-to-refresh header appear on top/after of SliverAppBar).

**Comment by peng8350** [comment]
I think you can try NestedScrollView(with SliverAppBar header) + SmartRefresher + CustomScrollView

**Comment by kaciula** [comment]
@alyyasser Did you manage to find a solution to show the pull-to-refresh header after the SliverAppBar? I've tried the NestedScrollView approach but it did not work.

**Comment by alyyasser** [comment]
@kaciula sadly, no. i ended up not using SmartRefresher and making my own implementation specific to my use-case. i only need the in-progress/loading view, and our designer agreed to remove the pull-to-refresh from layout's design completely.
