### ISSUE TITLE
An error is reported after flutter update

### ISSUE THREAD

**Issue by ModWU** [peng8350/flutter_pulltorefresh#422]
![图片](https://user-images.githubusercontent.com/16234264/104693613-ed909400-5744-11eb-9fc5-489a3d135687.png)
![图片](https://user-images.githubusercontent.com/16234264/104693684-08fb9f00-5745-11eb-9d44-932d4fa23d54.png)

This 'ancestorWidgetOfExactType(Widget)’ function cannot be found in the BuildContext class

**Comment by a7mdragab** [comment]
+1

**Comment by tianketianke** [comment]
I have the same problem as you .

**Comment by Jbz797** [comment]
+1
