### ISSUE TITLE
In iOS, Exception caught by scheduler library

### ISSUE THREAD

**Issue by tree1891** [peng8350/flutter_pulltorefresh#423]
It occurs when refresh by pull down and finish, keep showing "Refresh completed" and part under smartrefresher does not response.

```
════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 789 pos 12: 'elapsedInSeconds >= 0.0': is not true.
════════════════════════════════════════════════════════════════════════════════
```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64,
locale en-KR)
• Flutter version 1.22.5 at /Users/***/flutter
• Framework revision 7891006 (6 weeks ago), 2020-12-10 11:54:40 -0800
• Engine revision ae90085a84
• Dart version 2.10.4

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.3, Build version 12C33
• CocoaPods version 1.9.2

**Comment by peng8350** [comment]
there is no exception logs pointing to this library,I don't think this caused by this library,If you sure it is this library problem,please give more details.Firstly,how to trigger this exception?Secondly,more exception information.
