### ISSUE TITLE
App is not built using new version 1.6.4

### ISSUE THREAD

**Issue by sergey-regotun** [peng8350/flutter_pulltorefresh#424]
Trying to build a flutter app using new version of the library 1.6.4. Logs when building:

```
[+18456 ms] ../../../../../../.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
[        ]         keyboardDismissBehavior:
[        ]         ^^^^^^^^^^^^^^^^^^^^^^^
[        ] ../../../../flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
[        ]   const CustomScrollView({
[        ]         ^^^^^^^^^^^^^^^^
[+8058 ms] ../../../../../../.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
[   +2 ms]         keyboardDismissBehavior:
[        ]         ^^^^^^^^^^^^^^^^^^^^^^^
[        ] ../../../../flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
[        ]   const CustomScrollView({
[        ]         ^^^^^^^^^^^^^^^^
[+9585 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/sergey/Projects/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/sergey/Projects/Flutter/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 38s
[{"event":"app.progress","params":{"appId":"13afa2cc-8a69-46e0-b928-0536b88bb6f7","id":"0","progressId":null,"finished":true}}]
[ +481 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:474:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

It seems the error is in smart_refresher.dart file on 434 line, "No named parameter with the name 'keyboardDismissBehavior'" for **CustomScrollView** widget.

**Comment by peng8350** [comment]
keyboardDismissBehavior parameter added in Sept 2020.You can update flutter sdk to the newest vevrsion. I am not sure stable version  work,but dev version must work

**Comment by Lloyd666** [comment]
same issue.

**Comment by peng8350** [comment]
My mistake,the newest stable version not contain keyboardDismissBehavior in CustomScrollView,wait for the next version publish in stable channel and this error will disappear

**Comment by peng8350** [comment]
If you use flutter stable version,you can continue use 1.6.3,because 1.6.4 is only for fix the error crash in dev version when flutter remove some functions.

**Comment by XutongGithub** [comment]
same issue.
In the stable version can not work.
flutter doctor 
Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-CN).

**Comment by Jacky-Xu** [comment]
downgrade 1.6.3, still can't work

**Comment by Lloyd666** [comment]
It seems like the problem with the cache.
After downgrading and running 'flutter pub get'. 
Both `flutter clean` and `File -> Invalidate cache` didn't work.
I still got the error:
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../../development/flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
  const CustomScrollView({
        ^^^^^^^^^^^^^^^^

**Comment by Jacky-Xu** [comment]
../../../../Library/Flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.3/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../../Library/Flutter/flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
  const CustomScrollView({
        ^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:

**Comment by juanlabrador** [comment]
Me too, few minutes ago

**Comment by juanlabrador** [comment]
I force   pull_to_refresh: '1.6.1' and works.

**Comment by darkThanBlack** [comment]
**Env**
Flutter 1.22.4
Tools • Dart 2.10.4

**Error**
```
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:
        ^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
  const CustomScrollView({
        ^^^^^^^^^^^^^^^^
```

**REASON**
Cause in Flutte codes,  ``CustomScrollView`` not exist ``keyboardDismissBehavior`` property.

**ANSWER**
1. update to newest Flutter version ;
2. set pull_to_refersh version to 1.6.3 or early.

**Comment by Jacky-Xu** [comment]
@juanlabrador  but, error occured:  'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.

**Comment by Jacky-Xu** [comment]
@darkThanBlack  set pull_to_refersh version to 1.6.3 also the error

**Comment by Jacky-Xu** [comment]
![image](https://user-images.githubusercontent.com/10206252/105125872-66626800-5b18-11eb-8e38-8587f8854412.png)
 already is newest Flutter version!!!

**Comment by peng8350** [comment]
@Jacky-Xu you clear your pull_to_refresh pub cache and pub upgrade 

```dart

 pull_to_refresh: 1.6.3

```

**Comment by Jacky-Xu** [comment]
problem solved:
 1.delete  'pull_to_refresh-1.6.3' folder
 2.pull_to_refresh: 1.6.3 and pub packages get

**Comment by wl386123298** [comment]
my solved:
1.run flutter clean
2. use pull_to_refresh:1.6.3
3. pub upgrade

**Comment by Pluto1219** [comment]
For those of you who still report errors after the downgrade, please find pull_to_refresh in pubspec.lock and change version to 1.6.3.

**Comment by Lloyd666** [comment]
@Pluto1219 It works, thank you.

**Comment by pradyotMobifyi** [comment]
> downgrade 1.6.3, still can't work

pull_to_refresh: 1.6.3

Use version without ^. This fixed for me.

**Comment by wlong800** [comment]
my solved:
1. open /Users/wanglong/.pub-cache/hosted/mirrors.cloud.tencent.com%47dart-pub/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart
2. delete  keyboardDismissBehavior

**Comment by sm9i** [comment]
https://github.com/peng8350/flutter_pulltorefresh/blob/master/lib/src/smart_refresher.dart#L434

**Comment by ahmedGibran** [comment]
> For those of you who still report errors after the downgrade, please find pull_to_refresh in pubspec.lock and change version to 1.6.3

Thanks it works

**Comment by peng8350** [comment]
Now,you can update flutter sdk to 2.0.0 and use ^1.6.4 for stable version.

**Comment by ultronnet** [comment]
> Now,you can update flutter sdk to 2.0.0 and use ^1.6.4 for stable version.

it's not a solution, you have to set min flutter SDK requirement to 2.0 in your pubspec.yaml file
you'd better not announce that it supports flutter 1.0, actually it's not.

**Comment by mhammedkh20** [comment]
I found the solution
 You just have to delete the scrollBehavior feature completely so that you search for the feature and delete it Via C:/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.3.8/lib/get_navigation/src/root/get_material_app.dart
