### ISSUE TITLE
Flutter 1.22.5 • channel stable ，1.6.4版本编译报错，

### ISSUE THREAD

**Issue by liuweilyy** [peng8350/flutter_pulltorefresh#425]
Flutter 1.22.5 • channel stable ，
flutter_pulltorefresh 1.6.4
CustomScrollView中的这个属性keyboardDismissBehavior找不到，CustomScrollView没有对外开放这个属性，只有ScrollView有这个属性

下面是报错的信息
```
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:
        ^^^^^^^^^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
  const CustomScrollView({
        ^^^^^^^^^^^^^^^^
```

**Comment by kevin406972552** [comment]
把库源码smart_refresher.dart 文件里面 _buildBodyBySlivers函数里面的CustomScrollView 参数keyboardDismissBehavior 注释掉就可以了

**Comment by liuweilyy** [comment]
> 把库源码smart_refresher.dart 文件里面 _buildBodyBySlivers函数里面的CustomScrollView 参数keyboardDismissBehavior 注释掉就可以了

嗯，我退回旧版本了。只不过说下版本有的问题，不然全升到1.6.4的版本都运行不了，

**Comment by zhangchunbin** [comment]
Flutter 1.22.5 我也遇到这个问题，突然项目就没法编译了.退回1.6.1也不行。只能编译源码删除keyboardDismissBehavior参数
