### ISSUE TITLE
Error: No named parameter with the name 'keyboardDismissBehavior'.

### ISSUE THREAD

**Issue by AnadaYuKi** [peng8350/flutter_pulltorefresh#427]
when use “flutter build ios --release --no-codesign” , it will throw a error message "Error: No named parameter with the name 'keyboardDismissBehavior'."

**Comment by zakaio** [comment]
Same for the android debug build. Appeared suddenly.

**Comment by zakaio** [comment]
started from 1.6.4, 
use pull_to_refresh: 1.6.3 without ^ for fast fix

**Comment by surpriso1997** [comment]
@zakaio  same issue in 1.6.3 in ios

**Comment by goo2018** [comment]
> started from 1.6.4,
> use pull_to_refresh: 1.6.3 without ^ for fast fix

but:
```The following assertion was thrown:
    A ScrollPositionWithSingleContext was used after being disposed.
    Once you have called dispose() on a
    ScrollPositionWithSingleContext, it can no longer be used.
    
    When the exception was thrown, this was the stack:
    #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
    #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
    #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
    #3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:889:11)
    #4      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:367:5)
    #5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/s
```

**Comment by felixgabler** [comment]
copy of #424 . Look for solutions there. It supposedly is due to incompatibility with flutter changes. 1.6.4 will work with the next stable release of the flutter sdk. Until then, use 1.6.3.

**Comment by hejunbinlan** [comment]
../lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
也碰到同样的问题

**Comment by flutterq** [comment]
[[Solved] Error: No named parameter with the name ‘keyboardDismissBehavior’](https://fluttercorner.com/flutter-run-error-no-named-parameter-with-the-name-keyboarddismissbehavior/)

**Comment by shinewanna** [comment]
> > started from 1.6.4,
> > use pull_to_refresh: 1.6.3 without ^ for fast fix
> 
> but:
> 
> ```
>     A ScrollPositionWithSingleContext was used after being disposed.
>     Once you have called dispose() on a
>     ScrollPositionWithSingleContext, it can no longer be used.
>     
>     When the exception was thrown, this was the stack:
>     #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
>     #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
>     #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
>     #3      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:889:11)
>     #4      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:367:5)
>     #5      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/s
> ```

How you solved this on i'm facing on this?@goo2018

**Comment by jeromekai** [comment]
v1.6.4 发现问题
./flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:                                        
        ^^^^^^^^^^^^^^^^^^^^^^^                                         
../../../flutter/packages/flutter/lib/src/widgets/scroll_view.dart:588:9: Context: Found this candidate, but the arguments don't match.
  const CustomScrollView({  

请问为修复了吗？

**Comment by ramsthapit** [comment]
use pull_to_refresh: 1.6.3
