### ISSUE TITLE
Useless files such as demo.apk and images

### ISSUE THREAD

**Issue by dm8tr** [peng8350/flutter_pulltorefresh#428]
Hello,
Is there any interest of putting the whole project files into the package download folder ?
We can notice the demo.apk file and lot of heavy image files. 
Since we can download the demo app and see related images from your package home page, any reason to put them in package download folder ?
 We do not need these files locally and their uselessly increase download size

**Comment by peng8350** [comment]
these files is not useless,they need to be displayed in README.If you have good advice,you can tell me.

**Comment by peng8350** [comment]
As you wish,apk has been deleted
