### ISSUE TITLE
更新完flutter最新版本，打包报错

### ISSUE THREAD

**Issue by 136759790** [peng8350/flutter_pulltorefresh#434]
`../../../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:`
需要回退到1.6.3才能解决

**Comment by kinling** [comment]
+1

**Comment by yenyichau** [comment]
+2

**Comment by Wing-Li** [comment]
+1

**Comment by titanseason** [comment]
The same build error with flutter 1.22.6

**Comment by 254929739** [comment]
+1

**Comment by inshyma** [comment]
+1

**Comment by 495073309** [comment]
+1

**Comment by chengdeccw** [comment]
+1

**Comment by peng8350** [comment]
Duplicate #424,If your flutter version is >=2.0.0,use >= 1.6.4.Otherwise use 1.6.3
