### ISSUE TITLE
Error: No named parameter with the name 'keyboardDismissBehavior'.

### ISSUE THREAD

**Issue by kawache** [peng8350/flutter_pulltorefresh#437]
https://github.com/peng8350/flutter_pulltorefresh/blob/75f05219af3734690e1b7cfbdafe4f8d083d3ac6/lib/src/smart_refresher.dart#L434

 Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:ScrollViewKeyboardDismissBehavior.manual,
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../../Applications/flutter/packages/flutter/lib/src/widgets/scroll_view.dart#588 Context: Found this candidate, but the arguments don't match.
  const CustomScrollView({
        ^^^^^^^^^^^^^^^^

**Comment by micer** [comment]
I have the same issue, how did you fix it?

**Comment by micer** [comment]
Found the fix, for others: https://stackoverflow.com/questions/65838381/flutter-run-error-no-named-parameter-with-the-name-keyboarddismissbehavior.

**Comment by CoderJohnhao** [comment]
Download 1.6.3, change the folder name to 1.6.4, and then go to ../flutter/.pub-cache/hosted/pub.dartlang.org to replace 1.6.4.
