### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HosseinAsadi** [peng8350/flutter_pulltorefresh#440]
hi please fix this bug for new version

/G:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.6.4/lib/src/smart_refresher.dart:434:9: Error: No named parameter with the name 'keyboardDismissBehavior'.
        keyboardDismissBehavior:
        ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by yasfdany** [comment]
Same here

**Comment by HosseinAsadi** [comment]
> Same here

So what do you say we do now?
The developer is not responsive !?

**Comment by furkansarihan** [comment]
https://github.com/peng8350/flutter_pulltorefresh/pull/442

**Comment by MelonWXD** [comment]
use version 1.6.3

**Comment by Oklahomawhore** [comment]
what is happenning

**Comment by Oklahomawhore** [comment]
+1

**Comment by peng8350** [comment]
Duplicate #424,If your flutter version is >=2.0.0,use >= 1.6.4.Otherwise use 1.6.3
