### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by pablo-johnson** [peng8350/flutter_pulltorefresh#443]
Hello,
Is there any plan to support null safety?

**Comment by jheimes-silveira** [comment]
I have the same problem, I need support

**Comment by fzyzcjy** [comment]
related: https://github.com/peng8350/flutter_pulltorefresh/issues/448

**Comment by fzyzcjy** [comment]
PR https://github.com/peng8350/flutter_pulltorefresh/pull/452
