### ISSUE TITLE
add null-safety support

### ISSUE THREAD

**Issue by chavesgu** [peng8350/flutter_pulltorefresh#448]
flutter stable version is `2.0.0`

**Comment by fzyzcjy** [comment]
any updates?

**Comment by kuromukira** [comment]
👀

**Comment by fzyzcjy** [comment]
if I make a PR will it be accepted?

**Comment by fzyzcjy** [comment]
PR https://github.com/peng8350/flutter_pulltorefresh/pull/452

**Comment by andoutica** [comment]
any updates? 
I received a error because of pull_to_refresh package.

```
Error: Cannot run with sound null safety, because the following dependencies don't support null safety:
     - package:pull_to_refresh

```

**Comment by kuromukira** [comment]
PR has been merged but not yet uploaded in pub. Can we get an ETA? Thanks.
