### ISSUE TITLE
页面快速rebuild时会报错

### ISSUE THREAD

**Issue by ykrank** [peng8350/flutter_pulltorefresh#453]
'''
I/flutter (12582): This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
I/flutter (12582): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
I/flutter (12582): #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:1088:9)
I/flutter (12582): #1      State.context (package:flutter/src/widgets/framework.dart:1094:6)
I/flutter (12582): #2      ScrollableState.storageContext (package:flutter/src/widgets/scrollable.dart:574:38)
I/flutter (12582): #3      RefreshController.requestRefresh.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:pull_to_refresh/src/smart_refresher.dart:687:53)
I/flutter (12582): #4      _rootRunUnary (dart:async/zone.dart:1362:47)
I/flutter (12582): #5      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
I/flutter (12582): #6      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
I/flutter (12582): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
I/flutter (12582): #8      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
I/flutter (12582): #9      Future._completeWithValue (dart:async/future_impl.dart:539:5)
I/flutter (12582): #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
'''
原因是延时操作结束后context已经被unmount。加一个判断即可。

**Comment by peng8350** [comment]
2.0.0已修复
