### ISSUE TITLE
Any plan to support GridView?

### ISSUE THREAD

**Issue by kechankrisna** [peng8350/flutter_pulltorefresh#454]
I would be so appreciate if this plugin can work great with GridView

**Comment by eason4best** [comment]
Actually it can.

**Comment by kechankrisna** [comment]
I run it on ios and android, it is working great but when I try it on desktop support, what i can see when scoll to bottom is loading failed gesture detecture.

**Comment by peng8350** [comment]
GridView is supported,If you are sure GridView is not work,please attach more details
