### ISSUE TITLE
数据不满一屏，底部仍然显示‘上拉加载’

### ISSUE THREAD

**Issue by duaiyun1314** [peng8350/flutter_pulltorefresh#456]
我怀疑是作者在判断数据不满一屏时的逻辑有问题，如果列表底部剩余空间大于footer的高度，是正常的；如果剩余空间小于footer的高度不论我怎么设置，好像都不走数据不满一屏的逻辑了。
![20210315110534](https://user-images.githubusercontent.com/6456552/111098472-80e81900-857e-11eb-90fa-3cde8ee7b277.jpg)

![image](https://user-images.githubusercontent.com/6456552/111098533-a6752280-857e-11eb-94e1-e4a1923a74a8.png)

**Comment by peng8350** [comment]
1.6.5 has fixed
