### ISSUE TITLE
onLoading and onRefresh not triggered on MacOS

### ISSUE THREAD

**Issue by subhash279** [peng8350/flutter_pulltorefresh#459]
Hi,
First of all, thanks for this plugin. It works perfectly on Android and iOS. I then used the same code to test on MacOS and both `onLoading` and `onRefresh` are not triggered when I scroll to the end. But if I pull the screen area up/down near the edge using my cursor, it works again. Just that the usual scroll doesn't trigger it.

Is it because of the way scrolling works on MacOS compared to touch screen iOS and Android. Does the plugin support MacOS already and do I have to change any parameters for it to work.

**Comment by peng8350** [comment]
I have not tested it on MacOS,but Web can work.May be you can stackoverflow,and you will find the answer quickly.
