### ISSUE TITLE
How to remove animation with enableBallisticRefresh=false?

### ISSUE THREAD

**Issue by themadmrj** [peng8350/flutter_pulltorefresh#460]
When setting enableBallisticRefresh: false (which is the default), as expected, no refresh is triggered when scrolling up. However, the refresh animation is still visible. How can I only start the refresh animation when the drag/fling gesture was started when the scroll was at position 0?

**Comment by peng8350** [comment]
I think you misunderstand enableBallisticRefresh prop,I guess your request is that you need set  physics to ClampingScrollPhysics.

**Comment by themadmrj** [comment]
> I think you misunderstand enableBallisticRefresh prop,I guess your request is that you need set physics to ClampingScrollPhysics.

Nope.  Here's a video to demonstrate the current behaviour. As you can see, with a quick fling, i scroll all the way to the top of the list and then the refresh animation is triggered. With `enableBallisticRefresh: true`, this with also trigger the refresh callback. In both cases, whether the callback is called or not, the animation still happens. I want to prevent the fling from triggering the animation, unless the scroll index is at 0 (meaning at the very top).


https://user-images.githubusercontent.com/11475495/114406010-7897f380-9ba7-11eb-91e8-400d422fb26a.mov

**Comment by peng8350** [comment]
If you use NestedScrollView,I must say there is no way to solve.Because the overScroll behaviour is controlled by NestedScrollView instead of CustomScrollView.This library is not very compatible with Nestedscrollview.

**Comment by themadmrj** [comment]
That is indeed the case.
Any idea where I have to start to make it happen? Where do I have to look inside of `NestedScrollView`?

**Comment by peng8350** [comment]
The only way is to modify the NestedScrollView ,make it support ClampingScrollPhysics(Android Behaviour) for inner ScrollView.

**Comment by themadmrj** [comment]
I don't understand...
This is the `NestedScrollViewState`:

  ```
@override
  Widget build(BuildContext context) {
    return _InheritedNestedScrollView(
      state: this,
      child: Builder(
        builder: (BuildContext context) {
          _lastHasScrolledBody = _coordinator!.hasScrolledBody;
          return _NestedScrollViewCustomScrollView(
            dragStartBehavior: widget.dragStartBehavior,
            scrollDirection: widget.scrollDirection,
            reverse: widget.reverse,
            physics: widget.physics != null
              ? widget.physics!.applyTo(const ClampingScrollPhysics())
              : const ClampingScrollPhysics(),
            controller: _coordinator!._outerController,
            slivers: widget._buildSlivers(
              context,
              _coordinator!._innerController,
              _lastHasScrolledBody!,
            ),
            handle: _absorberHandle,
            clipBehavior: widget.clipBehavior,
            restorationId: widget.restorationId,
          );
        },
      ),
    );
  }
```

And `_NestedScrollViewCustomScrollView` extends `CustomScrollView`, so I don't get where the problem is?

**Comment by peng8350** [comment]
I've said: I'm not responsible for maintaining NestedScrollView,and I don't know more about NestedScrollView.Only you can do is that give flutter issue and tell them to support custom inner ScrollView physics when fliping from not out of edge. Same issue #400.

**Comment by peng8350** [comment]
It has been determined that there is a logic problem in my ScrollPhysics, not  NestedScrollView fault

**Comment by themadmrj** [comment]
> It has been determined that there is a logic problem in my ScrollPhysics, not NestedScrollView fault

Does this mean you will implement a fix? That would be awesome :)

**Comment by peng8350** [comment]
2.0.0 has fixed this
