### ISSUE TITLE
Add Null safe version

### ISSUE THREAD

**Issue by zhaopingfu** [peng8350/flutter_pulltorefresh#461]
After Flutter is upgraded to `2.0.2`, it needs to support `null safety`. 

Currently version `1.6.4` does not support `null safety`. 

Please support `null safety`. 

Thank you.

**Comment by onlyYU** [comment]
+1

**Comment by DasTobbel** [comment]
Duplicate of #452

**Comment by DogHank** [comment]
+1

**Comment by birhos** [comment]
+1

**Comment by zhaopingfu** [comment]
`pull_to_refresh: 1.6.4-nullsafety.0` can be use.

**Comment by kuromukira** [comment]
`-nullsafety.0` does not work yet

**Comment by zhaopingfu** [comment]
> `-nullsafety.0` does not work yet

use `1.6.4-nullsafety.0`, don\`t use `^1.6.4-nullsafety.0`
