### ISSUE TITLE
null-safety 什么时候发布呢？

### ISSUE THREAD

**Issue by lionnner** [peng8350/flutter_pulltorefresh#467]

**Comment by itmediacreations** [comment]
Already in another branch, use:

`pull_to_refresh: 1.6.4-nullsafety.0` in pubspec.yaml

**Comment by lionnner** [comment]
> Already in another branch, use:
> 
> `pull_to_refresh: 1.6.4-nullsafety.0` in pubspec.yaml

not working
pull_to_refresh  ✗1.6.4   ✗1.6.4      ✗1.6.4      ✗1.6.4

**Comment by itmediacreations** [comment]
> > Already in another branch, use:
> > `pull_to_refresh: 1.6.4-nullsafety.0` in pubspec.yaml
> 
> not working
> pull_to_refresh ✗1.6.4 ✗1.6.4 ✗1.6.4 ✗1.6.4

Are you using `^` sign before `1.6.4` ?
