### ISSUE TITLE
header 会显示出10dp。在没有刷新或者刷新结束后，header（loading 显示区域）会溢出到视觉范围。

### ISSUE THREAD

**Issue by wilin52** [peng8350/flutter_pulltorefresh#47]
在没有刷新或者刷新结束后，header（loading 显示区域）会溢出到视觉范围。
原因是default_height = 50， 而如果没有设置ClassicIndicator 里的height， height 默认为60.  
SmartRefresher 在build 时候会将 ScrollView 上移 default_height。 那么视觉范围内就会有60 - 50 = 10 的大小区域。

解决这个问题：
1. 将ClassicIndicator height 默认值改回50；
2. 使用者每次使用的时候，设置height 为 50；

**Comment by benoitjadinon** [comment]
I've quick-fixed it with ```headerConfig: RefreshConfig(height:60, ),``` but it's weird

**Comment by peng8350** [comment]
@benoitjadinon no,just my forgot!
