### ISSUE TITLE
Migration to null safety.

### ISSUE THREAD

**Issue by mrdemqn** [peng8350/flutter_pulltorefresh#470]
Hi!

I ran into a problem with the migration of my project to Null Safety Sound. Since the plugin does not support zero security.

Please tell me if plans for the migration of the plugin?

**Comment by leonalonso** [comment]
Same here! The only one is to find alternative ways, until they migrate.

**Comment by andoutica** [comment]
this lib supported null-safety, but it seem like the owner have not still update on pub.dev yet. 
use this on your pubspec 
```pull_to_refresh: 1.6.4-nullsafety.0```

**Comment by mrdemqn** [comment]
> this lib supported null-safety, but it seem like the owner have not still updated on pub.dev yet.
> use this on your pubspec
> `pull_to_refresh: 1.6.4-nullsafety.0`
Thank you very much for the information. It helped me a lot.
