### ISSUE TITLE
[Minor suggestion] in onRefresh callback provide a boolean flag to indicate the action was triggered by user or by controller.requestRefresh()

### ISSUE THREAD

**Issue by iulian0512** [peng8350/flutter_pulltorefresh#471]
Thanks for providing us with this wonderful control.

**Comment by peng8350** [comment]
In fact, it is difficult to judge whether it is triggered by the user dragging or requestRefresh()

**Comment by peng8350** [comment]
I must say that this request is hard.Adding a paramter to check onRefresh triggered by user is necessary.But this is a big breaking change.it will cause everyone to update onRefresh callback function.I have no idea how not to make  breaking change.

**Comment by peng8350** [comment]
2.0.0 has been added this request,you can use _refreshController.requestRefresh(needCallback:false).then(...).the more details you can check Test3.dart
