### ISSUE TITLE
headerMode is nullable

### ISSUE THREAD

**Issue by NarHakobyan** [peng8350/flutter_pulltorefresh#473]
Why headerMode is nullable?

```dart
  /// header status mode controll
  ValueNotifier<RefreshStatus>? headerMode;

```

**Comment by peng8350** [comment]
this has been fixed

**Comment by peng8350** [comment]
Reverted,this crash error after not nullable.Why headerMode is nullable?Because it need to detect the headerMode is mounted or unmount,they didn't provide bool to check it,so I have no idea how to do,only I can do is that make headerMode = null to check this is unmount state.
