### ISSUE TITLE
Compatibility with ListView

### ISSUE THREAD

**Issue by cianiandreadev** [peng8350/flutter_pulltorefresh#48]
I'm using the version 1.2.0 and when I try to assign the ListView as Child of the SmartRefresher it says that the ListView is not type ScrollView.

From the example written in the README is instead shown that I'm doing correctly.

How can implement that?

Sorry, it may be a simple trick but I'm new to Flutter. :)

**Comment by peng8350** [comment]
I don't understand why ListView is not a subclass of ScrollView. It may be a problem with your flutter version.

**Comment by cianiandreadev** [comment]
@peng8350 you are right. My fault. I messed up some settings. :)
