### ISSUE TITLE
RefreshIndicator shows forever

### ISSUE THREAD

**Issue by narakai** [peng8350/flutter_pulltorefresh#49]
你好，

请问_controller.sendBack(false, event.status); 这里我设置了返回idle的status，但是RefreshIndicator仍然一直显示，可能是什么问题？大概是这样的：

new RefreshIndicator(
              child: SmartRefresher(
                controller: _controller,
                enablePullDown: false,
                enablePullUp: false,
                enableOverScroll: false,
                child: new ListView.builder(
                  itemCount: snapshot.data == null ? 0 : snapshot.data.length,
                  itemBuilder: (BuildContext context, int index) {
                    MovieModel model = snapshot.data[index];
                    return new ReposItem(model);
                  },
                ),
              ),
              onRefresh: () {
                bloc.onRefresh(labelId: labelId);
              },
            ),

**Comment by peng8350** [comment]
RefreshIndicator是flutter那边提供的,你调用_controller.sendBack(false, event.status)只能对我内部顶部指示器操作,而不是对RefreshIndicator,example4里面有例子

**Comment by narakai** [comment]
好的，谢谢解答
