### ISSUE TITLE
Don't use one refreshController to multiple SmartRefresher,It will cause some unexpected bugs mostly in TabBarView

### ISSUE THREAD

**Issue by jahnli** [peng8350/flutter_pulltorefresh#491]
Don't use one refreshController to multiple SmartRefresher,It
will cause some unexpected bugs mostly in TabBarView
package:pull_to_refresh/src/smart_refresher.dart':

![image](https://user-images.githubusercontent.com/20943608/121458873-c466ed80-c9dc-11eb-8629-d76bd8264273.png)
![image](https://user-images.githubusercontent.com/20943608/121458882-c761de00-c9dc-11eb-9d94-7dbadd58df6f.png)

**Comment by olyshchuk** [comment]
Same, please help @peng8350

**Comment by CatEatFishs** [comment]
I have the same problem

**Comment by dinhthi147** [comment]
+1 here

**Comment by CatEatFishs** [comment]
I have the same problem but I solved it。
are you using GetController ？ i am using GetController ，please Destroy the GetController when you exit the page，make sure only one GetController

**Comment by jahnli** [comment]
是的，请问可以留个联系方式 ？

**Comment by jahnli** [comment]
@CatEatFishs   是GetController ，请问可以留个联系方式吗？

**Comment by jahnli** [comment]
@CatEatFishs   请问是如何解决的，可以贴个代码 ？

**Comment by ehsanbigzad** [comment]
In GetX state management i solved the issue by the following method:

```dart
class PostController extends GetxController {

  RefreshController refreshController;

  @override
  void onReady() {
    refreshController = new RefreshController();
    super.onReady();
  }

}
```

**Comment by jahnli** [comment]
OK，thanks @ehsanbigzad

**Comment by Jvaeyhcd** [comment]
@jahnli Have you solved the problem?

**Comment by jahnli** [comment]
@Jvaeyhcd   I haven't had time to try it yet, you can refer to the scheme upstairs to see if it is feasible    ，If possible, please let me know

**Comment by chunhtp** [comment]
I am facing the same issue right now , I think because of i using bottomNavigationBar
The scheme upstairs seem not solving the issue. 
Anyone got better solution ?

**Comment by Jvaeyhcd** [comment]
When i build SmartRefresher, i create the RefreshController. Then the problem will be solved.
``` dart
Widget buildView(
    PullRefreshState state, Dispatch dispatch, ViewService viewService) {
  state.refreshController = RefreshController();
  return NotificationListener<ScrollStartNotification>(
    child: SmartRefresher(
        enablePullDown: true,
        enablePullUp: state.enablePullUp,
        onRefresh: () {
          dispatch(PullRefreshActionCreator.onPullRefresh(true));
        },
        onLoading: () {
          dispatch(PullRefreshActionCreator.onPullRefresh(false));
        },
        controller: state.refreshController,
        child: ListView.builder(
          shrinkWrap: true,
          itemBuilder: state.itemBuilder,
          itemCount: state.dataList.length,
        )),
    onNotification: (ScrollStartNotification notification) {
      KeyboardUtil.hideKeyboard(viewService.context);
      return false;
    },
  );
}
```

**Comment by chunhtp** [comment]
> When i build SmartRefresher, i create the RefreshController. Then the problem will be solved.
> 
> ```dart
> Widget buildView(
>     PullRefreshState state, Dispatch dispatch, ViewService viewService) {
>   state.refreshController = RefreshController();
>   return NotificationListener<ScrollStartNotification>(
>     child: SmartRefresher(
>         enablePullDown: true,
>         enablePullUp: state.enablePullUp,
>         onRefresh: () {
>           dispatch(PullRefreshActionCreator.onPullRefresh(true));
>         },
>         onLoading: () {
>           dispatch(PullRefreshActionCreator.onPullRefresh(false));
>         },
>         controller: state.refreshController,
>         child: ListView.builder(
>           shrinkWrap: true,
>           itemBuilder: state.itemBuilder,
>           itemCount: state.dataList.length,
>         )),
>     onNotification: (ScrollStartNotification notification) {
>       KeyboardUtil.hideKeyboard(viewService.context);
>       return false;
>     },
>   );
> }
> ```

Yes , i solved it with initial the controller inside the smart refresher as well

**Comment by alan-biao** [comment]
这是因为GetX复用controller的问题导致的，Get.put加个tag和GetBuilder加个tag就能解决

**Comment by mehrzut** [comment]
> I have the same problem but I solved it。 are you using GetController ？ i am using GetController ，please Destroy the GetController when you exit the page，make sure only one GetController

It actually gave me the idea. That happens because I need the GetController and can't dispose it when the page is built again the RefreshController is the same but the widget is a new one. I moved the RefreshController from GetController to Stateless class and it worked. Thanks.

**Comment by Jiju-keyvalue** [comment]
> > When i build SmartRefresher, i create the RefreshController. Then the problem will be solved.
> > ```dart
> > Widget buildView(
> >     PullRefreshState state, Dispatch dispatch, ViewService viewService) {
> >   state.refreshController = RefreshController();
> >   return NotificationListener<ScrollStartNotification>(
> >     child: SmartRefresher(
> >         enablePullDown: true,
> >         enablePullUp: state.enablePullUp,
> >         onRefresh: () {
> >           dispatch(PullRefreshActionCreator.onPullRefresh(true));
> >         },
> >         onLoading: () {
> >           dispatch(PullRefreshActionCreator.onPullRefresh(false));
> >         },
> >         controller: state.refreshController,
> >         child: ListView.builder(
> >           shrinkWrap: true,
> >           itemBuilder: state.itemBuilder,
> >           itemCount: state.dataList.length,
> >         )),
> >     onNotification: (ScrollStartNotification notification) {
> >       KeyboardUtil.hideKeyboard(viewService.context);
> >       return false;
> >     },
> >   );
> > }
> > ```
> 
> Yes , i solved it with initializing the refreshcontroller inside the smart refresher as well for GetController

**Comment by OrageKK** [comment]
> 这是因为GetX复用controller的问题导向的，Get.put加个tag和GetBuilder加个tag就可以解决

贴个代码好吗,我加了tag,并没用,无法继续下拉

**Comment by dazeGitHub** [comment]
所以为什么 pull_to_refresh 要复用沙比 controller ????

**Comment by Asmewill** [comment]
> 这是因为GetX复用controller的问题导致的，Get.put加个tag和GetBuilder加个tag就能解决

可以贴个代码吗
