### ISSUE TITLE
I hope this will add value for it (Arabic language(ar))

### ISSUE THREAD

**Issue by Majd-AL-Shalash** [peng8350/flutter_pulltorefresh#492]
/// Arabic
class EnRefreshString implements RefreshString {
  @override
  String? canLoadingText = "حرر لتحميل المزيد";

  @override
  String? canRefreshText = "حرر للتحديث";

  @override
  String? canTwoLevelText = "حرر للدخول إلى الطابقة الثانية";

  @override
  String? idleLoadingText = "اسحب لتحميل المزيد";

  @override
  String? idleRefreshText = "اسحب للتحديث";

  @override
  String? loadFailedText = "فشل التحميل";

  @override
  String? loadingText = "جاري التحميل…";

  @override
  String? noMoreText = "لا مزيد من البيانات";

  @override
  String? refreshCompleteText = "اكتمل التحديث";

  @override
  String? refreshFailedText = "فشل التحديث";

  @override
  String? refreshingText = "جاري التحديث…";
}

**Comment by isa-sabbagh** [comment]
I add arabic translation by using CustomFooter like this :


class SmartFooter extends StatelessWidget {
  const SmartFooter({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CustomFooter(
      builder: (BuildContext context, LoadStatus? mode) {
        Widget body;
        if (mode == LoadStatus.idle) {
          body = const Text('أسحب للمزيد');
        } else if (mode == LoadStatus.loading) {
          body = const CircularProgressIndicator.adaptive();
        } else if (mode == LoadStatus.failed) {
          body = const Text('فشل التحميل ! أعد المحاولة');
        } else if (mode == LoadStatus.canLoading) {
          body = const Text('افلت لتحميل البيانات');
        } else {
          body = const Text('لا يوجد المزيد من البيانات');
        }
        return SizedBox(
          height: 55.0,
          child: Center(child: body),
        );
      },
    );
  }
}


class MainRefresher extends StatelessWidget {
  const MainRefresher({
    Key? key,
    required this.controller,
    required this.onRefresh,
    required this.onLoading,
    required this.child,
  }) : super(key: key);

  final RefreshController controller;
  final void Function()? onRefresh;
  final void Function()? onLoading;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return SmartRefresher(
        controller: controller,
        enablePullDown: true,
        enablePullUp: true,
        header: const WaterDropMaterialHeader(),
        footer: const SmartFooter(),
        onRefresh: onRefresh,
        onLoading: onLoading,
        cacheExtent: 10.0,
        physics: const AlwaysScrollableScrollPhysics(),
        child: child);
  }
}
