### ISSUE TITLE
当数据不足一页或者没数据时，如何让上拉加载组件不显示在页面上

### ISSUE THREAD

**Issue by wwangzhuang** [peng8350/flutter_pulltorefresh#5]
@peng8350 

类似这样 内容少的时候 怎么才能让上拉组件不显示

![h7qt 9e o2d c80exbb8lp4](https://user-images.githubusercontent.com/31605698/42433870-a30e31ae-8383-11e8-991f-7520cb7a0316.png)

**Comment by peng8350** [comment]
你可以给enablePullUp一个状态值的

**Comment by ginoz** [comment]
> 你可以给enablePullUp一个状态值的

如何给状态值呢。能详细说一下吗，build的时候给一个值之后，页面构建完如何去改enablePullUp呢
