### ISSUE TITLE
更新了1.2.0 之后怎么 监听 scrollcontrol  啊，为什么吧1.6.0 的 scrollcontrol搞成了私有

### ISSUE THREAD

**Issue by LZQL** [peng8350/flutter_pulltorefresh#51]
更新了1.2.0 之后怎么 监听 scrollcontrol  啊，为什么吧1.6.0 的 scrollcontrol搞成了私有，我需要添加监听

**Comment by LZQL** [comment]
我想 给这个 smartRefresh   添加一个  scrollcontrol 的 滚动监听，做一些自己的操作，比如标题栏跟随着 滚动来设置背景的透明度，然后把他们封装成一个 widget，怎么添加这个监听？以前1.6.0是可以添加的，

**Comment by peng8350** [comment]
在child里的ScrollView的controller设置

**Comment by peng8350** [comment]
1.3.0又重新设置为公有的了,因为指示器那边要利用它来算出offset
