### ISSUE TITLE
如果加载更多的时候 状态是RefreshStatus.failed  那我下次再滚到底部的时候怎么不会自动在去出发加载更多的方法

### ISSUE THREAD

**Issue by LZQL** [peng8350/flutter_pulltorefresh#52]
如果加载更多的时候 状态是RefreshStatus.failed  那我下次再滚到底部的时候怎么不会自动在去出发加载更多的网络请求，， 或者能否提供一下 点击   loadmore view 的点击事件，回调，然后我自己去调用加载更多的网络请求

**Comment by LZQL** [comment]
还有 一个需求就是，能否提供自定义修改 状态所对应的的 语言表达，比如 this.refreshingText: 'Refreshing...',  能否用户可以自定义内容为 正在加载更多

**Comment by peng8350** [comment]
前面的:提的不错,我有空修复一下,不过我看很多app一般没有上拉加载是没有显示success和failed的必要。后面的:没必要,直接在指示器外套一个GestureDetector

**Comment by peng8350** [comment]
在RefreshConfiguration里有个enableLoadingWhenFailed属性,打开就可以允许失败状态下通过上拉来触发加载更多
