### ISSUE TITLE
可能是手势引起的一个loadmore跳屏问题，是否有方法规避？

### ISSUE THREAD

**Issue by ldhlfzysys** [peng8350/flutter_pulltorefresh#523]
loadmore时，拉高一点，手不离开屏幕，当前cell会跳动到新数据的最后一条，并且再触发一次loadmore。

https://user-images.githubusercontent.com/7666564/130440003-c1221731-9c27-49f3-9e73-7926b20447bf.mp4

**Comment by ldhlfzysys** [comment]
用的提交问题时master分支版本。

**Comment by ldhlfzysys** [comment]
#19 看着和这个相似，但是看评论说解决了，我这仍然能复现

**Comment by ldhlfzysys** [comment]
#430 跳转问题看这个issue是官方问题，不知道有没有给官方提这个issue

**Comment by ldhlfzysys** [comment]
https://github.com/flutter/flutter/issues/89417  官方已经复现并接受了

**Comment by ldhlfzysys** [comment]
解决方案：
```

class MyScrollPhysics extends BouncingScrollPhysics {
  const MyScrollPhysics({ScrollPhysics parent}) : super(parent: parent);
  @override
  MyScrollPhysics applyTo(ScrollPhysics ancestor) {
    return MyScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  double adjustPositionForNewDimensions({
    ScrollMetrics oldPosition,
    ScrollMetrics newPosition,
    bool isScrolling,
    double velocity,
  }) {
    return newPosition.pixels;
  }
}
```
SmartRefresher(
physics: MyScrollPhysics()
)
```

```

**Comment by figbin** [comment]
人才啊，有一个 issue 是我提的，一直没解决，最近再关注下（其实早期flutter版本是没问题的）
楼主去官方提得这么详细，这个功能官方确实需要改进，太影响体验了，不知道接受了没有。
感谢楼主提出解决方案。
