### ISSUE TITLE
修改 enablePullDown 或者enablePullUp 会造成其child rebuild

### ISSUE THREAD

**Issue by AlanJN** [peng8350/flutter_pulltorefresh#525]
我使用provider selector  去修改SmartRefresher的 enablePullUp 和 enablePullDown ，并且SmartRefresher的child 也使用selector 包裹，selector的属性 shouldRebuild 写成固定的false ，child 是一个CustomScrollView，slivers包含 SliverToBoxAdapter，SliverFillRemaining，其中SliverFillRemaining里面包含一个PageView,每次我修改enablePullUp和enablePullDown，都会触发SliverToBoxAdapter和 SliverFillRemaining里面的组件rebuild 请问如何解决，辛苦

**Comment by iworkcloud** [comment]
请问有解决办法吗？
