### ISSUE TITLE
 Null check operator used on a null value

### ISSUE THREAD

**Issue by yanqibd** [peng8350/flutter_pulltorefresh#529]
The following _CastError was thrown while dispatching
notifications for ChangeNotifier:
Null check operator used on a null value
When the exception was thrown, this was the stack:
#0      FixedScrollMetrics.viewportDimension (package:flutter/src/widgets/scroll_metrics.dart:164)
#1      ScrollableState.storageContext (package:flutter/src/widgets/scrollable.dart:582)
#2      RefreshController.requestRefresh (package:pull_to_refresh/src/smart_refresher.dart:662)

**Comment by MsXam** [comment]
This issue is caused because you potentially have a Custom progress indicator that you use in this plugin. i.e you may have something like : 

`    
return SmartRefresher(
      enablePullDown: true,
      enablePullUp: false,

      header: CustomHeader(
          height: 120,
          refreshStyle: RefreshStyle.Follow,
          builder: (context, status) {
            return PullDownRefresh(
              color: ColorHelper.getSecondaryColourForTheme(),
            );
            switch (status) {
              case RefreshStatus.completed:
                return Refreshed(
                  color: ColorHelper.getSecondaryColourForTheme(),
                );
              case RefreshStatus.idle:
                return PullDownRefresh(
                  color: ColorHelper.getSecondaryColourForTheme(),
                );
              case RefreshStatus.canRefresh:
                return ReleaseToRefresh(
                  color: ColorHelper.getSecondaryColourForTheme(),
                );

              case RefreshStatus.refreshing:
                return Refreshing(
                  color: ColorHelper.getSecondaryColourForTheme(),
                );
              case RefreshStatus.failed:
                return RefreshFailed(
                  color: ColorHelper.getSecondaryColourForTheme(),
                );
              default:
                return Refreshing(
                  color: ColorHelper.getSecondaryColourForTheme(),
                );
            }
          }),
      controller: _refreshController,
      onRefresh: _onRefresh,
      onLoading: _onLoading,
      child: _buildRefreshIndicatorData(),
    );
` 

In my case, I have a **Custom Header** which returns different widgets based on the status of the ProgressIndicator. My custom widgets use **Expanded** - This will cause the issue that you are seeing - if you define a fixed size so that it is not unbounded then you will no longer see this issue.

So to **RESOLVE** ** restructure your custom header** to not use ANY expanded widgets.

**Comment by yanqibd** [comment]
> This issue is caused because you potentially have a Custom progress indicator that you use in this plugin. i.e you may have something like :
> 
> `
> return SmartRefresher(
> enablePullDown: true,
> enablePullUp: false,
> 
> ```
>   header: CustomHeader(
>       height: 120,
>       refreshStyle: RefreshStyle.Follow,
>       builder: (context, status) {
>         return PullDownRefresh(
>           color: ColorHelper.getSecondaryColourForTheme(),
>         );
>         switch (status) {
>           case RefreshStatus.completed:
>             return Refreshed(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           case RefreshStatus.idle:
>             return PullDownRefresh(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           case RefreshStatus.canRefresh:
>             return ReleaseToRefresh(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
> 
>           case RefreshStatus.refreshing:
>             return Refreshing(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           case RefreshStatus.failed:
>             return RefreshFailed(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           default:
>             return Refreshing(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>         }
>       }),
>   controller: _refreshController,
>   onRefresh: _onRefresh,
>   onLoading: _onLoading,
>   child: _buildRefreshIndicatorData(),
> );
> ```
> 
> `
> 
> In my case, I have a **Custom Header** which returns different widgets based on the status of the ProgressIndicator. My custom widgets use **Expanded** - This will cause the issue that you are seeing - if you define a fixed size so that it is not unbounded then you will no longer see this issue.
> 
> So to **RESOLVE** ** restructure your custom header** to not use ANY expanded widgets.

**Comment by yanqibd** [comment]
> This issue is caused because you potentially have a Custom progress indicator that you use in this plugin. i.e you may have something like :
> 
> `
> return SmartRefresher(
> enablePullDown: true,
> enablePullUp: false,
> 
> ```
>   header: CustomHeader(
>       height: 120,
>       refreshStyle: RefreshStyle.Follow,
>       builder: (context, status) {
>         return PullDownRefresh(
>           color: ColorHelper.getSecondaryColourForTheme(),
>         );
>         switch (status) {
>           case RefreshStatus.completed:
>             return Refreshed(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           case RefreshStatus.idle:
>             return PullDownRefresh(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           case RefreshStatus.canRefresh:
>             return ReleaseToRefresh(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
> 
>           case RefreshStatus.refreshing:
>             return Refreshing(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           case RefreshStatus.failed:
>             return RefreshFailed(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>           default:
>             return Refreshing(
>               color: ColorHelper.getSecondaryColourForTheme(),
>             );
>         }
>       }),
>   controller: _refreshController,
>   onRefresh: _onRefresh,
>   onLoading: _onLoading,
>   child: _buildRefreshIndicatorData(),
> );
> ```
> 
> `
> 
> In my case, I have a **Custom Header** which returns different widgets based on the status of the ProgressIndicator. My custom widgets use **Expanded** - This will cause the issue that you are seeing - if you define a fixed size so that it is not unbounded then you will no longer see this issue.
> 
> So to **RESOLVE** ** restructure your custom header** to not use ANY expanded widgets.


Thank you for the answer, but I checked the code and found that the **expanded** component is not used。

there is my code:

```
Widget build(BuildContext context) {
    return CustomHeader(
      builder: (_, mode) {
        String customText;
        if (widget.customTextBuilder != null) {
          customText = widget.customTextBuilder(mode);
        }
        if (mode == RefreshStatus.idle) {
          return RefreshIcon(isLinear: true, color: widget.iconColor);
        } else if (mode == RefreshStatus.canRefresh) {
          return RefreshIcon(isLinear: true, color: widget.iconColor);
        } else if (mode == RefreshStatus.refreshing) {
          return RefreshIcon(isLinear: false, color: widget.iconColor);
        } else if (mode == RefreshStatus.completed) {
          return NotifyTips(
            backgroundColor: widget.tipBackgroundColor,
            text: customText ?? "refresh done",
          );
        } else if (mode == RefreshStatus.failed) {
          return NotifyTips(
            backgroundColor: widget.tipBackgroundColor,
            text: customText ?? "refresh failed",
          );
        }
        return SizedBox();
      },
      height: kHeaderHeight,
      completeDuration: Duration(seconds: 1),
    );
  }
RefreshIcon:

Widget build(BuildContext context) {
    return Container(
      height: kHeaderHeight,
      alignment: Alignment.bottomCenter,
      padding: EdgeInsets.only(bottom: 4),
      child: LoadingIcon(
        color: color,
        curve: isLinear ? Curves.linear : Curves.easeInOut,
        size: 24,
      ),
    );
  }
NotifyTips:

 return Container(
      alignment: Alignment.bottomCenter,
      height: kHeaderHeight,
      padding: EdgeInsets.only(bottom: 4),
      child:.......
      )


```

**Comment by paintingStyle** [comment]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/22866404/147815449-e5524209-0a45-4c91-ad24-f283bdbf1389.png">

```
```

**Comment by paintingStyle** [comment]
```
RefreshConfiguration(
        headerBuilder: () => RefreshHeader(),
        footerBuilder: () => RefreshFooter(),
      
   );
```

```
class RefreshHeader extends StatelessWidget {
  final textStyle = MHHTextStyles.dark14.copyWith(color: MHHColors.gray);

  @override
  Widget build(BuildContext context) {
    return CustomHeader(
      completeDuration: Duration(milliseconds: 200),
      builder: (context, mode) {
        Widget body = SizedBox();
        if (mode == RefreshStatus.idle) {
          body = Text('refresh_idle'.tr, style: textStyle);
        } else if (mode == RefreshStatus.refreshing) {
          body = MHHLoadingIndicator(
            size: 20,
            strokeWidth: 2,
          );
        } else if (mode == RefreshStatus.canRefresh) {
          body = Text('refresh_canRefresh'.tr, style: textStyle);
        } else if (mode == RefreshStatus.completed) {
          body = Text('refresh_completed'.tr, style: textStyle);
        } else if (mode == RefreshStatus.failed) {
          body = Text('refresh_failed'.tr, style: textStyle);
        }
        return Container(
          height: 60.0,
          child: Center(
            child: body,
          ),
        );
      },
      onModeChange: (RefreshStatus? status) {
        if (status == RefreshStatus.canRefresh) {
          HapticFeedback.mediumImpact();
        }
      },
    );
  }
}
```

**Comment by paintingStyle** [comment]
I always collect such exceptions. I don't know how to solve them. There is my code on them
<img width="888" alt="image" src="https://user-images.githubusercontent.com/22866404/148868629-8a8cafa5-571d-40ba-aac8-40d87d837da7.png">
