### ISSUE TITLE
无法保持ListView.builder在PageView切换时的Offset

### ISSUE THREAD

**Issue by maxcong** [peng8350/flutter_pulltorefresh#53]
我的业务当中采用PageView对页面进行左右切换。纯ListView.builder的情况下，通过下面的方式可以保持Offset状态，
`

ListView.builder(

key: PageStorageKey("list"),

controller: ScrollController(keepScrollOffset: true)

)

`

但只要将SmartRefresher引入进来，ListView便失去了保持Offset的能力。

我尝试去查看源码，发现SmartRefresher的ScrollController是私有属性。请问作者有没有能解决这样问题的思路呢？

**Comment by peng8350** [comment]
是我没引用key,我之前是认为用不上key的。

**Comment by peng8350** [comment]
在child里的key设置即可,内部引用
