### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by jkl2323** [peng8350/flutter_pulltorefresh#55]
数据量比较小时，比如有一到3个数据下拉刷新  会触发下拉刷新和加载更多    都同时触发了 下拉刷新的动画和上啦加载更多的动画都有展示    应该只展示下拉刷新才对

**Comment by peng8350** [comment]
这个问题已经提了很多次了,可能我说明文档没有把这个问题详情放到前面去吧, #37

**Comment by luoxuguang** [comment]
> 这个问题已经提了很多次了,可能我说明文档没有把这个问题详情放到前面去吧, #37

不是简单的隐藏，你给的demo也有这个问题，只要一两条数据下拉刷新是有问题的

**Comment by peng8350** [comment]
@luoxuguang 什么问题?

**Comment by luoxuguang** [comment]
> @luoxuguang 什么问题?

没有设置footerConfig, foot的刷新会受下拉影响，当时没找到原因，现在解决啦，还是谢谢啦
