### ISSUE TITLE
建议：增加cacheExtent 配置功能

### ISSUE THREAD

**Issue by richartan** [peng8350/flutter_pulltorefresh#56]
项目遇到一个问题：需要统计列表中的卡片曝光，但是发现CustomScrollView默认预加载不在可是范围内的卡片
建议：增加CustomScrollView中cacheExtent 的配置功能@peng8350 
return new LayoutBuilder(builder: (context, cons) {
      return new Stack(
        children: <Widget>[
          new Positioned(
              top: !widget.enablePullDown || widget.headerConfig is LoadConfig
                  ? 0.0
                  : -(widget.headerConfig as RefreshConfig).height,
              bottom: !widget.enablePullUp || widget.footerConfig is LoadConfig
                  ? 0.0
                  : -(widget.footerConfig as RefreshConfig).height,
              left: 0.0,
              right: 0.0,
              child: new NotificationListener(
                child: new CustomScrollView(
                  physics: new RefreshScrollPhysics(
                      enableOverScroll: widget.enableOverScroll),
                  controller: _scrollController,
                  slivers: slivers,
                  **cacheExtent: widget.cacheExtent,**
                ),
                onNotification: _dispatchScrollEvent,
              )),
        ],
      );

**Comment by peng8350** [comment]
新版本已追加!
