### ISSUE TITLE
I can't pull to refresh with Stream Builder

### ISSUE THREAD

**Issue by Velkamhell97** [peng8350/flutter_pulltorefresh#577]
I can't pull to refresh when my ListView childrens are ListTile

```
body: SmartRefresher(
        controller: _refreshController,
        onRefresh: _onRefresh,
        enablePullUp: true,
        header: WaterDropHeader(
          idleIcon: const Icon(Icons.check, color: Colors.white, size: 15,),
          waterDropColor: Colors.blue,
          complete: Icon(Icons.check_circle, color: Colors.blue.shade300),
        ),
        child:  StreamBuilder<List<User>>(
          stream: users.stream,
          initialData: [],
          builder: (context, snapshot) => ListView.separated(
            physics: const BouncingScrollPhysics(),
            separatorBuilder: (context, index) => const Divider(thickness: 1), 
            itemCount: 10,
            itemBuilder: (context, index) {
              return _UserTile(user: User.test[0]);
            }, 
          ),
        )
      )
```

Please tell me if i am making any mistake, thanks a lot!

**Comment by papakay** [comment]
@Velkamhell97 please how did you manage to resolve this?

**Comment by adamcastleman** [comment]
The whole idea of streams is that you would not need pull to refresh. The Widget will update automatically when changes are made to the data.

You would need pull to refresh in something like FutureBuilder, where changes to data would not be made available to your app without you needing to manually update the request (hence pull to refresh)

Even if you could get pull to refresh to work in this instance, it would not be useful.
