### ISSUE TITLE
A RenderViewport exceeded its maximum number of layout cycles.

### ISSUE THREAD

**Issue by lymanllm** [peng8350/flutter_pulltorefresh#58]
flutter: The following assertion was thrown during performLayout():
flutter: A RenderViewport exceeded its maximum number of layout cycles.
flutter: RenderViewport render objects, during layout, can retry if either their slivers or their
flutter: ViewportOffset decide that the offset should be corrected to take into account information collected
flutter: during that layout.
flutter: In the case of this RenderViewport object, however, this happened 10 times and still there was no
flutter: consensus on the scroll offset. This usually indicates a bug. Specifically, it means that one of the
flutter: following three problems is being experienced by the RenderViewport object:
flutter:  * One of the RenderSliver children or the ViewportOffset have a bug such that they always think
flutter:    that they need to correct the offset regardless.
flutter:  * Some combination of the RenderSliver children and the ViewportOffset have a bad interaction such
flutter:    that one applies a correction then another applies a reverse correction, leading to an infinite
flutter:    loop of corrections.
flutter:  * There is a pathological case that would eventually resolve, but it is so complicated that it
flutter:    cannot be resolved in any reasonable number of layout passes.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderViewport.performLayout.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1255:9)
flutter: #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1275:6)
flutter: #2      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
flutter: #3      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:336:19)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #13     _invoke (dart:ui/hooks.dart:209:10)
flutter: #14     _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderViewport#d4cc3 NEEDS-LAYOUT NEEDS-PAINT
flutter:   creator: Viewport ← IgnorePointer-[GlobalKey#937ad] ← Semantics ← Listener ← _GestureSemantics ←
flutter:   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#4cc4c] ← _ScrollableScope ←
flutter:   _ScrollSemantics-[GlobalKey#b2d24] ← Scrollable ← CustomScrollView ←
flutter:   NotificationListener<ScrollNotification> ← Positioned ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=414.0, h=690.2)
flutter:   layer: OffsetLayer#fe986
flutter:   size: Size(414.0, 690.2)
flutter:   axisDirection: down
flutter:   crossAxisDirection: right
flutter:   offset: ScrollPositionWithSingleContext#4cfa0(offset: 390.3, range: 0.0..942.6, viewport: 690.2,
flutter:   ScrollableState, RefreshScrollPhysics -> BouncingScrollPhysics,
flutter:   BallisticScrollActivity#20ecb(AnimationController#aca4d(▶ 390.271; for BallisticScrollActivity)),
flutter:   ScrollDirection.forward)
flutter:   anchor: 0.0
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:   RenderSliverToBoxAdapter#5bee7 relayoutBoundary=up1 NEEDS-PAINT
flutter:     RenderFlex#44dc1 relayoutBoundary=up2 NEEDS-PAINT
flutter:       RenderClipRect#1aa0c relayoutBoundary=up3 NEEDS-PAINT
flutter:         RenderPositionedBox#7c696 relayoutBoundary=up4 NEEDS-PAINT
flutter:           RenderConstrainedBox#739fd relayoutBoundary=up5 NEEDS-PAINT
flutter:       RenderConstrainedBox#c24db relayoutBoundary=up3 NEEDS-PAINT
flutter:         RenderPositionedBox#ad1e1 relayoutBoundary=up4 NEEDS-PAINT
flutter:           RenderFlex#4f03b relayoutBoundary=up5 NEEDS-PAINT
flutter:   RenderSliverPadding#1a576 relayoutBoundary=up1 NEEDS-PAINT
flutter:     RenderSliverList#e8b20 relayoutBoundary=up2 NEEDS-PAINT
flutter:       RenderIndexedSemantics#1d327 relayoutBoundary=up3 NEEDS-PAINT
flutter:         RenderRepaintBoundary#6dbfd relayoutBoundary=up4 NEEDS-PAINT
flutter:           RenderSemanticsGestureHandler#7b5f3 relayoutBoundary=up5 NEEDS-PAINT
flutter:       RenderIndexedSemantics#93adb relayoutBoundary=up3 NEEDS-PAINT
flutter:         RenderRepaintBoundary#7b3f7 relayoutBoundary=up4 NEEDS-PAINT
flutter:           RenderSemanticsGestureHandler#b95bc relayoutBoundary=up5 NEEDS-PAINT
flutter:       RenderIndexedSemantics#f8e83 relayoutBoundary=up3 NEEDS-PAINT
flutter:         RenderRepaintBoundary#f526b relayoutBoundary=up4 NEEDS-PAINT
flutter:           RenderSemanticsGestureHandler#2a276 relayoutBoundary=up5 NEEDS-PAINT
flutter:       RenderIndexedSemantics#d0d4a relayoutBoundary=up3
flutter:         RenderRepaintBoundary#b2481 relayoutBoundary=up4
flutter:           RenderSemanticsGestureHandler#0fac2 relayoutBoundary=up5
flutter:       RenderIndexedSemantics#a1d46 relayoutBoundary=up3
flutter:         RenderRepaintBoundary#673e3 relayoutBoundary=up4
flutter:           RenderSemanticsGestureHandler#3e41c relayoutBoundary=up5
flutter:       RenderIndexedSemantics#53915 relayoutBoundary=up3
flutter:         RenderRepaintBoundary#4a2a2 relayoutBoundary=up4
flutter:           RenderSemanticsGestureHandler#9c8ef relayoutBoundary=up5
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by peng8350** [comment]
Detailed description of how this happened, show the important code

**Comment by DingXuefeng** [comment]
也遇到这个问题了
