### ISSUE TITLE
Triggering of load more when page reaches the end in web from desktop

### ISSUE THREAD

**Issue by jcblancomartinez** [peng8350/flutter_pulltorefresh#581]
Hi,

I want to trigger the loading of more results for desktop's browsers. Pull up to load more results is appropriate for mobile and web from mobile experiences, however, for web from desktop experience, I would want to trigger the loading of more results when the end of the page is reached (either via scrolling down using mouse's scroll wheel or using the scroll bar).

- Currently are there other ways to trigger the loading of results other than with "Pull up" for web from desktop? I was able to trigger the loading of results after clicking multiple times around the bottom of the scrollbar.

https://user-images.githubusercontent.com/1192455/161711648-4a301361-b97f-4420-b375-8d45cc8d125b.mp4

- Could you please expose a method to trigger the loading of results programmatically?

```
NotificationListener<ScrollNotification>(
                        onNotification: (ScrollNotification scrollInfo) {
                          if (scrollInfo is ScrollUpdateNotification &&
                              scrollInfo.metrics.pixels ==
                                  scrollInfo.metrics.maxScrollExtent && kIsWeb &&
                      (defaultTargetPlatform == TargetPlatform.linux ||
                          defaultTargetPlatform == TargetPlatform.macOS || defaultTargetPlatform == TargetPlatform.windows)) {
                            print('Reached the bottom');
                            // Trigger the loading of more results
                          }
                          return false;
                        },
                        child: SmartRefresher(...))
```

Thanks.

**Comment by jcblancomartinez** [comment]
I've found what I was looking for `refreshController.requestLoading()`

**Comment by DarenF-20C** [comment]
Life-saving suggestion, bro! Huge thanks, it worked perfectly. 🎉

Things to add on, "remember to add your own condition to request loading" to prevent it from keep calling it.
