### ISSUE TITLE
flutter 3.0 support

### ISSUE THREAD

**Issue by jeromekai** [peng8350/flutter_pulltorefresh#591]
^
/D:/soft/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-2.0.0/lib/src/internals/indicator_wrap.dart:393:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/soft/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {

**Comment by educoutinho** [comment]
Warnings after migrate do flutter 3:

```
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-2.0.0/lib/src/smart_refresher.dart:788:20:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-2.0.0/lib/src/smart_refresher.dart:796:20:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-2.0.0/lib/src/smart_refresher.dart:803:20:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-2.0.0/lib/src/internals/indicator_wrap.dart:260:24:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-2.0.0/lib/src/internals/indicator_wrap.dart:290:22:
/c:/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-2.0.0/lib/src/internals/indicator_wrap.dart:393:22:

Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/c:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
```

**Comment by amadridAgg** [comment]
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance!.addPostFrameCallback((_) {
                       ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

**Comment by rudian** [comment]
> : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> 
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
> * 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
>   SchedulerBinding.instance!.addPostFrameCallback(
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.addObserver(this);
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> * 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
>   WidgetsBinding.instance!.removeObserver(this);
>   ^
>   : Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
> * 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
>   SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
>   ^
>   : Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
> * 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
>   SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
> * 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
>   SchedulerBinding.instance!.addPostFrameCallback((_) {
>   ^
>   : Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
> * 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Downloads/flutter/packages/flutter/lib/src/scheduler/binding.dart').
>   SchedulerBinding.instance!.addPostFrameCallback((_) {
>   ^

Please add this to your pubspec.yaml file while this repo haven't approved the PR
`dependency_overrides:
    pull_to_refresh:
        git:
            url: https://github.com/miquelbeltran/flutter_pulltorefresh`

**Comment by rudian** [comment]
dependency_overrides:
    pull_to_refresh:
        git:
            url: https://github.com/miquelbeltran/flutter_pulltorefresh

**Comment by nixonoftheyear** [comment]
> dependency_overrides: pull_to_refresh: git: url: https://github.com/miquelbeltran/flutter_pulltorefresh

this doesn't work for me.
when i try to 'flutter pub get' i have this error:
```
Because myProject depends on dependency_overrides from unknown source "pull_to_refresh", version solving failed.
pub get failed (1; Because myProject depends on dependency_overrides from unknown source "pull_to_refresh", version solving failed.)
```

**Comment by mdeimert** [comment]
@nixonoftheyear 

Use it like this:

dependency_overrides:
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh
      ref: master

**Comment by nixonoftheyear** [comment]
> @nixonoftheyear
> 
> Use it like this:
> 
> dependency_overrides: pull_to_refresh: git: url: https://github.com/miquelbeltran/flutter_pulltorefresh ref: master

another error now:
`Because myProject depends on dependency_overrides from unknown source "pull_to_refresh", version solving failed.
`
is there any command for enable unknow source or anything similar?

**Comment by mdeimert** [comment]
You have original dependency added in dependencies?

dependencies:
      pull_to_refresh: ^2.0.0
      
dependency_overrides:
pull_to_refresh:
git:
url: https://github.com/miquelbeltran/flutter_pulltorefresh
ref: master

This one works for me without any issue.

**Comment by mdeimert** [comment]
Also please remember that spacing/tabulation in yaml file is important the dependency_overrides needs to be at the same level as dependencies.

Like this:
![Zrzut ekranu 2022-05-19 o 21 49 28](https://user-images.githubusercontent.com/41264745/169391165-1ad0fedf-25da-49e4-96de-e36357086586.png)

**Comment by nixonoftheyear** [comment]
> Also please remember that spacing/tabulation in yaml file is important the dependency_overrides needs to be at the same level as dependencies.
> 
> Like this: ![Zrzut ekranu 2022-05-19 o 21 49 28](https://user-images.githubusercontent.com/41264745/169391165-1ad0fedf-25da-49e4-96de-e36357086586.png)

yes, i have
but android studio  highlight suggest: Remove prohibited property "pull_to_refresh"

<img width="513" alt="image" src="https://user-images.githubusercontent.com/13642182/169391383-8f3b7acf-b9af-4d22-9a5a-bc12589670a6.png">

**Comment by nixonoftheyear** [comment]
> Also please remember that spacing/tabulation in yaml file is important the dependency_overrides needs to be at the same level as dependencies.
> 
> Like this: ![Zrzut ekranu 2022-05-19 o 21 49 28](https://user-images.githubusercontent.com/41264745/169391165-1ad0fedf-25da-49e4-96de-e36357086586.png)

resolved! i was wrong to align dependency_overrides as the daughter of dependencies. thank you!
is it normal that the flutter pub get takes a long time (72 seconds instead 3 seconds)?

**Comment by mdeimert** [comment]
> > Also please remember that spacing/tabulation in yaml file is important the dependency_overrides needs to be at the same level as dependencies.
> > Like this: ![Zrzut ekranu 2022-05-19 o 21 49 28](https://user-images.githubusercontent.com/41264745/169391165-1ad0fedf-25da-49e4-96de-e36357086586.png)
> 
> resolved! i was wrong to align dependency_overrides as the daughter of dependencies. thank you! is it normal that the flutter pub get takes a long time (72 seconds instead 3 seconds)?

Great :) 

Could be if fetching first time some repo.

**Comment by cybrox** [comment]
While I greatly appreciate miquelbeltran's effort on providing a fork, I urge people to use `ref: 6d7fbdd` instead of just `ref: master` in your dependency overrides.

Using `ref: master` means whatever is commited to that repository is bundled and delivered in your application, no questions asked.

**Comment by miquelbeltran** [comment]
Hi everyone! **I don't endorse the use of my fork (because I don't plan on maintaining it)**, instead, please insist on the library authors to merge this PR: https://github.com/peng8350/flutter_pulltorefresh/pull/589

**Comment by Mahrash-Malik** [comment]
same issue

**Comment by jeromekai** [comment]
pub search pull_to_refresh_flutter3
