### ISSUE TITLE
TabBarView  相隔Tab点击切换（相隔Tab不是相邻Tab），出现 setState() called after dispose() 错误

### ISSUE THREAD

**Issue by CR903** [peng8350/flutter_pulltorefresh#6]
![image](https://user-images.githubusercontent.com/7643647/43250243-7d37d6aa-90ef-11e8-8850-2f4ac5550978.png)

**Comment by peng8350** [comment]
大致原因是因为控件被新建了然后立马被销毁,导致我后面setState引发的异常。而TabBarView这个控件又带有缓存和销毁页面的功能,但我刚刚测试了一遍,我发现一个问题就是,比如,我从页面一跳到页面三的时候,我的执行log是这样的:

```
  1.页面一 initState
  2.页面一 dispose
  3.页面三 initState
  4.页面二 initState
  5.页面一 dispose
  6.页面二 dispose

```
从log看出来,页面一是被new了两次,这就导致另外一个可能会出现的Bug:如果你页面一带有GlobalKey,你就会报GlobalKey被重复使用的异常。这点,我不明白为什么官方要这样做,理论上页面二初始化之后不应该立马销毁才是。

所以,目前来说,这个问题我也找不到什么好的解决办法

**Comment by lyquocnam** [comment]
you could try:
```
if (mounted) {
    setState(() {
       // ....
    });
}
```
for checking everytime `setState` if not sure it safe or not. That's my solution on another project

**Comment by YouCii** [comment]
这个问题我碰见过类似情景, 记在这了 [https://blog.csdn.net/j550341130/article/details/88102927](https://blog.csdn.net/j550341130/article/details/88102927)

**Comment by peng8350** [comment]
may be fixed after I remove the setState
