### ISSUE TITLE
Refresh on pull on listview

### ISSUE THREAD

**Issue by arualana** [peng8350/flutter_pulltorefresh#600]
I have a scaffold with a header and a listview
The pull to refresh only works when pulling down on the header, not on the list view

Is there a way to make it work on both? Thank you

**Comment by gehad-ahmed-mohammed** [comment]
I have the same problem ... did you find solution for that ?

**Comment by arualana** [comment]
@gehad-ahmed-mohammed yes, you need to wrap the ListView directly with the SmartRefresh, and it will work on the ListView
