### ISSUE TITLE
pull_to_refresh 1.3.0 always show bottom loading

### ISSUE THREAD

**Issue by pmrajani** [peng8350/flutter_pulltorefresh#61]
please fix this

**Comment by dexcell** [comment]
same issue

**Comment by peng8350** [comment]
sorry,I don't quite understand what you mean.Do you mean that the indicator does not occupy any height?

**Comment by peng8350** [comment]
I understand,thet two bool value I forgot it

**Comment by peng8350** [comment]
1.3.1 has fixed

**Comment by Arkangel12** [comment]
this was never fixed? 

i am having an error here i will walk you true what happening to me.

i have my items in the SmartRefresher and it works the first time i try to load older items on the list, but i am doing it a second time i find out that the mode is LoadStatus.loading forever, this never get back do idle or something else different so its always showing my custom loading footer.

please let me know if you need more details.

**Comment by ismaelAbogabal** [comment]
This is not working for me to 
I am testing on Windows 11 
This feature is required because users have no way to load more using there mouce
