### ISSUE TITLE
Why do the widgets enlarge in size when I refresh?

### ISSUE THREAD

**Issue by huynguyen96419** [peng8350/flutter_pulltorefresh#644]
Sometimes when I swipe down to refresh the data, the size of the widgets enlarges. But when I scroll down, they return to their normal size.
From this:
![Screenshot 2024-02-21 at 1 25 13 PM](https://github.com/peng8350/flutter_pulltorefresh/assets/127708425/2c2803d4-88e5-4bc1-b6b3-0d1312a72c78)

To this:
![Screenshot 2024-02-21 at 1 26 00 PM](https://github.com/peng8350/flutter_pulltorefresh/assets/127708425/90d032bd-bf43-46e3-b726-e49de287ed64)

My code:
```
class ListLoader extends StatelessWidget {
  final Widget child;
  final RefreshController controller;
  final Future<dynamic>? Function()? onRefresh;
  final Future<dynamic>? Function()? onLoadMore;
  final bool hasNext;
  final bool hasLoadComplete;

  const ListLoader({
    Key? key,
    required this.child,
    required this.controller,
    this.hasNext = false,
    this.onRefresh,
    this.onLoadMore,
    this.hasLoadComplete = true,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return RefreshConfiguration(
      headerBuilder: () => ClassicHeader(
        refreshingText: LocaleKeys.smartRefresh_header_refreshing.tr(),
        releaseText: LocaleKeys.smartRefresh_header_releaseToRefresh.tr(),
        completeText: LocaleKeys.smartRefresh_header_refreshCompleted.tr(),
        idleText: LocaleKeys.smartRefresh_header_pullDownRefresh.tr(),
        failedText: LocaleKeys.smartRefresh_header_refreshFailed.tr(),
      ),
      footerBuilder: () => ClassicFooter(
        loadingText: LocaleKeys.smartRefresh_footer_loading.tr(),
        noDataText: LocaleKeys.smartRefresh_footer_noData.tr(),
        canLoadingText: LocaleKeys.smartRefresh_footer_releaseToLoadMore.tr(),
        idleText: LocaleKeys.smartRefresh_footer_pullUpToLoadMore.tr(),
        failedText: LocaleKeys.smartRefresh_footer_loadMoreFailed.tr(),
      ),
      child: SmartRefresher(
        controller: controller,
        onLoading: _loadMore,
        onRefresh: _refresh,
        enablePullUp: hasNext && onLoadMore != null,
        enablePullDown: onRefresh != null,
        child: child,
      ),
    );
  }

  Future<void> _loadMore() async {
    if (controller.isRefresh) return;
    onLoadMore?.call()?.then(
          (_) => controller.loadComplete(),
          onError: (_) => controller.loadFailed(),
        );
  }

  Future<void> _refresh() async {
    if (hasLoadComplete && controller.isLoading) {
      controller.loadComplete();
    }

    onRefresh?.call()?.then(
          (_) => controller.refreshCompleted(),
          onError: (_) => controller.refreshFailed(),
        );
    if (SessionManager.instance.user != null) {
      getIt<IAuthenticationRepository>().handshake(
          firebaseToken: await FirebaseMessaging.instance.getToken() ?? '');
    }
  }
}
```

I using it like this:
```
ListLoader(
            controller: _refreshController,
            onRefresh: () => _initData(isRefresh: true),
            hasNext: false,
            hasLoadComplete: false,
            child: SingleChildScrollView(
              child: Column(
                children: [
                  Widget...])))
```

``` 
Future<dynamic> _initData({bool isRefresh = false}) async {
    return Future.wait([
    _bloc
    .getMenus(),
    ]);
  }
``` 
For setting the height and width of widgets, I use ScreenUtil().setHeight or ScreenUtil().setWidth, while for font size, I use ScreenUtil().setSp.
So I don't understand why the size is enlarged like that. Help me, pls.

**Comment by giridat** [comment]
Facing the same issue.

**Comment by hrxiang** [comment]
> Sometimes when I swipe down to refresh the data, the size of the widgets enlarges. But when I scroll down, they return to their normal size. From this: ![Screenshot 2024-02-21 at 1 25 13 PM](https://private-user-images.githubusercontent.com/127708425/306520114-2c2803d4-88e5-4bc1-b6b3-0d1312a72c78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjA5NDcsIm5iZiI6MTcwOTg2MDY0NywicGF0aCI6Ii8xMjc3MDg0MjUvMzA2NTIwMTE0LTJjMjgwM2Q0LTg4ZTUtNGJjMS1iNmIzLTBkMTMxMmE3MmM3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwMTE3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmFjYzhkZmU5NWIzYzE3NjUzMTJiM2I4NDE0NzU5N2EzYjcwZDJkMTgxNGRiODdkZDQxMzAxODA2NGQ4ZDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-vI8Sof7aOeqf249yXS0uwOeXgIc3zbg2a_YTZ4Ofm4)
> 
> To this: ![Screenshot 2024-02-21 at 1 26 00 PM](https://private-user-images.githubusercontent.com/127708425/306520197-90d032bd-bf43-46e3-b726-e49de287ed64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjA5NDcsIm5iZiI6MTcwOTg2MDY0NywicGF0aCI6Ii8xMjc3MDg0MjUvMzA2NTIwMTk3LTkwZDAzMmJkLWJmNDMtNDZlMy1iNzI2LWU0OWRlMjg3ZWQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOFQwMTE3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODRkMGFmN2Q2YmZlOWQ1NTUzYmI0YmNiMDE4YjU3OWFhODNkNzA1OTdjMWJmNmMzOWFhMDc4Mzg1NjUwOTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0SzBQI-1Ux8VlGMpK_Klg7ZELb4xe_dcskMixqKpzbs)
> 
> My code:
> 
> ```
> class ListLoader extends StatelessWidget {
>   final Widget child;
>   final RefreshController controller;
>   final Future<dynamic>? Function()? onRefresh;
>   final Future<dynamic>? Function()? onLoadMore;
>   final bool hasNext;
>   final bool hasLoadComplete;
> 
>   const ListLoader({
>     Key? key,
>     required this.child,
>     required this.controller,
>     this.hasNext = false,
>     this.onRefresh,
>     this.onLoadMore,
>     this.hasLoadComplete = true,
>   }) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return RefreshConfiguration(
>       headerBuilder: () => ClassicHeader(
>         refreshingText: LocaleKeys.smartRefresh_header_refreshing.tr(),
>         releaseText: LocaleKeys.smartRefresh_header_releaseToRefresh.tr(),
>         completeText: LocaleKeys.smartRefresh_header_refreshCompleted.tr(),
>         idleText: LocaleKeys.smartRefresh_header_pullDownRefresh.tr(),
>         failedText: LocaleKeys.smartRefresh_header_refreshFailed.tr(),
>       ),
>       footerBuilder: () => ClassicFooter(
>         loadingText: LocaleKeys.smartRefresh_footer_loading.tr(),
>         noDataText: LocaleKeys.smartRefresh_footer_noData.tr(),
>         canLoadingText: LocaleKeys.smartRefresh_footer_releaseToLoadMore.tr(),
>         idleText: LocaleKeys.smartRefresh_footer_pullUpToLoadMore.tr(),
>         failedText: LocaleKeys.smartRefresh_footer_loadMoreFailed.tr(),
>       ),
>       child: SmartRefresher(
>         controller: controller,
>         onLoading: _loadMore,
>         onRefresh: _refresh,
>         enablePullUp: hasNext && onLoadMore != null,
>         enablePullDown: onRefresh != null,
>         child: child,
>       ),
>     );
>   }
> 
>   Future<void> _loadMore() async {
>     if (controller.isRefresh) return;
>     onLoadMore?.call()?.then(
>           (_) => controller.loadComplete(),
>           onError: (_) => controller.loadFailed(),
>         );
>   }
> 
>   Future<void> _refresh() async {
>     if (hasLoadComplete && controller.isLoading) {
>       controller.loadComplete();
>     }
> 
>     onRefresh?.call()?.then(
>           (_) => controller.refreshCompleted(),
>           onError: (_) => controller.refreshFailed(),
>         );
>     if (SessionManager.instance.user != null) {
>       getIt<IAuthenticationRepository>().handshake(
>           firebaseToken: await FirebaseMessaging.instance.getToken() ?? '');
>     }
>   }
> }
> ```
> 
> I using it like this:
> 
> ```
> ListLoader(
>             controller: _refreshController,
>             onRefresh: () => _initData(isRefresh: true),
>             hasNext: false,
>             hasLoadComplete: false,
>             child: SingleChildScrollView(
>               child: Column(
>                 children: [
>                   Widget...])))
> ```
> 
> ```
> Future<dynamic> _initData({bool isRefresh = false}) async {
>     return Future.wait([
>     _bloc
>     .getMenus(),
>     ]);
>   }
> ```
> 
> For setting the height and width of widgets, I use ScreenUtil().setHeight or ScreenUtil().setWidth, while for font size, I use ScreenUtil().setSp. So I don't understand why the size is enlarged like that. Help me, pls.

The same problem occurred when I upgraded the flutter version to the latest 3.19.2, then I downgraded the flutter version to 3.13.9 and the problem disappeared

**Comment by hrxiang** [comment]
The same problem occurred when I upgraded the flutter version to the latest 3.19.2, then I downgraded the flutter version to 3.13.9 and the problem disappeared

**Comment by hrxiang** [comment]
> Facing the same issue.



> Facing the same issue.

I solved this problem using a lower version of flutter

**Comment by giridat** [comment]
I removed the package and have been using refresh indicator by Flutter, lowering Flutter version bad , but if fine for u then ok.

**Comment by giridat** [comment]
> > Facing the same issue.
> 
> 
> 
> > Facing the same issue.
> 
> I solved this problem using a lower version of flutter

I removed the package and have been using refresh indicator by Flutter, lowering Flutter version bad , but if fine for u then ok.

**Comment by huynguyen96419** [comment]
I fixed this issue with set physic for SmartRefresher: 
`        physics: const BouncingScrollPhysics(),
`
