### ISSUE TITLE
enablePullDown: false, enablePullUp: false,  均无效 

### ISSUE THREAD

**Issue by Angelnil** [peng8350/flutter_pulltorefresh#65]
enablePullDown: false, enablePullUp: false,  均无效 。 
忘记判断了 。
  @override
  Widget build(BuildContext context) {
    List<Widget> slivers =
        List.from(widget.child.buildSlivers(context), growable: true);
    if(widget.enablePullDown) {
      slivers.insert(0, widget.header);
    }
    if(widget.enablePullUp){
      slivers.add(widget.footer);
    }
    return NotificationListener(
      child: CustomScrollView(
        physics:
            RefreshScrollPhysics(enableOverScroll: widget.enableOverScroll),
        controller: scrollController,
        cacheExtent: widget.child.cacheExtent,
        slivers: slivers,
        reverse: widget.child.reverse,
      ),
      onNotification: _dispatchScrollEvent,
    );
  }
}

**Comment by figbin** [comment]
我刚想发 issue的。看到有人发了。坑呀

**Comment by peng8350** [comment]
1.3.1已经修正
