### ISSUE TITLE
当列表元素过多时，会导致CPU狂飙。

### ISSUE THREAD

**Issue by zfha** [peng8350/flutter_pulltorefresh#67]
![image](https://user-images.githubusercontent.com/4082233/57287471-2cee8c80-70ea-11e9-92d5-5071bbe47ee8.png)
CustomScrollview silver没有解决列表块 复用的问题？请问下有什么办法解决？

**Comment by peng8350** [comment]
性能这块我不大了解,Item里dispose调用了,应该算是复用了吧
