### ISSUE TITLE
When data length do not than one page, do pull down, got a error The getter 'widget' was called on null.

### ISSUE THREAD

**Issue by arthurzoubin** [peng8350/flutter_pulltorefresh#69]

**Comment by peng8350** [comment]
是和#68 差不多吧?

**Comment by arthurzoubin** [comment]
@peng8350 
不太一样，这个报错是当第一次加载是好的，但是第一次加载加入只有5条数据，不能覆盖整个屏幕的可视区域，这时候去下拉刷新，就出现这个错误

**Comment by arthurzoubin** [comment]
@peng8350 
我的重现步骤是：
第一次加载一个很长的List，所以`enablePullUp`是`true`，然后通过关键字搜索，加载一个较短的List，这时候用`innerListHeight > listHeight`去判断`enablePullUp`，并把它设置成`false`，这时候就会报错了

**Comment by peng8350** [comment]
这个问题1.4.0还有吗
