### ISSUE TITLE
下拉刷新结束后,设置初始数据为1后，会常驻 pull down to resh 文案样式

### ISSUE THREAD

**Issue by xiangwenbin** [peng8350/flutter_pulltorefresh#7]
如题，当初始数据元素为多个，下拉刷新后，回调函数里，将初始的数据设置为1个后，则会出现如图2 bug
未下拉刷新前：
<img width="344" alt="3" src="https://user-images.githubusercontent.com/6227903/43378472-ced33556-93f9-11e8-9b97-cf2ad34cc7d1.png">
下拉刷新结束后：
![1](https://user-images.githubusercontent.com/6227903/43378498-f5ecba22-93f9-11e8-8b16-e0fc85dd6a48.png)
部分 代码如下：
![06b564a0-8d92-4457-9468-063611c85ad0](https://user-images.githubusercontent.com/6227903/43378975-89d2eae8-93fc-11e8-97d3-9d01e4387070.png)

**Comment by xiangwenbin** [comment]
貌似跟下拉刷新这个动作没关系，把初始的元素列表dataList设置成1，默认这个组件上的 pull down to refresh 这个文案样式就是可见的

**Comment by peng8350** [comment]
你的需求应该是和这个人的需求差不多的吧? #5

**Comment by xiangwenbin** [comment]
对，同一个。。。

**Comment by xiangwenbin** [comment]
@peng8350 对同一个

**Comment by peng8350** [comment]
参考 #37
