### ISSUE TITLE
when list data not enough one page , trigger refresh always cause loading.

### ISSUE THREAD

**Issue by zhancheng** [peng8350/flutter_pulltorefresh#70]

**Comment by peng8350** [comment]
Setting enablePullUp to false when less than one page

**Comment by zhancheng** [comment]
@peng8350 at first, the enablePullUp property does not support to dynamic set,  i think the work should be done in the source code, loading always should not be trigger when refreshing, even the content list not enough one page.

**Comment by peng8350** [comment]
[DataSmall](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/sample/DataSmall.dart),See this Example.There is no way to get the actual height of ListView before the interface is rendered.

**Comment by figbin** [comment]
@peng8350 他说的是动态设置 enablePullUp 应该和我提的问题是一样的。刚开始是true重绘后动态设置false，你组件仍然当true处理了。参见 #68

**Comment by peng8350** [comment]
@figbin 1.3.0确实是仍然当true来处理了,1.3.1已经修复,只是没考虑到状态变化移除监听

**Comment by peng8350** [comment]
我想出一种idea去获取内部高度了,可能下一个版本就可以解决

**Comment by peng8350** [comment]
the issue that pulling down also trigger load more has been fixed after some update!(I use useScrollDirection to check if user pulling up ,if not it will never trigger loading)
