### ISSUE TITLE
1.3.1版本问题

### ISSUE THREAD

**Issue by DreamBuddy** [peng8350/flutter_pulltorefresh#72]
1.当navigator -->push-->pop 然后刷新 onRefresh 会被调用两次 （1.2.x无问题)
2.调用requestRefresh 没有下来的动画 但是连续两次调用requestRefresh 就会出现动画 (旧版本无此问题)

**Comment by DreamBuddy** [comment]
问题2 在更新1.3.2以后得到解决了 完美~

**Comment by DreamBuddy** [comment]
补充: 问题2的话 在第一次调用 requestRefresh的时候 也会触发onRefresh方法，但是没有下拉刷新的动画

**Comment by peng8350** [comment]
问题2没有下拉动画的话,其实你可以直接利用ScrollController滑动到-触发高度 ,也可以达到相同效果

**Comment by DreamBuddy** [comment]
@peng8350 
如果先让scrollview有一点位移 再调用requestRefresh就一定会触发下拉刷新的动画，不然第一次就必然不会.. 有点懵逼
现在我的做法是请求requestRefresh之前先scrollController.jumpTo(0.5)............
总之很感谢您回复我

**Comment by peng8350** [comment]
1.3.3 问题应该已经修复了，如果还有问题重新打开！

**Comment by DreamBuddy** [comment]
测试了下，问题2尚未解决
