### ISSUE TITLE
Compiler failed

### ISSUE THREAD

**Issue by xmc123456** [peng8350/flutter_pulltorefresh#73]
`Compiler message:
file:///C:/Users/wangxin/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/flutter_sticky_header-0.3.4/lib/src/widgets/sticky_header_layout_builder.dart:147:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///D:/ProgramFiles/FlutterSDK/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: context);
               ^
Compiler failed on D:\workspace\flutter\flutter_pulltorefresh\example\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by peng8350** [comment]
不清楚，注意flutter版本还有包是否有引入。另外，这类问题问stackoverflow好点
