### ISSUE TITLE
1.3.2有个问题，

### ISSUE THREAD

**Issue by jp1017** [peng8350/flutter_pulltorefresh#75]
加载更多没有数据时，设置为_controller.loadNoData();，再次下拉刷新，导致就这一页数据，底部会一直显示没有更多啦，，，

**Comment by peng8350** [comment]
你可以当数据抓取后,用controller内部footerMode改变它的状态即可。

**Comment by jp1017** [comment]
> 用controller内部footerMode改变它的状态即可。

怎么玩的呢？什么状态做此改变？

**Comment by jp1017** [comment]
下拉刷新时添加    _controller.resetNoData();
