### ISSUE TITLE
ListView reserve not working..

### ISSUE THREAD

**Issue by lanrehnics** [peng8350/flutter_pulltorefresh#79]
child: ListView.builder(
                      padding: EdgeInsets.all(10.0),
                      itemBuilder: (context, index) =>
                          buildItem(index, snapshot.data.documents[index]),
                      itemCount: snapshot.data.documents.length,
                     ===> reverse: true,<=====
                      controller: listScrollController,
                    ),  

not working when wrapped with SmartRefresher widget

**Comment by peng8350** [comment]
I remember that I had fixed the problem after version 1.3.0.

**Comment by peng8350** [comment]
I have got not reply and this problem cannot happen ,close it
