### ISSUE TITLE
1.3.3 requestRefresh 刷新动画未显示的问题 依然存在

### ISSUE THREAD

**Issue by DreamBuddy** [peng8350/flutter_pulltorefresh#80]
调用requestRefresh 没有下来的动画 但是连续两次调用requestRefresh 就会出现动画 (旧版本无此问题)

**Comment by peng8350** [comment]
还有这问题?我这里测试没问题啊,你怎么操作的

**Comment by Vongolatt** [comment]
@peng8350 bug已复现，使用ClassicHeader()可以执行requestRefresh，Android使用的是默认使用的MaterialClassicHeader无法触发requestRefresh

**Comment by peng8350** [comment]
@Vongolatt 你说的无法触发,是不是这种情况:进度条下来了但是又缩回去了?

**Comment by Vongolatt** [comment]
@peng8350 就是没有触发刷新机制，没有触发onrefresh

**Comment by peng8350** [comment]
![gif9](https://user-images.githubusercontent.com/19425362/58149664-68668a80-7c96-11e9-86e8-278e00dc8caa.gif)
像这样是吧?我在Android模拟器才能发现这类情况,而且是有时可以有时不可以

**Comment by Vongolatt** [comment]
@peng8350 不是，是压根就没有出现刷新动画，

**Comment by peng8350** [comment]
@Vongolatt 你用的模拟器是什么

**Comment by Vongolatt** [comment]
@peng8350 真机

**Comment by Vongolatt** [comment]
@peng8350 我修改MaterialClassicHeader的RefreshStyle为follow可以触发_controller.requestRefresh()；建议在看看

**Comment by Vongolatt** [comment]
@peng8350 已确定原因，我在根页面做了异步初始化数据，导致主页面在异步数据加载后又重新加载了一次，这个时候_refreshController.requestRefresh的scrollController已经不是第一次的scrollController导致没有触发方法。

**Comment by peng8350** [comment]
@Vongolatt 没有下来的动画,感觉指示器的状态不是idle,可以先用着scrollController.animateTo,不过我上面图这种情况的话还是需要查明什么原因

**Comment by Vongolatt** [comment]
@peng8350 直接调用scrollController.animateTo也没用，我打过断点，scrollController.animateTo这一步是执行了的，我暂时用计时器解决了，延迟0.3秒可以正常空屏首次加载了。

**Comment by peng8350** [comment]
看来这个问题应该没有了
