### ISSUE TITLE
数据不满一页时如何请求第二页？

### ISSUE THREAD

**Issue by jp1017** [peng8350/flutter_pulltorefresh#81]

**Comment by peng8350** [comment]
新版本新增一个hideWhenNotFull去取消自动隐藏，默认为true

**Comment by jp1017** [comment]
> 新版本新增一个hideWhenNotFull去取消自动隐藏，默认为true

1.4.0还没有呀，，，

**Comment by peng8350** [comment]
定义在classicfooter或者custom footer里

**Comment by peng8350** [comment]
1.4.1后,使用RefreshConfiguration(它是个全局配置的东西,和ScrollConfiguration类似),里面有个hideWhenNotFull,设置为false就可以了

**Comment by jp1017** [comment]
> 1.4.1后,使用RefreshConfiguration(它是个全局配置的东西,和ScrollConfiguration类似),里面有个hideWhenNotFull,设置为false就可以了

Wonderful
