### ISSUE TITLE
SingleChildScrollView不行?

### ISSUE THREAD

**Issue by badboy-tian** [peng8350/flutter_pulltorefresh#83]

**Comment by peng8350** [comment]
不行,它不是继承ScrollView

**Comment by badboy-tian** [comment]
好的 谢谢 希望增加支持 谢谢

**Comment by peng8350** [comment]
@badboy-tian 没这个必要的,把child放在ListView children内部。之所以要限定ScrollView,那是因为要取出内部的slivers出来

**Comment by badboy-tian** [comment]
Jpeng <notifications@github.com> 于2019年5月17日周五 下午7:03写道：
