### ISSUE TITLE
重大事件

### ISSUE THREAD

**Issue by ZQ330093887** [peng8350/flutter_pulltorefresh#85]
lutter: 'package:pull_to_refresh/src/smart_refresher.dart': error: line 155 pos 7:
flutter: pull_to_refresh-1.3.3/lib/src/smart_refresher.dart:155:7:
flutter: Error: No named parameter with the name 'center'.
flutter:       center: widget.child.center,
flutter:       ^^^^^^
flutter:       center: widget.child.center,

**Comment by peng8350** [comment]
flutter版本多少

**Comment by ZQ330093887** [comment]
原始邮件
发件人:Jpengnotifications@github.com
收件人:peng8350/flutter_pulltorefreshflutter_pulltorefresh@noreply.github.com
抄送:魔君330093887@qq.com; Authorauthor@noreply.github.com
发送时间:2019年5月20日(周一) 16:13
主题:Re: [peng8350/flutter_pulltorefresh] 重大事件 (#85)


flutter版本多少

**Comment by peng8350** [comment]
抱歉,之前没察觉到center和anchor是新增加的属性

**Comment by peng8350** [comment]
确保flutter版本大于等于1.2.1
