### ISSUE TITLE
上拉加载一直报异常

### ISSUE THREAD

**Issue by Hell0wor1d** [peng8350/flutter_pulltorefresh#87]
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching notifications for ValueNotifier<LoadStatus>:
flutter: Looking up a deactivated widget's ancestor is unsafe.
flutter: At this point the state of the widget's element tree is no longer stable. To safely refer to a
flutter: widget's ancestor in its dispose() method, save a reference to the ancestor by calling
flutter: inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3257
flutter: #1      Element._debugCheckStateIsActiveForAncestorLookup 
package:flutter/…/widgets/framework.dart:3266
flutter: #2      Element.ancestorStateOfType 
package:flutter/…/widgets/framework.dart:3314
flutter: #3      SmartRefresher.of 
package:pull_to_refresh/src/smart_refresher.dart:73
flutter: #4      LoadIndicatorState.refresher 
package:pull_to_refresh/…/internals/indicator_wrap.dart:205
flutter: #5      LoadIndicatorState.mode 
package:pull_to_refresh/…/internals/indicator_wrap.dart:207
flutter: #6      LoadIndicatorState.handleModeChange 
package:pull_to_refresh/…/internals/indicator_wrap.dart:262
flutter: #7      ChangeNotifier.notifyListeners

**Comment by Hell0wor1d** [comment]
不知道是不是使用姿势不对，还请作者看看该异常。

**Comment by peng8350** [comment]
别就贴异常信息啊，描述一下怎么触发，或者给出关键代码，不然我也不知道怎么触发这个问题

**Comment by Hell0wor1d** [comment]
已解决，因为其它依赖组件导致，嵌套的Widget导致。辛苦，感谢你的时间和付出。

**Comment by 1181888200** [comment]
同样的问题，请问你是怎么解决的，我是把他放在TabBarView里，然后就出现这样的问题


> 已解决，因为其它依赖组件导致，嵌套的Widget导致。辛苦，感谢你的时间和付出。

`@override
  Widget build(BuildContext context) {
    return DefaultTabController(
    //导航栏的长度
      length: _tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text("${widget.name}"),
          // backgroundColor: Colors.red,
          centerTitle: true,
          bottom: TabBar(
            isScrollable: true, //可滚动
            indicatorColor: Colors.blueGrey, //指示器的颜色
            labelColor: Colors.blueGrey, //选中文字颜色
            unselectedLabelColor: Colors.white, //为选中文字颜色
            // indicatorSize: TabBarIndicatorSize.label, //指示器与文字等宽
            tabs: _tabs,
            controller: _tabController,
          ),
        ),
        body: TabBarView(
          // children: this._tabs.map((e) => _getGoodList()).toList(),
            children: [
                        Container(
                          child: SmartRefresher(
                                key: GlobalKey(),
                                controller: _refreshController,
                                enablePullUp: true,
                                enablePullDown: true,
                                child: _showGoods(),
                                physics: BouncingScrollPhysics(),
                                footer: ClassicFooter(
                                  loadStyle: LoadStyle.ShowWhenLoading,
                                  loadingText: "加载数据",
                                  canLoadingText: "释放刷新数据....",
                                  idleText: "刷新完成",
                                  failedText: "刷新失败",
                                  completeDuration: Duration(milliseconds: 1000),
                                ),
                                onLoading:_loadData,
                                onRefresh: _onRefresh,
                              ),
                        ),
                        
            ],
        ),
      ),
    );
  }`
