### ISSUE TITLE
1.3.6版本不设置下拉刷新就会遮盖一部分内容

### ISSUE THREAD

**Issue by KarenKaKa** [peng8350/flutter_pulltorefresh#88]
如题，在安卓手机上会出现，ios手机上正常

**Comment by KarenKaKa** [comment]
补充一下，1.3.6版本拉着给人的感觉不是BouncingScrollPhysics，同样是在Android手机上

**Comment by peng8350** [comment]
这个确实是个问题,我待会看一下。Android默认使用的是MaterialClassicalheader,这种header使用的是Front刷新风格,Front采用ClampPhysics,这样更使用Android平台多一点

**Comment by peng8350** [comment]
某个版本已解决,应该不会再重现这问题
