### ISSUE TITLE
页面初始化时, 如何让刷新的指示器,进行刷新状态

### ISSUE THREAD

**Issue by hightfly** [peng8350/flutter_pulltorefresh#89]

**Comment by peng8350** [comment]
你是说Front无法初始化时进入刷新状态吧?这是个Bug,已经修复好的了

**Comment by peng8350** [comment]
等下一个版本

**Comment by hightfly** [comment]
> 你是说Front无法初始化时进入刷新状态吧?这是个Bug,已经修复好的了

就是界面刚打开时, 让组件进入刷新状态, 加载数据.

**Comment by peng8350** [comment]
···
 SchedulerBinding.instance.addPostFrameCallback((_) {
         _refreshController.requestRefresh();
        })
;
···

**Comment by yangfanzn** [comment]
> ···
> SchedulerBinding.instance.addPostFrameCallback((_) {
> _refreshController.requestRefresh();
> })
> ;
> ···

SchedulerBinding 提示不存在啊

**Comment by peng8350** [comment]
1.4.0后在RefreshController设置initalRefresh即可
