### ISSUE TITLE
你好，当listview中没有数据更新时，上拉会触发onloading多次，看之前的issues里说在1.3.1版本已经解决了，可是好像1.3.8版本中仍然存在这个问题

### ISSUE THREAD

**Issue by jqhx** [peng8350/flutter_pulltorefresh#91]

**Comment by peng8350** [comment]
你是说footer状态为noMore,仍然会触发onLoading。还是onLoading会触发多次

**Comment by jqhx** [comment]
> 你是说footer状态为noMore,仍然会触发onLoading。还是onLoading会触发多次

onLoading会触发多次

**Comment by peng8350** [comment]
你怎么操作会触发多次,我不断拖上去都没出现问题

**Comment by jqhx** [comment]
> 你怎么操作会触发多次,我不断拖上去都没出现问题

我也是往上拖，我再回调函数里打印了一下footstatus的值 每拖动一次 就会打印很多onLoading
![image](https://user-images.githubusercontent.com/48592894/58371379-59f0cb00-7f43-11e9-9363-39ea0e5e7f15.png)

**Comment by peng8350** [comment]
假如你给他的一个延时就不会有这情况。

**Comment by jqhx** [comment]
> 假如你给他的一个延时就不会有这情况。

刚试了下 延迟1s还是会重复进onloading 2次，延迟2s只会进一次 应该还是哪有bug吧？ 硬延时不太好吧，而且延时时间有点长，线上环境肯定接受不了

**Comment by jqhx** [comment]
当listview里有数据在更新的时候 onloading只会进一次

**Comment by jqhx** [comment]
当listview里有数据在更新的时候 onloading只会进一次，onfresh和下拉操作 无论有没有数据都是进一次

**Comment by peng8350** [comment]
这个问题我想想吧，之前我是没考虑过这个问题

**Comment by jqhx** [comment]
> 这个问题我想想吧，之前我是没考虑过这个问题

好的  非常感谢！期待修复bug

**Comment by peng8350** [comment]
给你一种临时的解决方法,使用NotificationListener 

```
   
      onNotification: (n){
        
        else if(n is ScrollEndNotification){
          _canLoad = true;
        }
      }

  onLoading(){
   if(!_canLoad)return;
   
  _canLoad = false;
 }
```

不过,我内部想要去捕捉这个scrollEnd的事件有点困难,假如flutter能提供一个ScrollActivity改变的回调就好了。

**Comment by jqhx** [comment]
看了下你的源代码 好像没发现在哪里有监听向上拖动状态的代码 是不是可以这样修复一下bug? 增加一个状态监听，当状态为isLoading的时候 不再触发onLoading
另外onLoading函数是通过什么触发的呢 didupdateWidget吗？

**Comment by jqhx** [comment]
![image](https://user-images.githubusercontent.com/48592894/58377958-30748580-7fbd-11e9-82c5-5c620a8c34ee.png)
是不是这个逻辑造成的 当往上拖动的时候 虽然mode没有变化 但是position会变化 那么也会触发onloading的执行

**Comment by peng8350** [comment]
这个问题我已经有办法处理它的了,让非用户手势导致滚动的情况只执行一次就ok,NotificationListener里面有个ScrollEndNotifcation,但是我内部无法使用NotificationListener,所以只能利用ScrollPosition里的isScrollingNotifiter来判断,为false就表示ScrollEnd,对应idleScrollActivity

**Comment by jqhx** [comment]
> 这个问题我已经有办法处理它的了,让非用户手势导致滚动的情况只执行一次就ok,NotificationListener里面有个ScrollEndNotifcation,但是我内部无法使用NotificationListener,所以只能利用ScrollPosition里的isScrollingNotifiter来判断,为false就表示ScrollEnd,对应idleScrollActivity

这样也行那 不过我还有一个情况需要跟你反映一下 我刚打印了一下上边的那个截图的mode，不是因为position的问题导致的，是mode导致的，listview里没有内容的时候，会出现重复的调用_updatelistener,而且传入的mode是RefreshStatus.failed _mode是RefreshStatus.loading 所以就会更新mode 出现重复调用onloading

**Comment by peng8350** [comment]
不太明白,重复调用是正常的,因为你那边不断setState,触发我内部didUpdateWidget,还有RefreshStatus代表顶部指示器的状态,而不是底部加载更多的更多

**Comment by jqhx** [comment]
> 不太明白,重复调用是正常的,因为你那边不断setState,触发我内部didUpdateWidget,还有RefreshStatus代表顶部指示器的状态,而不是底部加载更多的更多


![image](https://user-images.githubusercontent.com/48592894/58378252-ab409f00-7fc3-11e9-8f1f-c3f18545149e.png)

看错了 不好意思  原来上拉也会导致header触发didUpdateWidget 是RefreshStatus由idle变成了failed 不过这应该不会导致modechange 所以不是onloading重复执行的原因

**Comment by jqhx** [comment]
> 这个问题我已经有办法处理它的了,让非用户手势导致滚动的情况只执行一次就ok,NotificationListener里面有个ScrollEndNotifcation,但是我内部无法使用NotificationListener,所以只能利用ScrollPosition里的isScrollingNotifiter来判断,为false就表示ScrollEnd,对应idleScrollActivity

确实是 我先用nofificationlistener解决吧 😄 感谢

**Comment by jqhx** [comment]
> > 不太明白,重复调用是正常的,因为你那边不断setState,触发我内部didUpdateWidget,还有RefreshStatus代表顶部指示器的状态,而不是底部加载更多的更多
> 
> ![image](https://user-images.githubusercontent.com/48592894/58378252-ab409f00-7fc3-11e9-8f1f-c3f18545149e.png)
> 
> 看错了 不好意思 原来上拉也会导致header触发didUpdateWidget 是RefreshStatus由idle变成了failed 不过这应该不会导致modechange 所以不是onloading重复执行的原因
忽略这条吧 rereshstatus failed的问题 应该是我的问题
