### ISSUE TITLE
滑动阻尼

### ISSUE THREAD

**Issue by 330676687** [peng8350/flutter_pulltorefresh#93]
为什么更新到1.3.6及之后的版本 iOS上滑动阻尼特别大 完全没了惯性 1.3.3无此问题 Android正常

**Comment by peng8350** [comment]
大概是之前写FrontStyle时，不小心改动那个参数了

**Comment by 330676687** [comment]
我看了1.3.6的版本更新说明 有说到这个 但是我更新到1.3.6还是不行呢

**Comment by peng8350** [comment]
什么不行?

**Comment by 330676687** [comment]
滑动问题依然存在 1.3.8也是 滑动距离很短

**Comment by peng8350** [comment]
我知道,这是因为我犯傻了没注意到,RefreshBouncingPhysics里不小心改动了里面createBallisticSimulation方法里velocity: velocity * 0.51,本来是velocity * 0.91,怪不得感觉拖动有点慢。我也发现了一个问题,布局越复杂,滑动速度越慢,不知道是不是我的问题

**Comment by 330676687** [comment]
坐等大佬修复哈

**Comment by 330676687** [comment]
已经更新1.3.9 滑动阻尼问题依旧存在

**Comment by peng8350** [comment]
你是用什么header?我是直接复制1.3.3里RefreshBouncing的,刚也测试了,滑动速度快了不少

**Comment by 330676687** [comment]
早上重新编译就没问题了😂 估计是缓存问题
