### ISSUE TITLE
RefreshIndicator with material confict...

### ISSUE THREAD

**Issue by memorycj** [peng8350/flutter_pulltorefresh#95]
The name 'RefreshIndicator' is defined in the libraries 'package:flutter/src/material/refresh_indicator.dart'  and 'package:pull_to_refresh/src/internals/refresh_wrap.dart'

**Comment by peng8350** [comment]
import 'package:flutter/material.dart'
    hide RefreshIndicator, RefreshIndicatorState

**Comment by memorycj** [comment]
tk..

**Comment by Ta0ge** [comment]
how to hide RefreshIndicator, RefreshIndicatorState?
