### ISSUE TITLE
让下拉刷新动画的展示位置可以配置

### ISSUE THREAD

**Issue by yangfanzn** [peng8350/flutter_pulltorefresh#98]
![image](https://user-images.githubusercontent.com/11271453/58622466-40160600-82fe-11e9-8583-70ac7e6964ba.png)
默认是在 CustomScrollView的第一个slivers的位置展示下拉刷新动画
    if (widget.enablePullDown) {
      slivers.insert(0, widget.header);
    }
我在项目中使用了 SliverAppBar, 所以不适合在第一个位置展示下拉刷新动画
所以能否在上面的代码处加一个参数, 能让拉下刷新位置在截图中的地方展示??
    if (widget.enablePullDown) {
      slivers.insert(将此参数进行配置, widget.header);
    }

**Comment by peng8350** [comment]
我内部给每个指示器提供了一个asSliver的构造方法,你可以使用asSliver这个构造方法放在CustomScrollView的slivers属性里。详细的例子可以看README第二种实现方式,也可以看这里 [Example](https://github.com/peng8350/flutter_pulltorefresh/blob/master/example/lib/ui/test/Example4.dart)

**Comment by peng8350** [comment]
下个版本加入

**Comment by peng8350** [comment]
然而这个问题并没有解决,触发刷新后往上移动一定距离,刷新完毕后会瞬间跳动

**Comment by peng8350** [comment]
只能依赖于NestedScrollView来实现这种内刷新外嵌套的效果,在非第一个sliver做刷新是不可能的,因为我还要考虑到ScrollBar的显示效果,只能靠越界.而现在NestedScrollView存在的问题也挺多,具体表现在:第一,下拉越界了再慢慢上啦,调度的是外部controller非内部controller.第二,下拉快速往上拉惯性反弹,第三,TabBarView下多个widget keepalive,多个ScrollPosition保持同样的offset。

**Comment by yangfanzn** [comment]
> 只能依赖于NestedScrollView来实现这种内刷新外嵌套的效果,在非第一个sliver做刷新是不可能的,因为我还要考虑到ScrollBar的显示效果,只能靠越界.而现在NestedScrollView存在的问题也挺多,具体表现在:第一,下拉越界了再慢慢上啦,调度的是外部controller非内部controller.第二,下拉快速往上拉惯性反弹,第三,TabBarView下多个widget keepalive,多个ScrollPosition保持同样的offset。

谢谢您对此所做的努力.
