### ISSUE TITLE
当第一个item还在屏幕上的时候，进入新页面返回会有下拉的动画

### ISSUE THREAD

**Issue by 3067200952** [peng8350/flutter_pulltorefresh#99]
![123](https://user-images.githubusercontent.com/44740855/58758044-2cf67680-8548-11e9-91e3-f76f06592c09.gif)

**Comment by 3067200952** [comment]
return Scaffold(
      body: SmartRefresher(
        controller: _refreshController,
        enablePullDown: true,
        enablePullUp: true,
        child: ListView.builder(
          controller: ScrollController(),
          physics: AlwaysScrollableScrollPhysics(),
          itemBuilder: (_, index) {
            return InkWell(
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (_) {
                  return Scaffold(
                    appBar: AppBar(),
                  );
                }));
              },
              child: Container(
                color: Colors.grey,
                height: 200,
                margin: EdgeInsets.only(top: 20),
              ),
            );
          },
        ),
      ),
    );

**Comment by peng8350** [comment]
这问题是我内部移除头部后修正offset产生的,flutter好像没提供一个生命周期可以在组件准备销毁前处理(界面还没被刷新),在dispose方法处理的话就更不安全了。目前发现dirty好像可以区分开来,只不过不知道还有没有别的生命周期调用的情况

**Comment by peng8350** [comment]
1.4.1 这问题应该干掉了,但不知道还有没有别的类似情况,观察中

**Comment by peng8350** [comment]
这个问题不会再发生的了,新版本重做了FrontStyle实现机制,在每次移除操作不需要再改动offset
